In [1]:
# Establishing project paths, Azure connection and source file registry

import os
import csv
import pandas as pd
import numpy as np

from io import BytesIO
from pathlib import Path

from azure.storage.blob import BlobServiceClient

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 180)

current_working_directory = Path.cwd().resolve()
project_root = current_working_directory.parent if current_working_directory.name == "notebooks" else current_working_directory

storage_connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING")

if not storage_connection_string:
    raise ValueError("AZURE_STORAGE_CONNECTION_STRING environment variable is not set.")

blob_service_client = BlobServiceClient.from_connection_string(storage_connection_string)

container_names = {"raw": "raw",
                   "curated": "curated",
                   "presentation": "presentation",
                   "model_output": "model-output"
}

raw_dataset_prefix = "KuaiRand-Pure/data"

source_blob_paths = {"interaction_log_standard_20220408_20220421": f"{raw_dataset_prefix}/log_standard_4_08_to_4_21_pure.csv",
                     "interaction_log_standard_20220422_20220508": f"{raw_dataset_prefix}/log_standard_4_22_to_5_08_pure.csv",
                     "interaction_log_random_20220422_20220508": f"{raw_dataset_prefix}/log_random_4_22_to_5_08_pure.csv",
                     "user_dimension": f"{raw_dataset_prefix}/user_features_pure.csv",
                     "video_dimension_basic": f"{raw_dataset_prefix}/video_features_basic_pure.csv",
                     "video_dimension_statistic": f"{raw_dataset_prefix}/video_features_statistic_pure.csv"
}

# Verifying that all required raw blobs are available
def blob_exists(container_name, blob_name):
    blob_client = blob_service_client.get_blob_client(container = container_name, blob = blob_name)
    return blob_client.exists()

missing_source_blobs = [source_name
                        for source_name, blob_name in source_blob_paths.items()
                        if not blob_exists(container_names["raw"], blob_name)
]

if missing_source_blobs:
    raise FileNotFoundError(f"Missing expected source blobs : {missing_source_blobs}")

print(f"Project root : {project_root}")
print(f"Raw container : {container_names['raw']}")
print("Blob connection established successfully.")

Project root : C:\Users\azureuser\Documents\Short-Video Engagement Analysis
Raw container : raw
Blob connection established successfully.

In [2]:
# Auditing source file structure and size before loading full data

def download_blob_bytes(container_name, blob_name):
    blob_client = blob_service_client.get_blob_client(container = container_name, blob = blob_name)
    return blob_client.download_blob().readall()

def read_csv_header_from_blob(container_name, blob_name):
    blob_bytes = download_blob_bytes(container_name, blob_name)
    first_line = blob_bytes.decode("utf-8").splitlines()[0]
    return next(csv.reader([first_line]))

def count_csv_rows_in_blob(container_name, blob_name):
    blob_bytes = download_blob_bytes(container_name, blob_name)
    line_count = len(blob_bytes.decode("utf-8").splitlines())
    return max(line_count - 1, 0)

source_file_inventory = []

for source_name, blob_name in source_blob_paths.items():
    header_columns = read_csv_header_from_blob(container_names["raw"], blob_name)
    file_row_count = count_csv_rows_in_blob(container_names["raw"], blob_name)

    source_file_inventory.append(
        {
            "source_name": source_name,
            "blob_name": blob_name,
            "row_count": file_row_count,
            "column_count": len(header_columns),
            "columns": ", ".join(header_columns),
        }
    )

source_file_inventory = pd.DataFrame(source_file_inventory).sort_values("source_name").reset_index(drop = True)
source_file_inventory

                                  source_name                                          blob_name  row_count  column_count                                            columns
0    interaction_log_random_20220422_20220508  KuaiRand-Pure/data/log_random_4_22_to_5_08_pur...    1186059            19  user_id, video_id, date, hourmin, time_ms, is_...
1  interaction_log_standard_20220408_20220421  KuaiRand-Pure/data/log_standard_4_08_to_4_21_p...    1141112            19  user_id, video_id, date, hourmin, time_ms, is_...
2  interaction_log_standard_20220422_20220508  KuaiRand-Pure/data/log_standard_4_22_to_5_08_p...     295497            19  user_id, video_id, date, hourmin, time_ms, is_...
3                              user_dimension          KuaiRand-Pure/data/user_features_pure.csv      27285            31  user_id, user_active_degree, is_lowactive_peri...
4                       video_dimension_basic   KuaiRand-Pure/data/video_features_basic_pure.csv       7583            12  video_id, author_id, video_type, upload_dt, up...
5                   video_dimension_statistic  KuaiRand-Pure/data/video_features_statistic_pu...       7583            52  video_id, counts, show_cnt, show_user_num, pla...

In [3]:
# Defining reusable Blob read and write helpers for the workflow

def read_csv_from_blob(container_name, blob_name, **read_csv_kwargs):
    blob_bytes = download_blob_bytes(container_name, blob_name)
    return pd.read_csv(BytesIO(blob_bytes), **read_csv_kwargs)

def read_parquet_from_blob(container_name, blob_name, **read_parquet_kwargs):
    blob_bytes = download_blob_bytes(container_name, blob_name)
    return pd.read_parquet(BytesIO(blob_bytes), **read_parquet_kwargs)

def upload_dataframe_to_parquet_blob(dataframe, container_name, blob_name):
    buffer = BytesIO()
    dataframe.to_parquet(buffer, index = False)
    buffer.seek(0)

    blob_client = blob_service_client.get_blob_client(container = container_name, blob = blob_name)
    blob_client.upload_blob(buffer.getvalue(), overwrite = True)

In [4]:
# Loading source tables with controlled data types for stable ingestion

interaction_dtype_map = {"time_ms": "int64",
                         "user_id": "int32", "video_id": "int32", "date": "int32", "hourmin": "int32", 
                         "play_time_ms": "int32", "duration_ms": "int32", "profile_stay_time": "int32", 
                         "comment_stay_time": "int32",
                         "is_click": "int8", "is_like": "int8", "is_follow": "int8", "is_comment": "int8",
                         "is_forward": "int8", "is_hate": "int8", "long_view": "int8", "is_profile_enter": "int8",
                         "is_rand": "int8", "tab": "int8"
}

interaction_log_standard_20220408_20220421 = read_csv_from_blob(
    container_names["raw"],
    source_blob_paths["interaction_log_standard_20220408_20220421"],
    dtype = interaction_dtype_map
)

interaction_log_standard_20220422_20220508 = read_csv_from_blob(
    container_names["raw"],
    source_blob_paths["interaction_log_standard_20220422_20220508"],
    dtype = interaction_dtype_map
)

interaction_log_random_20220422_20220508 = read_csv_from_blob(
    container_names["raw"],
    source_blob_paths["interaction_log_random_20220422_20220508"],
    dtype = interaction_dtype_map
)

user_dimension = read_csv_from_blob(
    container_names["raw"],
    source_blob_paths["user_dimension"]
)

video_dimension_basic = read_csv_from_blob(
    container_names["raw"],
    source_blob_paths["video_dimension_basic"]
)

video_dimension_statistic = read_csv_from_blob(
    container_names["raw"],
    source_blob_paths["video_dimension_statistic"]
)

print(interaction_log_standard_20220408_20220421.shape)
print(interaction_log_standard_20220422_20220508.shape)
print(interaction_log_random_20220422_20220508.shape)
print(user_dimension.shape)
print(video_dimension_basic.shape)
print(video_dimension_statistic.shape)

(1141112, 19)
(295497, 19)
(1186059, 19)
(27285, 31)
(7583, 12)
(7583, 52)

In [5]:
# Combining interaction logs into one traceable raw event base

interaction_frames = {"log_standard_4_08_to_4_21_pure": interaction_log_standard_20220408_20220421.copy(),
                      "log_standard_4_22_to_5_08_pure": interaction_log_standard_20220422_20220508.copy(),
                      "log_random_4_22_to_5_08_pure": interaction_log_random_20220422_20220508.copy()
}

interaction_source_metadata = {
    "log_standard_4_08_to_4_21_pure": {"traffic_source": "standard",
                                       "source_period": "20220408_20220421"
    },
    "log_standard_4_22_to_5_08_pure": {"traffic_source": "standard",
                                       "source_period": "20220422_20220508"
    },
    "log_random_4_22_to_5_08_pure": {"traffic_source": "random",
                                     "source_period": "20220422_20220508"
    },
}

raw_interaction_log = pd.concat(
    [
        frame.assign(source_file = source_name,
                     traffic_source = interaction_source_metadata[source_name]["traffic_source"],
                     source_period = interaction_source_metadata[source_name]["source_period"]
        )
        for source_name, frame in interaction_frames.items()
    ],
    ignore_index = True
)

print(raw_interaction_log.shape)
raw_interaction_log.head()

(2622668, 22)

,user_id,video_id,date,hourmin,time_ms,is_click,is_like,is_follow,is_comment,is_forward,is_hate,long_view,play_time_ms,duration_ms,profile_stay_time,comment_stay_time,is_profile_enter,is_rand,tab,source_file,traffic_source,source_period
0,0,1527,20220411,1900,1649675512388,0,0,0,0,0,0,0,1385,209900,0,0,0,0,1,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
1,0,7405,20220416,2000,1650111976017,0,0,0,0,0,0,0,0,65400,0,0,0,0,0,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
2,0,6026,20220420,1600,1650444367095,0,0,0,0,0,0,0,1405,170833,0,0,0,0,1,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
3,1,6354,20220411,1100,1649645295928,0,0,0,0,0,0,0,0,255160,0,0,0,0,8,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
4,1,3645,20220411,1100,1649648827559,0,0,0,0,0,0,0,1970,79733,0,0,0,0,1,log_standard_4_08_to_4_21_pure,standard,20220408_20220421

In [6]:
# Auditing duplicate behavior at full-row and event-key level

interaction_columns = list(raw_interaction_log.columns)
duplicate_key_columns = ["user_id", "video_id", "time_ms"]

interaction_audit_table = raw_interaction_log.copy()

# Hashing full rows for separating exact duplicates from conflicting records
interaction_audit_table["record_signature"] = pd.util.hash_pandas_object(
    interaction_audit_table[interaction_columns],
    index = False
)

duplicate_event_key_summary = (
    interaction_audit_table
    .groupby(duplicate_key_columns, as_index = False)
    .agg(record_count = ("user_id", "size"),
         distinct_record_count = ("record_signature", "nunique"),
         source_file_count = ("source_file", "nunique")
    )
)

duplicate_diagnostic_summary = pd.DataFrame(
    {
        "check_name": [
            "full_row_duplicate_count",
            "duplicate_user_video_time_count",
            "duplicate_keys_with_identical_records_only",
            "duplicate_keys_with_conflicting_records",
            "row_count",
            "distinct_user_count",
            "distinct_video_count"
        ],
        "value": [
            int(raw_interaction_log.duplicated().sum()),
            int(raw_interaction_log.duplicated(subset = duplicate_key_columns).sum()),
            int(((duplicate_event_key_summary["record_count"] > 1) & (duplicate_event_key_summary["distinct_record_count"] == 1)).sum()),
            int(((duplicate_event_key_summary["record_count"] > 1) & (duplicate_event_key_summary["distinct_record_count"] > 1)).sum()),
            int(len(raw_interaction_log)),
            int(raw_interaction_log["user_id"].nunique()),
            int(raw_interaction_log["video_id"].nunique())
        ]
    }
)

duplicate_diagnostic_summary

                                   check_name    value
0                    full_row_duplicate_count    21997
1             duplicate_user_video_time_count    23483
2  duplicate_keys_with_identical_records_only    21916
3     duplicate_keys_with_conflicting_records     1486
4                                   row_count  2622668
5                         distinct_user_count    27285
6                        distinct_video_count     7583

In [7]:
# Inspecting example duplicate event keys

duplicate_event_key_examples = (
    duplicate_event_key_summary.loc[duplicate_event_key_summary["record_count"] > 1]
    .sort_values(["distinct_record_count", "record_count"], ascending = [False, False])
    .head(10)
)

duplicate_event_key_examples

         user_id  video_id        time_ms  record_count  distinct_record_count  source_file_count
2114425    22155      1957  1651937555119             5                      2                  1
10730        110      7044  1649597988214             3                      2                  1
84440        881      3740  1649774581330             3                      2                  1
869106      9122      3858  1649774809577             3                      2                  1
1171812    12242       527  1651236457849             3                      2                  1
1598584    16705       124  1649684535855             3                      2                  1
1924022    20134      1052  1649597929901             3                      2                  1
1725          20      7086  1649859935878             2                      2                  1
2239          27       728  1650642130406             2                      2                  1
3487          39      1052  1651362622018             2                      2                  1

In [8]:
# Checking date coverage and source consistency across interaction files

interaction_file_coverage_summary = (interaction_audit_table
                                     .groupby("source_file", as_index = False)
                                     .agg(row_count = ("user_id", "size"),
                                          minimum_date = ("date", "min"),
                                          maximum_date = ("date", "max"),
                                          minimum_time_ms = ("time_ms", "min"),
                                          maximum_time_ms = ("time_ms", "max"),
                                          is_rand_rate = ("is_rand", "mean")
    )
)

interaction_file_coverage_summary["is_rand_rate"] = interaction_file_coverage_summary["is_rand_rate"].round(4)
interaction_file_coverage_summary

                      source_file  row_count  minimum_date  maximum_date  minimum_time_ms  maximum_time_ms  is_rand_rate
0    log_random_4_22_to_5_08_pure    1186059      20220422      20220508    1650595332831    1652025128763           1.0
1  log_standard_4_08_to_4_21_pure    1141112      20220409      20220421    1649475963278    1650556328855           0.0
2  log_standard_4_22_to_5_08_pure     295497      20220422      20220508    1650552767170    1652025130564           0.0

In [9]:
# Summarizing key integrity and missingness in dimension tables

def summarize_dimension_quality(table_name, frame, key_column):
    return {"table_name": table_name,
            "row_count": len(frame),
            "column_count": frame.shape[1],
            "distinct_key_count": frame[key_column].nunique(dropna = False),
            "duplicate_key_count": int(frame.duplicated(subset = [key_column]).sum()),
            "rows_with_any_missing": int(frame.isna().any(axis = 1).sum()),
            "total_missing_values": int(frame.isna().sum().sum())
    }

dimension_quality_summary = pd.DataFrame(
    [
        summarize_dimension_quality("user_dimension", user_dimension, "user_id"),
        summarize_dimension_quality("video_dimension_basic", video_dimension_basic, "video_id"),
        summarize_dimension_quality("video_dimension_statistic", video_dimension_statistic, "video_id")
    ]
)

dimension_quality_summary

                  table_name  row_count  column_count  distinct_key_count  duplicate_key_count  rows_with_any_missing  total_missing_values
0             user_dimension      27285            31               27285                    0                   1563                  5158
1      video_dimension_basic       7583            12                7583                    0                    533                   538
2  video_dimension_statistic       7583            52                7583                    0                      0                     0

In [10]:
# Measuring column-level missingness in supporting dimension tables

dimension_missingness = []

for table_name, frame in {"user_dimension": user_dimension,
                          "video_dimension_basic": video_dimension_basic,
                          "video_dimension_statistic": video_dimension_statistic
}.items():
    missing_summary = pd.DataFrame({"table_name": table_name,
                                    "column_name": frame.columns,
                                    "missing_count": frame.isna().sum().values,
                                    "missing_rate": (frame.isna().mean().values * 100).round(4)
        }
    )
    dimension_missingness.append(missing_summary)

dimension_missingness = (pd.concat(dimension_missingness, ignore_index = True)
                         .query("missing_count > 0")
                         .sort_values(["missing_rate", "table_name", "column_name"], ascending = [False, True, True])
                         .reset_index(drop = True)
)

dimension_missingness

              table_name     column_name  missing_count  missing_rate
0         user_dimension    onehot_feat4            874        3.2032
1  video_dimension_basic  video_duration            239        3.1518
2  video_dimension_basic      music_type            203        2.6770
3         user_dimension   onehot_feat12            714        2.6168
4         user_dimension   onehot_feat13            714        2.6168
5         user_dimension   onehot_feat14            714        2.6168
6         user_dimension   onehot_feat15            714        2.6168
7         user_dimension   onehot_feat16            714        2.6168
8         user_dimension   onehot_feat17            714        2.6168
9  video_dimension_basic             tag             96        1.2660

In [11]:
# Profiling outcome event frequency to confirm analytical usefulness

event_columns = ["is_click", "long_view", "is_like", "is_follow",
                 "is_comment", "is_forward", "is_hate", "is_profile_enter"
]

event_audit = pd.DataFrame(
    {
        "event_name": event_columns,
        "positive_count": [int(raw_interaction_log[column].sum()) for column in event_columns],
        "positive_rate": [(raw_interaction_log[column].mean() * 100).round(4) for column in event_columns],
        "min_value": [raw_interaction_log[column].min() for column in event_columns],
        "max_value": [raw_interaction_log[column].max() for column in event_columns]
    }
).sort_values("positive_rate", ascending = False).reset_index(drop = True)

event_audit

         event_name  positive_count  positive_rate  min_value  max_value
0          is_click          869276        33.1447          0          1
1         long_view          577493        22.0193          0          1
2  is_profile_enter           41093         1.5668          0          1
3           is_like           32237         1.2292          0          1
4        is_comment            4068         0.1551          0          1
5           is_hate            2061         0.0786          0          1
6         is_follow            1853         0.0707          0          1
7        is_forward            1784         0.0680          0          1

In [12]:
# Verifying join coverage from events to dimension tables

user_join_coverage_rate = raw_interaction_log["user_id"].isin(user_dimension["user_id"]).mean()
video_basic_join_coverage_rate = raw_interaction_log["video_id"].isin(video_dimension_basic["video_id"]).mean()
video_statistic_join_coverage_rate = raw_interaction_log["video_id"].isin(video_dimension_statistic["video_id"]).mean()

join_coverage_summary = pd.DataFrame(
    {
        "dimension_table": ["user_dimension",
                            "video_dimension_basic",
                            "video_dimension_statistic"
        ],
        "join_coverage_rate_percent": [round(user_join_coverage_rate * 100, 4),
                                       round(video_basic_join_coverage_rate * 100, 4),
                                       round(video_statistic_join_coverage_rate * 100, 4)
        ]
    }
)

join_coverage_summary

             dimension_table  join_coverage_rate_percent
0             user_dimension                       100.0
1      video_dimension_basic                       100.0
2  video_dimension_statistic                       100.0

In [13]:
# Checking raw date, hour, play-time and duration ranges

date_time_summary = pd.DataFrame(
    {
        "metric_name": ["minimum_date", "maximum_date",
                        "minimum_hourmin", "maximum_hourmin",
                        "minimum_play_time_ms", "maximum_play_time_ms",
                        "minimum_duration_ms", "maximum_duration_ms"
        ],
        "value": [raw_interaction_log["date"].min(), raw_interaction_log["date"].max(),
                  raw_interaction_log["hourmin"].min(), raw_interaction_log["hourmin"].max(),
                  raw_interaction_log["play_time_ms"].min(), raw_interaction_log["play_time_ms"].max(),
                  raw_interaction_log["duration_ms"].min(), raw_interaction_log["duration_ms"].max()
        ]
    }
)

date_time_summary

            metric_name     value
0          minimum_date  20220409
1          maximum_date  20220508
2       minimum_hourmin         0
3       maximum_hourmin      2300
4  minimum_play_time_ms         0
5  maximum_play_time_ms   1023809
6   minimum_duration_ms         0
7   maximum_duration_ms   1177720

In [14]:
# Validating raw temporal field quality against parsed values

raw_event_date_parsed = pd.to_datetime(raw_interaction_log["date"].astype(str),
                                       format = "%Y%m%d",
                                       errors = "coerce"
)

raw_temporal_field_quality = pd.DataFrame(
    {
        "metric_name": ["minimum_raw_event_date", "maximum_raw_event_date",
                        "invalid_raw_event_date_count",
                        "minimum_raw_event_hour_bucket", "maximum_raw_event_hour_bucket",
                        "raw_event_hour_bucket_out_of_range_count", "raw_event_hour_bucket_not_hour_aligned_count",
                        "minimum_event_timestamp_utc", "maximum_event_timestamp_utc"
        ],
        "value": [int(raw_interaction_log["date"].min()), int(raw_interaction_log["date"].max()),
                  int(raw_event_date_parsed.isna().sum()), 
                  int(raw_interaction_log["hourmin"].min()), int(raw_interaction_log["hourmin"].max()),
                  int((~raw_interaction_log["hourmin"].between(0, 2300)).sum()),
                  int((raw_interaction_log["hourmin"] % 100 != 0).sum()),
                  pd.to_datetime(raw_interaction_log["time_ms"].min(), unit = "ms", utc = True),
                  pd.to_datetime(raw_interaction_log["time_ms"].max(), unit = "ms", utc = True)
        ]
    }
)

raw_temporal_field_quality

                                    metric_name                             value
0                        minimum_raw_event_date                          20220409
1                        maximum_raw_event_date                          20220508
2                  invalid_raw_event_date_count                                 0
3                 minimum_raw_event_hour_bucket                                 0
4                 maximum_raw_event_hour_bucket                              2300
5      raw_event_hour_bucket_out_of_range_count                                 0
6  raw_event_hour_bucket_not_hour_aligned_count                                 0
7                   minimum_event_timestamp_utc  2022-04-09 03:46:03.278000+00:00
8                   maximum_event_timestamp_utc  2022-05-08 15:52:10.564000+00:00

In [15]:
# Removing exact duplicate rows from the raw interaction table

interaction_log_exact_deduplicated = raw_interaction_log.loc[
    ~raw_interaction_log.duplicated()
].copy()

pd.DataFrame(
    {
        "metric_name": ["row_count_before_exact_deduplication",
                        "row_count_after_exact_deduplication",
                        "exact_duplicates_removed"
        ],
        "value": [int(len(raw_interaction_log)),
                  int(len(interaction_log_exact_deduplicated)),
                  int(len(raw_interaction_log) - len(interaction_log_exact_deduplicated))
        ]
    }
)

                            metric_name    value
0  row_count_before_exact_deduplication  2622668
1   row_count_after_exact_deduplication  2600671
2              exact_duplicates_removed    21997

In [16]:
# Isolating unresolved duplicate event-key groups after exact deduplication

duplicate_key_columns = ["user_id", "video_id", "time_ms"]

unresolved_duplicate_rows = interaction_log_exact_deduplicated.loc[
    interaction_log_exact_deduplicated.duplicated(subset = duplicate_key_columns, keep = False)
].copy()

remaining_duplicate_key_summary = pd.DataFrame(
    {
        "metric_name": ["rows_in_remaining_duplicate_groups", 
                        "remaining_duplicate_event_key_count"
        ],
        "value": [int(len(unresolved_duplicate_rows)),
                  int(unresolved_duplicate_rows[duplicate_key_columns]
                      .drop_duplicates()
                      .shape[0]
            )
        ]
    }
)

remaining_duplicate_key_summary

                           metric_name  value
0   rows_in_remaining_duplicate_groups   2972
1  remaining_duplicate_event_key_count   1486

In [17]:
# Separating temporal-only duplicate differences from true event conflicts

non_temporal_columns = ["is_click", "is_like", "is_follow", "is_comment", "is_forward", "is_hate",
                        "long_view", "play_time_ms", "duration_ms", "profile_stay_time", "comment_stay_time",
                        "is_profile_enter", "is_rand", "tab", "traffic_source"
]

unresolved_duplicate_key_profile = (unresolved_duplicate_rows
                                    .groupby(duplicate_key_columns, as_index = False)
                                    .agg(
                                        record_count = ("user_id", "size"),
                                        distinct_raw_date_count = ("date", "nunique"),
                                        distinct_raw_hourmin_count = ("hourmin", "nunique"),
                                        **{
                                            f"distinct_{column}_count": (column, "nunique")
                                            for column in non_temporal_columns
        }
    )
)

duplicate_conflict_profile = pd.DataFrame(
    {
        "metric_name": ["remaining_duplicate_key_count_after_exact_deduplication",
                        "duplicate_keys_with_raw_date_difference",
                        "duplicate_keys_with_raw_hourmin_difference",
                        "duplicate_keys_with_non_temporal_difference"
        ],
        "value": [int(len(unresolved_duplicate_key_profile)),
                  int((unresolved_duplicate_key_profile["distinct_raw_date_count"] > 1).sum()),
                  int((unresolved_duplicate_key_profile["distinct_raw_hourmin_count"] > 1).sum()),
                  int(
                        unresolved_duplicate_key_profile[
                            [f"distinct_{column}_count" for column in non_temporal_columns]
                        ].gt(1).any(axis = 1).sum()
            )
        ]
    }
)

duplicate_conflict_profile

                                         metric_name  value
0  remaining_duplicate_key_count_after_exact_dedu...   1486
1            duplicate_keys_with_raw_date_difference    110
2         duplicate_keys_with_raw_hourmin_difference   1461
3        duplicate_keys_with_non_temporal_difference     27

In [18]:
# Quantifying duplicate groups that remain analytically unsafe.

unresolved_duplicate_keys = unresolved_duplicate_key_profile.loc[
    unresolved_duplicate_key_profile[
        [f"distinct_{column}_count" for column in non_temporal_columns]
    ].gt(1).any(axis = 1),
    duplicate_key_columns
].copy()

duplicate_resolution_summary = pd.DataFrame(
    {
        "metric_name": ["remaining_duplicate_key_count_after_exact_deduplication",
                        "duplicate_keys_with_only_raw_date_or_hourmin_difference",
                        "duplicate_keys_with_non_temporal_conflicts"
        ],
        "value": [int(len(unresolved_duplicate_key_profile)),
                  int(len(unresolved_duplicate_key_profile) - len(unresolved_duplicate_keys)),
                  int(len(unresolved_duplicate_keys))
        ]
    }
)

duplicate_resolution_summary

                                         metric_name  value
0  remaining_duplicate_key_count_after_exact_dedu...   1486
1  duplicate_keys_with_only_raw_date_or_hourmin_d...   1459
2         duplicate_keys_with_non_temporal_conflicts     27

In [19]:
# Testing whether temporal-only duplicates align under plausible UTC offsets

temporal_only_duplicate_keys = unresolved_duplicate_key_profile.loc[
    ~unresolved_duplicate_key_profile[
        [f"distinct_{column}_count" for column in non_temporal_columns]
    ].gt(1).any(axis = 1),
    duplicate_key_columns
].copy()

temporal_only_duplicate_rows = (interaction_log_exact_deduplicated
                                .merge(temporal_only_duplicate_keys, on = duplicate_key_columns, how = "inner")
                                .copy()
)

temporal_only_duplicate_rows["timestamp_utc"] = pd.to_datetime(temporal_only_duplicate_rows["time_ms"],
                                                               unit = "ms",
                                                               utc = True
)

temporal_only_duplicate_rows["raw_event_date"] = pd.to_datetime(temporal_only_duplicate_rows["date"].astype(str),
                                                                format = "%Y%m%d",
                                                                errors = "coerce"
)

temporal_only_duplicate_rows["raw_event_hour"] = (
    temporal_only_duplicate_rows["hourmin"] // 100
).astype("int16")

temporal_alignment_rows = []


# Comparing raw date and hour fields against shifted event timestamps
for utc_offset_hours in range(-12, 15):
    shifted_timestamp = (
        temporal_only_duplicate_rows["timestamp_utc"] + pd.to_timedelta(utc_offset_hours, unit = "h")
    )

    derived_event_date = pd.to_datetime(shifted_timestamp.dt.date)
    derived_event_hour = shifted_timestamp.dt.hour

    temporal_alignment_rows.append(
        {
            "utc_offset_hours": utc_offset_hours,
            "date_match_rate_percent": round(
                (derived_event_date == temporal_only_duplicate_rows["raw_event_date"]).mean() * 100,
                4
            ),
            "hour_match_rate_percent": round(
                (derived_event_hour == temporal_only_duplicate_rows["raw_event_hour"]).mean() * 100,
                4
            ),
            "date_and_hour_match_rate_percent": round(
                (
                    (derived_event_date == temporal_only_duplicate_rows["raw_event_date"])
                    & (derived_event_hour == temporal_only_duplicate_rows["raw_event_hour"])
                ).mean() * 100,
                4
            )
        }
    )

temporal_alignment_summary = (
    pd.DataFrame(temporal_alignment_rows)
    .sort_values(
        [
            "date_and_hour_match_rate_percent",
            "date_match_rate_percent",
            "hour_match_rate_percent"
        ],
        ascending = False
    )
    .reset_index(drop = True)
)

temporal_duplicate_conflict_shape = (
    temporal_only_duplicate_rows
    .groupby(duplicate_key_columns, as_index = False)
    .agg(
        raw_date_count = ("date", "nunique"),
        raw_hourmin_count = ("hourmin", "nunique")
    )
)

temporal_duplicate_validation_summary = pd.DataFrame(
    {
        "metric_name": ["temporal_only_duplicate_event_key_count",
                        "temporal_only_duplicate_row_count",
                        "keys_with_date_difference",
                        "keys_with_hourmin_difference",
                        "keys_with_both_date_and_hourmin_difference"
        ],
        "value": [int(len(temporal_only_duplicate_keys)),
                  int(len(temporal_only_duplicate_rows)),
                  int((temporal_duplicate_conflict_shape["raw_date_count"] > 1).sum()),
                  int((temporal_duplicate_conflict_shape["raw_hourmin_count"] > 1).sum()),
                  int(
                        (
                            (temporal_duplicate_conflict_shape["raw_date_count"] > 1)
                            & (temporal_duplicate_conflict_shape["raw_hourmin_count"] > 1)
                        ).sum()
                )
        ]
    }
)

display(temporal_duplicate_validation_summary)
display(temporal_alignment_summary.head(10))

                                  metric_name  value
0     temporal_only_duplicate_event_key_count   1459
1           temporal_only_duplicate_row_count   2918
2                   keys_with_date_difference    110
3                keys_with_hourmin_difference   1459
4  keys_with_both_date_and_hourmin_difference    110

   utc_offset_hours  date_match_rate_percent  hour_match_rate_percent  date_and_hour_match_rate_percent
0                 8                  96.2303                  49.8972                           49.8972
1                 9                  96.2303                  49.7944                           49.7944
2                10                  84.5099                   0.3084                            0.3084
3                 7                  93.0775                   0.0000                            0.0000
4                 6                  91.5010                   0.0000                            0.0000
5                 5                  90.1302                   0.0000                            0.0000
6                 4                  89.3763                   0.0000                            0.0000
7                 3                  88.6223                   0.0000                            0.0000
8                 2                  86.7718                   0.0000                            0.0000
9                 1                  84.0987                   0.0000                            0.0000

In [20]:
# Comparing duplicate handling options before final event cleaning

strict_exclusion_key_count = int(len(unresolved_duplicate_key_profile))
strict_exclusion_row_count = int(len(unresolved_duplicate_rows))

targeted_conflict_key_count = int(len(unresolved_duplicate_keys))
targeted_conflict_row_count = int(interaction_log_exact_deduplicated
                                  .merge(unresolved_duplicate_keys, on = duplicate_key_columns, how = "inner")
                                  .shape[0]
)

duplicate_strategy = pd.DataFrame(
    {
        "approach": ["strict_exclusion_of_all_unresolved_duplicate_event_keys",
                     "exclude_only_non_temporal_conflicts_and_keep_one_row_for_temporal_only_duplicates"
        ],
        "excluded_event_key_count": [strict_exclusion_key_count,
                                     targeted_conflict_key_count
        ],
        "excluded_row_count": [strict_exclusion_row_count,
                               targeted_conflict_row_count
        ],
        "retained_row_count": [int(len(interaction_log_exact_deduplicated) - strict_exclusion_row_count),
                               int(len(interaction_log_exact_deduplicated) - targeted_conflict_row_count)
        ]
    }
)

duplicate_strategy["excluded_row_rate_percent"] = (
    duplicate_strategy["excluded_row_count"] / len(interaction_log_exact_deduplicated) * 100
).round(4)

duplicate_strategy

                                            approach  excluded_event_key_count  excluded_row_count  retained_row_count  excluded_row_rate_percent
0  strict_exclusion_of_all_unresolved_duplicate_e...                      1486                2972             2597699                     0.1143
1  exclude_only_non_temporal_conflicts_and_keep_o...                        27                  54             2600617                     0.0021

In [21]:
# Finalizing the clean interaction event base with conservative exclusions
interaction_events = (interaction_log_exact_deduplicated
                      .merge(unresolved_duplicate_key_profile[duplicate_key_columns].assign(exclude_from_analysis = 1),
                             on = duplicate_key_columns,
                             how = "left"
    )
)

interaction_events = (interaction_events.loc[interaction_events["exclude_from_analysis"].isna()]
                      .drop(columns = ["exclude_from_analysis"])
                      .copy()
)

interaction_events["event_timestamp_utc"] = pd.to_datetime(interaction_events["time_ms"],
                                                           unit = "ms",
                                                           utc = True
)

interaction_events["event_date"] = pd.to_datetime(interaction_events["date"].astype(str),
                                                  format = "%Y%m%d",
                                                  errors = "coerce"
)

interaction_events["event_date_key"] = interaction_events["date"].astype("int32")
interaction_events["event_hour_bucket"] = interaction_events["hourmin"].astype("int32")

interaction_events = (interaction_events
                      .sort_values(["event_date", "event_timestamp_utc", "user_id", "video_id", "date", "hourmin"])
                      .reset_index(drop = True)
)

pd.DataFrame(
    {
        "metric_name": ["row_count_after_exact_deduplication",
                        "excluded_temporal_only_duplicate_event_key_count",
                        "excluded_conflicting_duplicate_event_key_count",
                        "excluded_unresolved_duplicate_row_count",
                        "clean_interaction_row_count",
                        "remaining_duplicate_event_key_count"
        ],
        "value": [int(len(interaction_log_exact_deduplicated)),
                  int(len(temporal_only_duplicate_keys)),
                  int(len(unresolved_duplicate_keys)),
                  int(len(unresolved_duplicate_rows)),
                  int(len(interaction_events)),
                  int(interaction_events.duplicated(subset = duplicate_key_columns).sum())
        ]
    }
)

                                        metric_name    value
0               row_count_after_exact_deduplication  2600671
1  excluded_temporal_only_duplicate_event_key_count     1459
2    excluded_conflicting_duplicate_event_key_count       27
3           excluded_unresolved_duplicate_row_count     2972
4                       clean_interaction_row_count  2597699
5               remaining_duplicate_event_key_count        0

In [22]:
# Creating quality flags and core derived engagement outcomes

interaction_events["has_zero_duration"] = interaction_events["duration_ms"].eq(0).astype("int8")
interaction_events["has_zero_play_time"] = interaction_events["play_time_ms"].eq(0).astype("int8")
interaction_events["has_play_time_exceeding_duration"] = (
    interaction_events["play_time_ms"] > interaction_events["duration_ms"]
).astype("int8")

interaction_events["meaningful_watch"] = interaction_events["long_view"].astype("int8")

interaction_events["high_value_engagement"] = (interaction_events["is_follow"].eq(1) 
                                               | interaction_events["is_comment"].eq(1)
                                               | interaction_events["is_forward"].eq(1)
).astype("int8")

In [23]:
# Recasting the event date field into final analytical format

interaction_events["event_date"] = pd.to_datetime(interaction_events["event_date_key"].astype(str),
                                                  format = "%Y%m%d",
                                                  errors = "coerce"
)

In [24]:
# Narrowing the clean event base to the required analytical fields

interaction_events_clean = interaction_events[["user_id", "video_id", 
                                               "time_ms", "event_timestamp_utc", "event_date_key", "event_date", "event_hour_bucket",
                                               "traffic_source", "is_rand", "tab", "is_click", "meaningful_watch", "is_like",
                                               "is_follow", "is_comment", "is_forward", "is_hate", "is_profile_enter",
                                               "play_time_ms", "duration_ms", "profile_stay_time", "comment_stay_time",
                                               "has_zero_duration", "has_zero_play_time", "has_play_time_exceeding_duration",
                                               "high_value_engagement"
    ]
].copy()

interaction_events_clean = (interaction_events_clean
                            .sort_values(["event_date", "event_timestamp_utc", "user_id", "video_id"])
                            .reset_index(drop = True)
)

In [25]:
# Checking whether downstream actions appear without click events

event_dependency_summary = pd.DataFrame(
    {
        "metric_name": ["meaningful_watch_without_click_count",
                        "profile_enter_without_click_count",
                        "like_without_click_count",
                        "follow_without_click_count",
                        "comment_without_click_count",
                        "forward_without_click_count",
                        "high_value_engagement_without_click_count"
        ],
        "value": [int(((interaction_events_clean["meaningful_watch"] == 1) & (interaction_events_clean["is_click"] == 0)).sum()),
                  int(((interaction_events_clean["is_profile_enter"] == 1) & (interaction_events_clean["is_click"] == 0)).sum()),
                  int(((interaction_events_clean["is_like"] == 1) & (interaction_events_clean["is_click"] == 0)).sum()),
                  int(((interaction_events_clean["is_follow"] == 1) & (interaction_events_clean["is_click"] == 0)).sum()),
                  int(((interaction_events_clean["is_comment"] == 1) & (interaction_events_clean["is_click"] == 0)).sum()),
                  int(((interaction_events_clean["is_forward"] == 1) & (interaction_events_clean["is_click"] == 0)).sum()),
                  int(((interaction_events_clean["high_value_engagement"] == 1) & (interaction_events_clean["is_click"] == 0)).sum())
        ]
    }
)

event_dependency_summary["rate_percent"] = (
    event_dependency_summary["value"] / len(interaction_events_clean) * 100
).round(4)

event_dependency_summary

                                 metric_name  value  rate_percent
0       meaningful_watch_without_click_count   2283        0.0879
1          profile_enter_without_click_count   4208        0.1620
2                   like_without_click_count   6275        0.2416
3                 follow_without_click_count    247        0.0095
4                comment_without_click_count    115        0.0044
5                forward_without_click_count    272        0.0105
6  high_value_engagement_without_click_count    633        0.0244

In [26]:
# Comparing key engagement rates across traffic sources

event_rate_by_traffic_source = (interaction_events_clean
                                .groupby("traffic_source", as_index = False)
                                .agg(
                                    row_count = ("user_id", "size"),
                                    click_rate_percent = ("is_click", lambda s: round(s.mean() * 100, 4)),
                                    meaningful_watch_rate_percent = ("meaningful_watch", lambda s: round(s.mean() * 100, 4)),
                                    like_rate_percent = ("is_like", lambda s: round(s.mean() * 100, 4)),
                                    follow_rate_percent = ("is_follow", lambda s: round(s.mean() * 100, 4)),
                                    comment_rate_percent = ("is_comment", lambda s: round(s.mean() * 100, 4)),
                                    forward_rate_percent = ("is_forward", lambda s: round(s.mean() * 100, 4)),
                                    high_value_engagement_rate_percent = ("high_value_engagement", lambda s: round(s.mean() * 100, 4))
    )
)

event_rate_by_traffic_source

,traffic_source,row_count,click_rate_percent,meaningful_watch_rate_percent,like_rate_percent,follow_rate_percent,comment_rate_percent,forward_rate_percent,high_value_engagement_rate_percent
0,random,1186049,17.616,8.4962,0.4798,0.0261,0.0347,0.0339,0.0942
1,standard,1411650,46.456,33.6059,1.8665,0.1070,0.2571,0.0973,0.4575

In [27]:
# Comparing playback-quality exceptions across traffic sources

playback_quality_by_traffic_source = (interaction_events_clean
                                      .groupby("traffic_source", as_index = False)
                                      .agg(
                                          row_count = ("user_id", "size"),
                                          zero_duration_rate_percent = ("has_zero_duration", lambda s: round(s.mean() * 100, 4)),
                                          zero_play_time_rate_percent = ("has_zero_play_time", lambda s: round(s.mean() * 100, 4)),
                                          play_time_exceeds_duration_rate_percent = ("has_play_time_exceeding_duration", lambda s: round(s.mean() * 100, 4))
    )
)

playback_quality_by_traffic_source

  traffic_source  row_count  zero_duration_rate_percent  zero_play_time_rate_percent  play_time_exceeds_duration_rate_percent
0         random    1186049                      3.1129                       0.6672                                   6.3101
1       standard    1411650                      2.0443                      13.3686                                  16.8289

In [28]:
# Reviewing basic video fields for completeness and analytical value

video_basic_field_review = pd.DataFrame(
    {
        "column_name": video_dimension_basic.columns,
        "missing_count": video_dimension_basic.isna().sum().values,
        "missing_rate_percent": (video_dimension_basic.isna().mean().values * 100).round(4),
        "distinct_value_count": [video_dimension_basic[column].nunique(dropna = False) for column in video_dimension_basic.columns],
        "sample_value": [video_dimension_basic[column].dropna().iloc[0]
                         if video_dimension_basic[column].notna().any()
                         else np.nan
                         for column in video_dimension_basic.columns
        ]
    }
).sort_values(["missing_rate_percent", "column_name"], ascending = [False, True]).reset_index(drop = True)

video_basic_field_review

       column_name  missing_count  missing_rate_percent  distinct_value_count sample_value
0   video_duration            239                3.1518                  5757      87433.0
1       music_type            203                2.6770                     6          9.0
2              tag             96                1.2660                   111           39
3        author_id              0                0.0000                  6510      7349781
4         music_id              0                0.0000                  7202   9155697141
5    server_height              0                0.0000                   120       1280.0
6     server_width              0                0.0000                   156        720.0
7        upload_dt              0                0.0000                     3   2022-04-10
8      upload_type              0                0.0000                    14   LongImport
9         video_id              0                0.0000                  7583            0
10      video_type              0                0.0000                     3       NORMAL
11  visible_status              0                0.0000                     1          0.0

In [29]:
# Reviewing user fields for completeness and segment usefulness

user_field_review = pd.DataFrame(
    {
        "column_name": user_dimension.columns,
        "missing_count": user_dimension.isna().sum().values,
        "missing_rate_percent": (user_dimension.isna().mean().values * 100).round(4),
        "distinct_value_count": [user_dimension[column].nunique(dropna = False) for column in user_dimension.columns],
        "sample_value": [user_dimension[column].dropna().iloc[0]
                         if user_dimension[column].notna().any()
                         else np.nan
                         for column in user_dimension.columns
        ]
    }
).sort_values(["missing_rate_percent", "column_name"], ascending = [False, True]).reset_index(drop = True)

user_field_review

              column_name  missing_count  missing_rate_percent  distinct_value_count sample_value
0            onehot_feat4            874                3.2032                    16          1.0
1           onehot_feat12            714                2.6168                     3          0.0
2           onehot_feat13            714                2.6168                     3          1.0
3           onehot_feat14            714                2.6168                     3          0.0
4           onehot_feat15            714                2.6168                     3          0.0
5           onehot_feat16            714                2.6168                     3          0.0
6           onehot_feat17            714                2.6168                     3          0.0
7           fans_user_num              0                0.0000                  2210          150
8     fans_user_num_range              0                0.0000                     9     [100,1k)
9         follow_user_num              0                0.0000                  2562          514
10  follow_user_num_range              0                0.0000                     8         500+
11        friend_user_num              0                0.0000                  1391           34
12  friend_user_num_range              0                0.0000                     7      [30,60)
13       is_live_streamer              0                0.0000                     2            1
14    is_lowactive_period              0                0.0000                     1            0
15        is_video_author              0                0.0000                     2            1
16           onehot_feat0              0                0.0000                     2            1
17           onehot_feat1              0                0.0000                     7            1
18          onehot_feat10              0                0.0000                     5            3
19          onehot_feat11              0                0.0000                     5            0
20           onehot_feat2              0                0.0000                    50           29
21           onehot_feat3              0                0.0000                  1471          949
22           onehot_feat5              0                0.0000                    34            0
23           onehot_feat6              0                0.0000                     3            0
24           onehot_feat7              0                0.0000                   118           14
25           onehot_feat8              0                0.0000                   454          135
26           onehot_feat9              0                0.0000                     7            6
27          register_days              0                0.0000                  2813          799
28    register_days_range              0                0.0000                     8         730+
29     user_active_degree              0                0.0000                     9  full_active
30                user_id              0                0.0000                 27285            0

In [30]:
# Reviewing aggregate video statistics before deciding whether to exclude them

video_statistic_field_review = pd.DataFrame(
    {
        "column_name": video_dimension_statistic.columns,
        "missing_count": video_dimension_statistic.isna().sum().values,
        "missing_rate_percent": (video_dimension_statistic.isna().mean().values * 100).round(4),
        "distinct_value_count": [video_dimension_statistic[column].nunique(dropna = False)
                                 for column in video_dimension_statistic.columns
        ],
        "sample_value": [video_dimension_statistic[column].dropna().iloc[0]
                         if video_dimension_statistic[column].notna().any()
                         else np.nan
                         for column in video_dimension_statistic.columns
        ]
    }
).sort_values(["missing_rate_percent", "column_name"], ascending = [False, True]).reset_index(drop = True)

video_statistic_field_review

                 column_name  missing_count  missing_rate_percent  distinct_value_count  sample_value
0         cancel_collect_cnt              0                   0.0                  6680  2.352941e-01
1    cancel_collect_user_num              0                   0.0                  6599  2.352941e-01
2          cancel_follow_cnt              0                   0.0                  5999  5.196078e-01
3     cancel_follow_user_num              0                   0.0                  5968  5.098039e-01
4            cancel_like_cnt              0                   0.0                  7136  6.960784e-01
5       cancel_like_user_num              0                   0.0                  7107  6.568627e-01
6             click_like_cnt              0                   0.0                  7488  2.921569e+00
7                collect_cnt              0                   0.0                  7290  9.019608e-01
8           collect_user_num              0                   0.0                  7274  8.823529e-01
9                comment_cnt              0                   0.0                  6906  1.960784e-01
10          comment_like_cnt              0                   0.0                  6867  3.921569e-02
11     comment_like_user_num              0                   0.0                  6592  3.921569e-02
12     comment_stay_duration              0                   0.0                  7583  2.034282e+05
13          comment_user_num              0                   0.0                  6834  1.960784e-01
14         complete_play_cnt              0                   0.0                  7573  1.952549e+02
15    complete_play_user_num              0                   0.0                  7572  1.830980e+02
16                    counts              0                   0.0                   125  1.020000e+02
17        delete_comment_cnt              0                   0.0                  3635  1.960784e-02
18   delete_comment_user_num              0                   0.0                  3448  1.960784e-02
19        direct_comment_cnt              0                   0.0                  6772  1.568627e-01
20   direct_comment_user_num              0                   0.0                  6771  1.568627e-01
21          double_click_cnt              0                   0.0                  7477  3.519608e+00
22              download_cnt              0                   0.0                  5346  1.960784e-02
23         download_user_num              0                   0.0                  5314  1.960784e-02
24                follow_cnt              0                   0.0                  7117  8.431373e-01
25           follow_user_num              0                   0.0                  7076  8.235294e-01
26                  like_cnt              0                   0.0                  7525  6.470588e+00
27             like_user_num              0                   0.0                  7545  6.392157e+00
28        long_time_play_cnt              0                   0.0                  7582  3.189706e+02
29   long_time_play_user_num              0                   0.0                  7578  2.993333e+02
30     outsite_share_all_cnt              0                   0.0                  6270  7.843137e-02
31                  play_cnt              0                   0.0                  7580  8.168824e+02
32             play_duration              0                   0.0                  7583  2.767915e+07
33             play_progress              0                   0.0                  7583  1.174067e-01
34             play_user_num              0                   0.0                  7583  7.131765e+02
35        reduce_similar_cnt              0                   0.0                  6802  9.607843e-01
36   reduce_similar_user_num              0                   0.0                  6761  9.117647e-01
37         reply_comment_cnt              0                   0.0                  5526  3.921569e-02
38    reply_comment_user_num              0                   0.0                  5192  3.921569e-02
39                report_cnt              0                   0.0                   406  0.000000e+00
40           report_user_num              0                   0.0                   364  0.000000e+00
41             share_all_cnt              0                   0.0                  6650  1.176471e-01
42        share_all_user_num              0                   0.0                  6557  1.078431e-01
43                 share_cnt              0                   0.0                  6064  5.882353e-02
44            share_user_num              0                   0.0                  5983  5.882353e-02
45       short_time_play_cnt              0                   0.0                  7582  2.270980e+02
46  short_time_play_user_num              0                   0.0                  7581  2.063725e+02
47                  show_cnt              0                   0.0                  7583  2.579686e+03
48             show_user_num              0                   0.0                  7583  2.308324e+03
49            valid_play_cnt              0                   0.0                  7581  4.430196e+02
50       valid_play_user_num              0                   0.0                  7578  4.144314e+02
51                  video_id              0                   0.0                  7583  0.000000e+00

In [31]:
# Renaming and narrowing the cleaned event table for impression-level analysis

impression_events = (
    interaction_events_clean
    .rename(
        columns = {
            "time_ms": "event_timestamp_ms",
            "tab": "feed_tab_id",
            "meaningful_watch": "is_meaningful_watch",
            "high_value_engagement": "is_high_value_engagement"
        }
    )
    .drop(columns = ["is_rand"])
    .copy()
)

impression_events = impression_events[
    [
        "user_id", "video_id", "event_timestamp_ms", "event_timestamp_utc", "event_date_key", "event_date", "event_hour_bucket",
        "traffic_source", "feed_tab_id",
        "is_click", "is_meaningful_watch", "is_high_value_engagement", "is_like", "is_follow", "is_comment", "is_forward", "is_hate",
        "is_profile_enter", "play_time_ms", "duration_ms", "profile_stay_time", "comment_stay_time",
        "has_zero_duration", "has_zero_play_time", "has_play_time_exceeding_duration"
    ]
].copy()

In [32]:
# Joining selected user and video attributes to the impression base for business analysis

user_columns = ["user_id", "user_active_degree", "is_video_author", 
                "follow_user_num", "follow_user_num_range", "fans_user_num", "fans_user_num_range",
                "friend_user_num", "friend_user_num_range", "register_days", "register_days_range"
]

video_columns = ["video_id", "author_id", "video_type", "upload_dt", "upload_type", "video_duration",
                 "server_width", "server_height", "music_id", "music_type", "tag"
]

# Standardizing the user attributes for consistent downstream grouping
user_attributes = user_dimension[user_columns].copy()

for column_name in ["user_active_degree", "follow_user_num_range", "fans_user_num_range",
                    "friend_user_num_range", "register_days_range"
]:
    user_attributes[column_name] = (user_attributes[column_name]
                                    .astype("string")
                                    .str.strip()
                                    .replace({"": pd.NA})
    )

# Standardizing the video attributes for business-ready field names
video_attributes = (video_dimension_basic[video_columns]
                    .rename(
                        columns = {"author_id": "creator_user_id",
                                   "upload_dt": "video_upload_date",
                                   "upload_type": "video_upload_type",
                                   "video_duration": "video_duration_ms",
                                   "server_width": "video_width",
                                   "server_height": "video_height",
                                   "tag": "video_tag"
        }
    )
    .copy()
)

video_attributes["video_upload_date"] = pd.to_datetime(video_attributes["video_upload_date"],
                                                       errors = "coerce"
)

for column_name in ["video_type", "video_upload_type", "video_tag"]:
    video_attributes[column_name] = (video_attributes[column_name]
                                     .astype("string")
                                     .str.strip()
                                     .replace({"": pd.NA})
    )

# Building the main impression fact table at the analytical grain
impression_fact = (impression_events
                   .merge(user_attributes, on = "user_id", how = "left")
                   .merge(video_attributes, on = "video_id", how = "left")
                   .rename(columns = {"duration_ms": "event_content_duration_ms"})
                   .copy()
)


# Deriving reporting fields that are usable for segmentation and interpretation
impression_fact["event_hour_of_day"] = (
    impression_fact["event_hour_bucket"] // 100
).astype("int8")

impression_fact["event_weekday_name"] = (
    impression_fact["event_date"]
    .dt.day_name()
    .astype("string")
)

impression_fact["is_weekend"] = (
    impression_fact["event_date"]
    .dt.dayofweek
    .isin([5, 6])
    .astype("int8")
)

impression_fact["video_age_days"] = (
    impression_fact["event_date"] - impression_fact["video_upload_date"]
).dt.days

impression_fact["video_orientation"] = np.select(
    [
        impression_fact["video_height"] > impression_fact["video_width"],
        impression_fact["video_width"] > impression_fact["video_height"],
        impression_fact["video_width"] == impression_fact["video_height"]
    ],
    ["vertical", "horizontal", "square"],
    default = "unknown"
)

impression_fact["playback_completion_rate"] = np.where(
    impression_fact["event_content_duration_ms"] > 0,
    impression_fact["play_time_ms"] / impression_fact["event_content_duration_ms"],
    np.nan
)

impression_fact["playback_completion_rate_capped"] = (
    impression_fact["playback_completion_rate"]
    .clip(lower = 0, upper = 1)
)

impression_fact["is_social_engagement"] = (
    impression_fact[["is_like", "is_follow", "is_comment", "is_forward"]]
    .max(axis = 1)
    .astype("int8")
)

impression_fact = (
    impression_fact[
        [
            "user_id", "video_id",
            "event_timestamp_ms", "event_timestamp_utc", "event_date_key", "event_date",
            "event_hour_bucket", "event_hour_of_day", "event_weekday_name", "is_weekend", "traffic_source", "feed_tab_id",
            "is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", "is_like", "is_follow", "is_comment",
            "is_forward", "is_hate", "is_profile_enter", "play_time_ms", "event_content_duration_ms", "video_duration_ms", 
            "playback_completion_rate", "playback_completion_rate_capped", "profile_stay_time", "comment_stay_time",
            "has_zero_duration", "has_zero_play_time", "has_play_time_exceeding_duration",
            "user_active_degree", "is_video_author", "follow_user_num", "follow_user_num_range",
            "fans_user_num", "fans_user_num_range", "friend_user_num", "friend_user_num_range", "register_days",
            "register_days_range", "creator_user_id", "video_type", "video_upload_date", "video_upload_type", "video_width",
            "video_height", "video_orientation", "music_id", "music_type", "video_tag", "video_age_days"
        ]
    ]
    .sort_values(["event_date", "event_timestamp_ms", "user_id", "video_id"])
    .reset_index(drop = True)
)

print(impression_fact.shape)
impression_fact.head()

(2597699, 53)

,user_id,video_id,event_timestamp_ms,event_timestamp_utc,event_date_key,event_date,event_hour_bucket,event_hour_of_day,event_weekday_name,is_weekend,traffic_source,feed_tab_id,is_click,is_meaningful_watch,is_social_engagement,is_high_value_engagement,is_like,is_follow,is_comment,is_forward,is_hate,is_profile_enter,play_time_ms,event_content_duration_ms,video_duration_ms,playback_completion_rate,playback_completion_rate_capped,profile_stay_time,comment_stay_time,has_zero_duration,has_zero_play_time,has_play_time_exceeding_duration,user_active_degree,is_video_author,follow_user_num,follow_user_num_range,fans_user_num,fans_user_num_range,friend_user_num,friend_user_num_range,register_days,register_days_range,creator_user_id,video_type,video_upload_date,video_upload_type,video_width,video_height,video_orientation,music_id,music_type,video_tag,video_age_days
0,20853,222,1649475963278,2022-04-09 03:46:03.278000+00:00,20220409,2022-04-09,1200,12,Saturday,1,standard,1,0,0,0,0,0,0,0,0,0,0,1286,289866,289866.0,0.004437,0.004437,0,0,0,0,0,full_active,1,78,"(50,100]",66,"[10,100)",0,0,2479,730+,6705448,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,9138394916,9.0,3,0
1,8286,222,1649476012164,2022-04-09 03:46:52.164000+00:00,20220409,2022-04-09,1200,12,Saturday,1,standard,1,0,0,0,0,0,0,0,0,0,0,1857,289866,289866.0,0.006406,0.006406,0,0,0,0,0,2_14_day_new,1,64,"(50,100]",47,"[10,100)",36,"[30,60)",1420,730+,6705448,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,9138394916,9.0,3,0
2,7406,222,1649476421916,2022-04-09 03:53:41.916000+00:00,20220409,2022-04-09,1200,12,Saturday,1,standard,4,1,1,0,0,0,0,0,0,0,1,25750,289866,289866.0,0.088834,0.088834,0,0,0,0,0,full_active,1,32,"(10,50]",53,"[10,100)",32,"[30,60)",102,91-180,6705448,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,9138394916,9.0,3,0
3,25934,6580,1649476523839,2022-04-09 03:55:23.839000+00:00,20220409,2022-04-09,1200,12,Saturday,1,standard,0,0,0,0,0,0,0,0,0,0,0,0,55960,55960.0,0.000000,0.000000,0,0,0,1,0,full_active,0,78,"(50,100]",0,0,0,0,89,61-90,4854468,NORMAL,2022-04-09,LongImport,720.0,1280.0,vertical,9138293546,9.0,"12,60",0
4,2073,4566,1649476630340,2022-04-09 03:57:10.340000+00:00,20220409,2022-04-09,1200,12,Saturday,1,standard,2,0,1,0,0,0,0,0,0,0,0,14904,14700,14700.0,1.013878,1.000000,0,1641,0,0,1,high_active,1,153,"(150,250]",11,"[10,100)",1,"[1,5)",1711,730+,5597283,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,5128196645,4.0,20,0

In [33]:
# Rebuilding the final video attribute view for later tag and content analysis

video_attributes = (
    video_dimension_basic[
        [
            "video_id", "author_id", "video_type", "upload_dt", "upload_type",
            "video_duration", "server_width", "server_height", "music_id", "music_type", "tag"
        ]
    ]
    .rename(
        columns = {"author_id": "creator_user_id",
                   "upload_dt": "video_upload_date",
                   "upload_type": "video_upload_type",
                   "video_duration": "video_duration_ms",
                   "server_width": "video_width",
                   "server_height": "video_height",
                   "tag": "video_tag"
        }
    )
    .copy()
)

video_attributes["video_upload_date"] = pd.to_datetime(
    video_attributes["video_upload_date"],
    errors = "coerce"
)

video_attributes["video_tag"] = (
    video_attributes["video_tag"]
    .astype("string")
    .str.strip()
    .replace({"": pd.NA})
)

In [34]:
# Checking how well raw event dates align with the timestamp field

event_date_reference = impression_fact["event_date"]
event_hour_reference = impression_fact["event_hour_bucket"].floordiv(100)

alignment_rows = []

for utc_offset_hours in range(-12, 15):
    shifted_timestamp = (
        impression_fact["event_timestamp_utc"] + pd.to_timedelta(utc_offset_hours, unit = "h")
    )

    same_date = shifted_timestamp.dt.date == event_date_reference.dt.date
    same_hour = shifted_timestamp.dt.hour == event_hour_reference

    alignment_rows.append(
        {
            "utc_offset_hours": utc_offset_hours,
            "event_date_match_rate_percent": round(same_date.mean() * 100, 4),
            "event_hour_match_rate_percent": round(same_hour.mean() * 100, 4),
            "event_date_and_hour_match_rate_percent": round((same_date & same_hour).mean() * 100, 4)
        }
    )

timestamp_alignment_summary = (
    pd.DataFrame(alignment_rows)
    .sort_values(
        [
            "event_date_and_hour_match_rate_percent",
            "event_date_match_rate_percent",
            "event_hour_match_rate_percent"
        ],
        ascending = False
    )
    .reset_index(drop = True)
)

timestamp_alignment_by_traffic_source = []

for traffic_source, source_frame in impression_fact.groupby("traffic_source"):
    source_event_date_reference = source_frame["event_date"]
    source_event_hour_reference = source_frame["event_hour_bucket"].floordiv(100)

    for utc_offset_hours in range(-12, 15):
        shifted_timestamp = (
            source_frame["event_timestamp_utc"] + pd.to_timedelta(utc_offset_hours, unit = "h")
        )

        same_date = shifted_timestamp.dt.date == source_event_date_reference.dt.date
        same_hour = shifted_timestamp.dt.hour == source_event_hour_reference

        timestamp_alignment_by_traffic_source.append(
            {
                "traffic_source": traffic_source,
                "utc_offset_hours": utc_offset_hours,
                "event_date_match_rate_percent": round(same_date.mean() * 100, 4),
                "event_hour_match_rate_percent": round(same_hour.mean() * 100, 4),
                "event_date_and_hour_match_rate_percent": round((same_date & same_hour).mean() * 100, 4)
            }
        )

timestamp_alignment_by_traffic_source = (
    pd.DataFrame(timestamp_alignment_by_traffic_source)
    .sort_values(
        ["traffic_source", "event_date_and_hour_match_rate_percent"],
        ascending = [True, False]
    )
    .groupby("traffic_source", as_index = False)
    .head(5)
    .reset_index(drop = True)
)

display(timestamp_alignment_summary.head(10))
display(timestamp_alignment_by_traffic_source)

   utc_offset_hours  event_date_match_rate_percent  event_hour_match_rate_percent  event_date_and_hour_match_rate_percent
0                 8                        99.2199                        82.6684                                 82.6684
1                 9                        95.4601                        17.3201                                 17.3201
2                10                        88.5976                         0.0107                                  0.0107
3                11                        81.5587                         0.0008                                  0.0008
4                 7                        95.9592                         0.0000                                  0.0000
5                 6                        93.9913                         0.0000                                  0.0000
6                 5                        92.7199                         0.0000                                  0.0000
7                 4                        91.8476                         0.0000                                  0.0000
8                 3                        91.0904                         0.0000                                  0.0000
9                 2                        90.0086                         0.0000                                  0.0000

  traffic_source  utc_offset_hours  event_date_match_rate_percent  event_hour_match_rate_percent  event_date_and_hour_match_rate_percent
0         random                 8                        99.2727                        83.0680                                 83.0680
1         random                 9                        95.7302                        16.9281                                 16.9281
2         random                10                        89.3626                         0.0026                                  0.0026
3         random                11                        82.9107                         0.0013                                  0.0013
4         random               -12                        23.4322                         0.0000                                  0.0000
5       standard                 8                        99.1755                        82.3327                                 82.3327
6       standard                 9                        95.2332                        17.6493                                 17.6493
7       standard                10                        87.9549                         0.0175                                  0.0175
8       standard                11                        80.4228                         0.0004                                  0.0004
9       standard               -12                        26.3259                         0.0000                                  0.0000

In [35]:
# Profiling playback anomalies to understand watch-quality edge cases

playback_exception_summary = (
    impression_fact
    .assign(
        click_status = np.where(impression_fact["is_click"].eq(1), "clicked", "not_clicked")
    )
    .groupby(["traffic_source", "click_status"], as_index = False)
    .agg(
        impression_count = ("user_id", "size"),
        zero_duration_count = ("has_zero_duration", "sum"),
        zero_play_time_count = ("has_zero_play_time", "sum"),
        play_time_exceeds_duration_count = ("has_play_time_exceeding_duration", "sum"),
        median_play_time_ms = ("play_time_ms", "median"),
        median_event_content_duration_ms = ("event_content_duration_ms", "median"),
        median_playback_completion_rate = ("playback_completion_rate_capped", "median")
    )
)

playback_exception_summary["zero_duration_rate_percent"] = (
    playback_exception_summary["zero_duration_count"] / playback_exception_summary["impression_count"] * 100
).round(4)

playback_exception_summary["zero_play_time_rate_percent"] = (
    playback_exception_summary["zero_play_time_count"] / playback_exception_summary["impression_count"] * 100
).round(4)

playback_exception_summary["play_time_exceeds_duration_rate_percent"] = (
    playback_exception_summary["play_time_exceeds_duration_count"] / playback_exception_summary["impression_count"] * 100
).round(4)

playback_exception_summary = playback_exception_summary[
    [
        "traffic_source", "click_status", "impression_count", "zero_duration_count", "zero_duration_rate_percent", "zero_play_time_count", 
        "zero_play_time_rate_percent", "play_time_exceeds_duration_count", "play_time_exceeds_duration_rate_percent",
        "median_play_time_ms", "median_event_content_duration_ms", "median_playback_completion_rate"
    ]
]

playback_exception_summary

,traffic_source,click_status,impression_count,zero_duration_count,zero_duration_rate_percent,zero_play_time_count,zero_play_time_rate_percent,play_time_exceeds_duration_count,play_time_exceeds_duration_rate_percent,median_play_time_ms,median_event_content_duration_ms,median_playback_completion_rate
0,random,clicked,208934,2792,1.3363,376,0.1800,40844,19.5488,14982.0,76400.0,0.299041
1,random,not_clicked,977115,34128,3.4927,7537,0.7714,33997,3.4793,1754.0,76920.0,0.024861
2,standard,clicked,655796,6511,0.9928,5056,0.7710,219385,33.4532,27682.0,72266.0,0.698498
3,standard,not_clicked,755854,22347,2.9565,183662,24.2986,18180,2.4052,1645.0,69033.0,0.020530

In [36]:
# Checking how much creator profile coverage is available from the user table

creator_user_ids = (video_attributes["creator_user_id"]
                    .dropna()
                    .drop_duplicates()
)

creator_profile_coverage = pd.DataFrame(
    {
        "metric_name": ["distinct_creator_count",
                        "distinct_creators_present_in_user_dimension",
                        "distinct_creators_missing_from_user_dimension",
                        "distinct_creator_coverage_rate_percent",
                        "impression_rows_with_creator_present_in_user_dimension",
                        "impression_row_creator_coverage_rate_percent"
        ],
        "value": [int(creator_user_ids.nunique()),
                  int(creator_user_ids.isin(user_dimension["user_id"]).sum()),
                  int((~creator_user_ids.isin(user_dimension["user_id"])).sum()),
                  round(creator_user_ids.isin(user_dimension["user_id"]).mean() * 100, 4),
                  int(impression_fact["creator_user_id"].isin(user_dimension["user_id"]).sum()),
                  round(impression_fact["creator_user_id"].isin(user_dimension["user_id"]).mean() * 100, 4)
        ]
    }
)

creator_profile_coverage

                                         metric_name       value
0                             distinct_creator_count   6510.0000
1        distinct_creators_present_in_user_dimension    104.0000
2      distinct_creators_missing_from_user_dimension   6406.0000
3             distinct_creator_coverage_rate_percent      1.5975
4  impression_rows_with_creator_present_in_user_d...  51663.0000
5       impression_row_creator_coverage_rate_percent      1.9888

In [37]:
# Profiling the final fact fields to confirm readiness and data coverage

final_field_profile = pd.DataFrame(
    {
        "field_name": impression_fact.columns,
        "data_type": impression_fact.dtypes.astype(str).values,
        "missing_count": impression_fact.isna().sum().values,
        "missing_rate_percent": (impression_fact.isna().mean().values * 100).round(4),
        "distinct_value_count": [impression_fact[column].nunique(dropna = False)
                                 for column in impression_fact.columns
        ],
        "sample_value": [impression_fact[column].dropna().iloc[0]
                         if impression_fact[column].notna().any()
                         else np.nan
                         for column in impression_fact.columns
        ]
    }
).sort_values(["missing_rate_percent", "field_name"],
              ascending = [False, True]
).reset_index(drop = True)


final_field_profile

                          field_name            data_type  missing_count  missing_rate_percent  distinct_value_count                      sample_value
0                         music_type              float64          79102                3.0451                     6                               9.0
1           playback_completion_rate              float64          65778                2.5322               2171493                          0.004437
2    playback_completion_rate_capped              float64          65778                2.5322               1933750                          0.004437
3                  video_duration_ms              float64          65778                2.5322                  5757                          289866.0
4                          video_tag               string          27593                1.0622                   111                                 3
5                  comment_stay_time                int32              0                0.0000                 24967                                 0
6                    creator_user_id                int64              0                0.0000                  6510                           6705448
7          event_content_duration_ms                int32              0                0.0000                  5757                            289866
8                         event_date       datetime64[us]              0                0.0000                    30               2022-04-09 00:00:00
9                     event_date_key                int32              0                0.0000                    30                          20220409
10                 event_hour_bucket                int32              0                0.0000                    24                              1200
11                 event_hour_of_day                 int8              0                0.0000                    24                                12
12                event_timestamp_ms                int64              0                0.0000               2511436                     1649475963278
13               event_timestamp_utc  datetime64[ms, UTC]              0                0.0000               2511436  2022-04-09 03:46:03.278000+00:00
14                event_weekday_name               string              0                0.0000                     7                          Saturday
15                     fans_user_num                int64              0                0.0000                  2210                                66
16               fans_user_num_range               string              0                0.0000                     9                          [10,100)
17                       feed_tab_id                 int8              0                0.0000                    15                                 1
18                   follow_user_num                int64              0                0.0000                  2562                                78
19             follow_user_num_range               string              0                0.0000                     8                          (50,100]
20                   friend_user_num                int64              0                0.0000                  1391                                 0
21             friend_user_num_range               string              0                0.0000                     7                                 0
22  has_play_time_exceeding_duration                 int8              0                0.0000                     2                                 0
23                 has_zero_duration                 int8              0                0.0000                     2                                 0
24                has_zero_play_time                 int8              0                0.0000                     2                                 0
25                          is_click                 int8              0                0.0000                     2                                 0
26                        is_comment                 int8              0                0.0000                     2                                 0
27                         is_follow                 int8              0                0.0000                     2                                 0
28                        is_forward                 int8              0                0.0000                     2                                 0
29                           is_hate                 int8              0                0.0000                     2                                 0
30          is_high_value_engagement                 int8              0                0.0000                     2                                 0
31                           is_like                 int8              0                0.0000                     2                                 0
32               is_meaningful_watch                 int8              0                0.0000                     2                                 0
33                  is_profile_enter                 int8              0                0.0000                     2                                 0
34              is_social_engagement                 int8              0                0.0000                     2                                 0
35                   is_video_author                int64              0                0.0000                     2                                 1
36                        is_weekend                 int8              0                0.0000                     2                                 1
37                          music_id                int64              0                0.0000                  7202                        9138394916
38                      play_time_ms                int32              0                0.0000                160587                              1286
39                 profile_stay_time                int32              0                0.0000                   184                                 0
40                     register_days                int64              0                0.0000                  2813                              2479
41               register_days_range               string              0                0.0000                     8                              730+
42                    traffic_source                  str              0                0.0000                     2                          standard
43                user_active_degree               string              0                0.0000                     9                       full_active
44                           user_id                int32              0                0.0000                 27285                             20853
45                    video_age_days                int64              0                0.0000                    30                                 0
46                      video_height              float64              0                0.0000                   120                            1280.0
47                          video_id                int32              0                0.0000                  7583                               222
48                 video_orientation                  str              0                0.0000                     3                          vertical
49                        video_type               string              0                0.0000                     3                            NORMAL
50                 video_upload_date       datetime64[us]              0                0.0000                     3               2022-04-09 00:00:00
51                 video_upload_type               string              0                0.0000                    14                               Web
52                       video_width              float64              0                0.0000                   156                             720.0

In [38]:
# Reviewing the main categorical fields for reporting usefulness

business_categorical_fields = ["traffic_source", "feed_tab_id", "user_active_degree", "follow_user_num_range",
                               "fans_user_num_range", "friend_user_num_range", "register_days_range", "video_type",
                               "video_upload_type", "music_type"
]

categorical_field_summary = pd.DataFrame(
    {
        "field_name": business_categorical_fields,
        "distinct_value_count": [impression_fact[field].nunique(dropna = False)
                                 for field in business_categorical_fields
        ],
        "missing_count": [int(impression_fact[field].isna().sum())
                          for field in business_categorical_fields
        ],
        "top_value": [impression_fact[field].value_counts(dropna = False).index[0]
                      for field in business_categorical_fields
        ],
        "top_value_count": [int(impression_fact[field].value_counts(dropna = False).iloc[0])
                            for field in business_categorical_fields
        ]
    }
)

categorical_field_summary

              field_name  distinct_value_count  missing_count    top_value  top_value_count
0         traffic_source                     2              0     standard          1411650
1            feed_tab_id                    15              0            1          2236411
2     user_active_degree                     9              0  full_active          1889845
3  follow_user_num_range                     8              0         500+           537421
4    fans_user_num_range                     9              0     [10,100)           991288
5  friend_user_num_range                     7              0       [5,30)           726049
6    register_days_range                     8              0         730+          1909229
7             video_type                     3              0       NORMAL          2568173
8      video_upload_type                    14              0   LongImport          1070378
9             music_type                     6          79102          9.0          2292634

In [39]:
# Inspecting the video tag structure before splitting tags for analysis

video_tag_profile = video_attributes[["video_id", "video_tag"]].copy()

video_tag_profile["tag_count"] = np.where(
    video_tag_profile["video_tag"].notna(),
    video_tag_profile["video_tag"].astype("string").str.count(",") + 1,
    np.nan
)

video_tag_structure_summary = pd.DataFrame(
    {
        "metric_name": ["video_count", "videos_with_missing_tag", "videos_with_single_tag",
                        "videos_with_multiple_tags", "maximum_tag_count_per_video"
        ],
        "value": [int(len(video_tag_profile)), 
                  int(video_tag_profile["video_tag"].isna().sum()),
                  int((video_tag_profile["tag_count"] == 1).sum()),
                  int((video_tag_profile["tag_count"] > 1).sum()),
                  int(video_tag_profile["tag_count"].max())
        ]
    }
)

exploded_video_tags = (video_tag_profile.loc[video_tag_profile["video_tag"].notna(), "video_tag"]
                       .astype("string")
                       .str.split(",")
                       .explode()
                       .str.strip()
)

top_video_tags = (exploded_video_tags.value_counts()
                  .head(20)
                  .rename_axis("video_tag")
                  .reset_index(name = "video_count")
)

video_tag_structure_summary

                   metric_name  value
0                  video_count   7583
1      videos_with_missing_tag     96
2       videos_with_single_tag   5696
3    videos_with_multiple_tags   1791
4  maximum_tag_count_per_video      3

In [40]:
# Surfacing the most common tags for later content-level reporting
top_video_tags

   video_tag  video_count
0         39         1446
1          3          732
2         20          675
3         12          606
4         62          489
5         43          428
6         68          428
7          9          419
8          6          400
9          7          383
10         2          296
11         1          254
12        15          245
13        17          220
14        67          206
15        11          181
16         4          177
17         8          177
18        28          145
19        60          144

In [41]:
# Exposing the truly conflicting duplicates as evidence for the exclusion policy

conflicting_duplicate_rows = (interaction_log_exact_deduplicated
                              .merge(unresolved_duplicate_keys, on = duplicate_key_columns, how = "inner")
                              .sort_values(duplicate_key_columns + ["date", "hourmin", "source_file"])
                              .reset_index(drop = True)
)

conflicting_duplicate_rows[
    [
        "user_id", "video_id", "time_ms", "date", "hourmin",
        "is_click", "is_like", "is_follow", "is_comment", "is_forward", "is_hate",
        "long_view", "play_time_ms", "duration_ms", "profile_stay_time", "comment_stay_time", 
        "is_profile_enter", "is_rand", "tab", "source_file", "traffic_source", "source_period"
    ]
]

,user_id,video_id,time_ms,date,hourmin,is_click,is_like,is_follow,is_comment,is_forward,is_hate,long_view,play_time_ms,duration_ms,profile_stay_time,comment_stay_time,is_profile_enter,is_rand,tab,source_file,traffic_source,source_period
0,1631,2329,1649908983373,20220414,1200,0,0,0,0,0,0,0,787,78733,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
1,1631,2329,1649908983373,20220414,1200,0,0,0,0,0,0,0,4960,78733,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
2,1756,4745,1651310345755,20220430,1700,1,0,0,0,0,0,1,48585,66700,0,0,0,0,5,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
3,1756,4745,1651310345755,20220430,1700,1,0,0,0,0,0,1,18726,66700,0,0,0,0,5,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
4,2037,527,1649905720525,20220414,1100,0,0,0,0,0,0,0,854,10388,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
5,2037,527,1649905720525,20220414,1100,0,0,0,0,0,0,0,1588,10388,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
6,2116,5319,1649512329194,20220409,2200,1,0,0,0,0,0,1,55927,7720,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
7,2116,5319,1649512329194,20220409,2200,1,0,0,0,0,0,1,55927,7720,0,47537,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
8,2373,2055,1649660927424,20220411,1500,1,0,0,0,0,0,0,1182,15800,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
9,2373,2055,1649660927424,20220411,1500,1,0,0,0,0,0,0,12451,15800,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
10,3366,7013,1651453610578,20220502,900,1,0,0,0,0,0,0,5348,72240,0,0,1,0,5,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
11,3366,7013,1651453610578,20220502,900,1,0,0,0,0,0,0,8051,72240,0,0,1,0,5,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
12,5333,1103,1651312900992,20220430,1800,0,0,0,0,0,0,0,1047,108650,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
13,5333,1103,1651312900992,20220430,1800,1,0,0,0,0,0,0,2852,108650,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
14,5446,7086,1649507452336,20220409,2000,0,0,0,0,0,0,0,1934,11333,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
15,5446,7086,1649507452336,20220409,2000,1,0,0,0,0,0,0,7250,11333,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
16,7079,706,1650582098237,20220422,700,1,1,0,1,0,0,1,67019,156066,0,41221,1,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
17,7079,706,1650582098237,20220422,700,1,1,0,0,0,0,1,57290,156066,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
18,7479,6132,1651234531759,20220429,2000,0,0,0,0,0,0,0,1411,25100,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
19,7479,6132,1651234531759,20220429,2000,0,0,0,0,0,0,0,1634,25100,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
20,10790,7201,1649637833896,20220411,800,1,0,0,0,0,0,0,12860,15066,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
21,10790,7201,1649637833896,20220411,800,1,0,0,0,0,0,0,12860,15066,0,0,1,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
22,10840,5937,1650364049575,20220419,1800,0,0,0,0,0,0,0,820,133383,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
23,10840,5937,1650364049575,20220419,1800,0,0,0,0,0,0,0,738,133383,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
24,11426,1129,1651137326003,20220428,1700,1,0,0,1,0,0,0,8731,101666,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
25,11426,1129,1651137326003,20220428,1700,1,0,0,1,0,0,0,11055,101666,0,7306,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
26,12686,4658,1651728612815,20220505,1300,1,0,0,0,0,0,1,17431,10343,0,0,1,0,5,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
27,12686,4658,1651728612815,20220505,1300,1,0,1,0,0,0,1,17431,10343,0,0,1,0,5,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
28,13532,6266,1651455476736,20220502,900,1,0,0,0,0,0,1,22460,160866,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
29,13532,6266,1651455476736,20220502,900,1,0,0,0,0,0,0,816,160866,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
30,13889,2436,1650960172850,20220426,1600,1,0,0,0,0,0,1,96215,98016,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
31,13889,2436,1650960172850,20220426,1600,1,0,0,0,0,0,1,96215,98016,0,7354,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
32,14053,2684,1651933343273,20220507,2200,1,0,0,0,0,0,1,20845,317633,0,15676,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
33,14053,2684,1651933343273,20220507,2300,1,0,0,0,0,0,1,20845,317633,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
34,15180,4420,1651325924545,20220430,2100,1,1,0,0,0,0,1,116423,115541,0,5169,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
35,15180,4420,1651325924545,20220430,2200,1,1,0,0,0,0,1,116423,115541,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
36,15293,969,1651548228884,20220503,1100,0,0,0,0,0,0,0,980,30366,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
37,15293,969,1651548228884,20220503,1100,0,0,0,0,0,0,0,526,30366,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
38,15775,259,1649765318126,20220412,2000,0,0,0,0,0,0,0,1509,223783,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
39,15775,259,1649765318126,20220412,2000,0,0,0,0,0,0,0,1117,223783,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
40,18426,6370,1651845768685,20220506,2200,1,0,0,0,0,0,1,39605,43066,0,3517,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
41,18426,6370,1651845768685,20220506,2200,1,0,0,0,0,0,1,39605,43066,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
42,18964,1103,1651330728422,20220430,2300,1,0,0,0,0,0,1,73848,108650,0,0,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
43,18964,1103,1651330728422,20220430,2300,1,0,0,0,0,0,1,73848,108650,0,12252,0,0,6,log_standard_4_22_to_5_08_pure,standard,20220422_20220508
44,19733,5819,1649753737694,20220412,1700,0,0,0,0,0,0,0,1583,41240,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
45,19733,5819,1649753737694,20220412,1700,0,0,0,0,0,0,0,979,41240,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
46,21537,7358,1649550656371,20220410,800,1,0,0,0,0,0,0,0,95183,0,0,0,0,1,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
47,21537,7358,1649550656371,20220410,800,1,0,0,0,0,0,1,95249,95183,0,0,0,0,1,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
48,22424,543,1650227102029,20220418,400,0,0,0,0,0,0,0,1110,31700,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
49,22424,543,1650227102029,20220418,400,0,0,0,0,0,0,0,1299,31700,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
50,23788,6712,1650165238454,20220417,1100,1,0,0,0,0,0,0,588,31166,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
51,23788,6712,1650165238454,20220417,1100,1,0,0,0,0,0,0,109,31166,0,0,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
52,24085,6801,1649864520366,20220413,2300,1,0,0,0,0,0,1,77318,35600,0,11069,1,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421
53,24085,6801,1649864520366,20220413,2300,1,0,0,0,0,0,1,77318,35600,0,11069,0,0,6,log_standard_4_08_to_4_21_pure,standard,20220408_20220421

In [42]:
# Summarizing whether the current fact table is ready for analysis use

creator_profile_coverage_rate = (impression_fact["creator_user_id"]
                                 .isin(user_dimension["user_id"])
                                 .mean()
)

dataset_readiness = pd.DataFrame(
    {
        "metric_name": ["row_count", "column_count", 
                        "duplicate_event_key_count", "resolved_temporal_only_duplicate_event_key_count",
                        "excluded_conflicting_duplicate_event_key_count", "excluded_conflicting_duplicate_row_count",
                        "missing_user_attribute_count", "missing_creator_user_id_count", "missing_event_content_duration_count",
                        "missing_video_duration_count", "missing_music_type_count", "missing_video_tag_count",
                        "negative_video_age_count", "creator_profile_coverage_rate_percent", "click_rate_percent",
                        "meaningful_watch_rate_percent", "social_engagement_rate_percent", "high_value_engagement_rate_percent"
        ],
        "value": [int(len(impression_fact)), 
                  int(impression_fact.shape[1]),
                  int(impression_fact.duplicated(subset = ["user_id", "video_id", "event_timestamp_ms"]).sum()),
                  int(len(temporal_only_duplicate_keys)),
                  int(len(unresolved_duplicate_keys)),
                  int(interaction_log_exact_deduplicated
                      .merge(unresolved_duplicate_keys, on = duplicate_key_columns, how = "inner")
                      .shape[0]),
                  int(impression_fact["user_active_degree"].isna().sum()),
                  int(impression_fact["creator_user_id"].isna().sum()),
                  int(impression_fact["event_content_duration_ms"].isna().sum()),
                  int(impression_fact["video_duration_ms"].isna().sum()),
                  int(impression_fact["music_type"].isna().sum()),
                  int(impression_fact["video_tag"].isna().sum()),
                  int((impression_fact["video_age_days"] < 0).fillna(False).sum()),
                  round(creator_profile_coverage_rate * 100, 4),
                  round(impression_fact["is_click"].mean() * 100, 4),
                  round(impression_fact["is_meaningful_watch"].mean() * 100, 4),
                  round(impression_fact["is_social_engagement"].mean() * 100, 4),
                  round(impression_fact["is_high_value_engagement"].mean() * 100, 4)
        ]
    }
)

field_missingness = pd.DataFrame(
    {
        "field_name": impression_fact.columns,
        "data_type": impression_fact.dtypes.astype(str).values,
        "missing_count": impression_fact.isna().sum().values,
        "missing_rate_percent": (impression_fact.isna().mean().values * 100).round(4)
    }
)

field_missingness = (field_missingness
                     .query("missing_count > 0")
                     .sort_values(["missing_rate_percent", "field_name"], ascending = [False, True])
                     .reset_index(drop = True)
)

display(dataset_readiness)
display(field_missingness)

                                         metric_name         value
0                                          row_count  2.597699e+06
1                                       column_count  5.300000e+01
2                          duplicate_event_key_count  0.000000e+00
3   resolved_temporal_only_duplicate_event_key_count  1.459000e+03
4     excluded_conflicting_duplicate_event_key_count  2.700000e+01
5           excluded_conflicting_duplicate_row_count  5.400000e+01
6                       missing_user_attribute_count  0.000000e+00
7                      missing_creator_user_id_count  0.000000e+00
8               missing_event_content_duration_count  0.000000e+00
9                       missing_video_duration_count  6.577800e+04
10                          missing_music_type_count  7.910200e+04
11                           missing_video_tag_count  2.759300e+04
12                          negative_video_age_count  0.000000e+00
13             creator_profile_coverage_rate_percent  1.988800e+00
14                                click_rate_percent  3.328830e+01
15                     meaningful_watch_rate_percent  2.214140e+01
16                    social_engagement_rate_percent  1.463700e+00
17                high_value_engagement_rate_percent  2.916000e-01

                        field_name data_type  missing_count  missing_rate_percent
0                       music_type   float64          79102                3.0451
1         playback_completion_rate   float64          65778                2.5322
2  playback_completion_rate_capped   float64          65778                2.5322
3                video_duration_ms   float64          65778                2.5322
4                        video_tag    string          27593                1.0622

In [43]:
# Saving the full curated impression fact table for reproducible downstream use

upload_dataframe_to_parquet_blob(impression_fact,
                                 container_names["curated"],
                                 "impression_fact.parquet"
)

pd.DataFrame(
    {
        "dataset_name": ["impression_fact"],
        "row_count": [len(impression_fact)],
        "column_count": [impression_fact.shape[1]]
    }
)

      dataset_name  row_count  column_count
0  impression_fact    2597699            53

In [44]:
# Verifying that the attribute joins are not changing the event grain

pre_join_row_count = len(impression_events)

post_join_row_count = len(impression_fact)

join_validation_summary = pd.DataFrame(
    {
        "metric_name": ["pre_join_row_count",
                        "post_join_row_count",
                        "row_count_difference",
                        "duplicate_event_key_count_after_join"
        ],
        "value": [int(pre_join_row_count),
                  int(post_join_row_count),
                  int(post_join_row_count - pre_join_row_count),
                  int(impression_fact.duplicated(
                        subset = ["user_id", "video_id", "event_timestamp_ms"]
                    ).sum()
                )
        ]
    }
)

binary_flag_columns = ["is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", "is_like",
                       "is_follow", "is_comment", "is_forward", "is_hate", "is_profile_enter", 
                       "has_zero_duration", "has_zero_play_time", "has_play_time_exceeding_duration", "is_weekend"
]

binary_flag_validation = pd.DataFrame(
    {
        "field_name": binary_flag_columns,
        "invalid_value_count": [
            int((~impression_fact[column].isin([0, 1])).sum())
            for column in binary_flag_columns
        ]
    }
)

display(join_validation_summary)
display(binary_flag_validation.sort_values("invalid_value_count", ascending = False))

                            metric_name    value
0                    pre_join_row_count  2597699
1                   post_join_row_count  2597699
2                  row_count_difference        0
3  duplicate_event_key_count_after_join        0

                          field_name  invalid_value_count
0                           is_click                    0
1                is_meaningful_watch                    0
2               is_social_engagement                    0
3           is_high_value_engagement                    0
4                            is_like                    0
5                          is_follow                    0
6                         is_comment                    0
7                         is_forward                    0
8                            is_hate                    0
9                   is_profile_enter                    0
10                 has_zero_duration                    0
11                has_zero_play_time                    0
12  has_play_time_exceeding_duration                    0
13                        is_weekend                    0

In [45]:
# Confirming whether the two duration fields are materially different

duration_comparison = impression_fact[
    [
        "event_content_duration_ms", "video_duration_ms"
    ]
].copy()

duration_comparison = duration_comparison[
    duration_comparison["video_duration_ms"].notna()
].copy()

duration_comparison["duration_difference_ms"] = (
    duration_comparison["event_content_duration_ms"] - duration_comparison["video_duration_ms"]
)

duration_comparison["absolute_duration_difference_ms"] = (
    duration_comparison["duration_difference_ms"].abs()
)

duration_concordance_summary = pd.DataFrame(
    {
        "metric_name": ["rows_with_both_duration_fields",
                        "exact_match_count", "exact_match_rate_percent", "median_absolute_difference_ms",
                        "p95_absolute_difference_ms", "rows_with_difference_over_1000_ms", "rate_over_1000_ms_percent"
        ],
        "value": [int(len(duration_comparison)),
                  int((duration_comparison["duration_difference_ms"] == 0).sum()),
                  round((duration_comparison["duration_difference_ms"] == 0).mean() * 100, 4),
                  float(duration_comparison["absolute_duration_difference_ms"].median()),
                  float(duration_comparison["absolute_duration_difference_ms"].quantile(0.95)),
                  int((duration_comparison["absolute_duration_difference_ms"] > 1000).sum()),
                  round((duration_comparison["absolute_duration_difference_ms"] > 1000).mean() * 100, 4)
        ]
    }
)

duration_difference_examples = (
    impression_fact.loc[
        impression_fact["video_duration_ms"].notna() & (impression_fact["event_content_duration_ms"] != impression_fact["video_duration_ms"]),
        [
            "video_id", "event_content_duration_ms", "video_duration_ms"
        ]
    ]
    .drop_duplicates()
    .head(20)
)

display(duration_concordance_summary)
display(duration_difference_examples)

                         metric_name      value
0     rows_with_both_duration_fields  2531921.0
1                  exact_match_count  2531921.0
2           exact_match_rate_percent      100.0
3      median_absolute_difference_ms        0.0
4         p95_absolute_difference_ms        0.0
5  rows_with_difference_over_1000_ms        0.0
6          rate_over_1000_ms_percent        0.0

Empty DataFrame
Columns: [video_id, event_content_duration_ms, video_duration_ms]
Index: []

In [46]:
# Recording why the aggregate video statistics table is being excluded

excluded_source_review = pd.DataFrame(
    {
        "source_table": ["video_dimension_statistic"],
        "current_use_in_impression_fact": ["excluded"],
        "reason": ["Contains aggregate performance fields that are likely post-outcome and unsuitable for the impression-level "
                   "predictive base unless a later descriptive use is specifically justified."
        ]
    }
)

excluded_source_review

                source_table current_use_in_impression_fact                                             reason
0  video_dimension_statistic                       excluded  Contains aggregate performance fields that are...

In [47]:
# Checking how downstream engagement behaves once a click has happened

downstream_event_columns = ["is_meaningful_watch", "is_like", "is_follow", "is_comment",
                            "is_forward", "is_high_value_engagement"
]

click_dependency_by_traffic_source = (
    impression_fact
    .assign(click_status = np.where(impression_fact["is_click"].eq(1), "clicked", "not_clicked"))
    .groupby(["traffic_source", "click_status"], as_index = False)
    .agg(
        impression_count = ("user_id", "size"),
        meaningful_watch_rate_percent = ("is_meaningful_watch", lambda s: round(s.mean() * 100, 4)),
        like_rate_percent = ("is_like", lambda s: round(s.mean() * 100, 4)),
        follow_rate_percent = ("is_follow", lambda s: round(s.mean() * 100, 4)),
        comment_rate_percent = ("is_comment", lambda s: round(s.mean() * 100, 4)),
        forward_rate_percent = ("is_forward", lambda s: round(s.mean() * 100, 4)),
        high_value_engagement_rate_percent = ("is_high_value_engagement", lambda s: round(s.mean() * 100, 4))
    )
)

click_dependency_by_traffic_source

,traffic_source,click_status,impression_count,meaningful_watch_rate_percent,like_rate_percent,follow_rate_percent,comment_rate_percent,forward_rate_percent,high_value_engagement_rate_percent
0,random,clicked,208934,48.0554,1.6666,0.1101,0.1900,0.1374,0.4351
1,random,not_clicked,977115,0.0374,0.2261,0.0082,0.0014,0.0118,0.0213
2,standard,clicked,655796,72.0468,3.3977,0.2049,0.5381,0.1856,0.9200
3,standard,not_clicked,755854,0.2538,0.5379,0.0221,0.0134,0.0208,0.0562

In [48]:
# Cataloging the retained analysis fields with their business roles

analysis_field_catalog = pd.DataFrame(
    [
        ("user_id", "identifier", "Impression viewer identifier"),
        ("video_id", "identifier", "Video identifier"),
        ("creator_user_id", "identifier", "Video creator identifier"),
        ("event_timestamp_ms", "identifier", "Event timestamp in milliseconds"),
        ("event_date_key", "calendar", "Source event date key"),
        ("event_date", "calendar", "Source event date"),
        ("event_weekday_name", "calendar", "Weekday derived from source event date"),
        ("is_weekend", "calendar", "Weekend flag derived from source event date"),
        ("traffic_source", "delivery_context", "Traffic allocation source"),
        ("feed_tab_id", "delivery_context", "Feed tab identifier"),
        ("is_click", "outcome", "Primary engagement target"),
        ("is_meaningful_watch", "outcome", "Meaningful watch outcome"),
        ("is_social_engagement", "outcome", "Any social engagement outcome"),
        ("is_high_value_engagement", "outcome", "Follow or comment or forward"),
        ("is_like", "outcome", "Like outcome"),
        ("is_follow", "outcome", "Follow outcome"),
        ("is_comment", "outcome", "Comment outcome"),
        ("is_forward", "outcome", "Forward outcome"),
        ("is_hate", "outcome", "Negative reaction outcome"),
        ("is_profile_enter", "outcome", "Profile entry outcome"),
        ("play_time_ms", "behavior_measure", "Observed play time"),
        ("event_content_duration_ms", "behavior_measure", "Content duration recorded on the event"),
        ("playback_completion_rate", "behavior_measure", "Play time divided by content duration, capped to 1"),
        ("profile_stay_time", "behavior_measure", "Profile stay time"),
        ("comment_stay_time", "behavior_measure", "Comment area stay time"),
        ("has_zero_duration", "quality_flag", "Event content duration equals zero"),
        ("has_zero_play_time", "quality_flag", "Play time equals zero"),
        ("has_play_time_exceeding_duration", "quality_flag", "Play time exceeds content duration"),
        ("user_active_degree", "user_attribute", "User activity segment"),
        ("is_video_author", "user_attribute", "Whether the user is a video author"),
        ("follow_user_num", "user_attribute", "Followed users count"),
        ("follow_user_num_range", "user_attribute", "Followed users count band"),
        ("fans_user_num", "user_attribute", "Fans count"),
        ("fans_user_num_range", "user_attribute", "Fans count band"),
        ("friend_user_num", "user_attribute", "Friends count"),
        ("friend_user_num_range", "user_attribute", "Friends count band"),
        ("register_days", "user_attribute", "Days since registration"),
        ("register_days_range", "user_attribute", "Registration age band"),
        ("video_type", "content_attribute", "Video type"),
        ("video_upload_date", "content_attribute", "Video upload date"),
        ("video_upload_type", "content_attribute", "Video upload source type"),
        ("video_width", "content_attribute", "Video width"),
        ("video_height", "content_attribute", "Video height"),
        ("video_orientation", "content_attribute", "Video orientation"),
        ("music_type", "content_attribute", "Music type"),
        ("video_age_days", "content_attribute", "Video age in days at event date")
    ],
    columns = ["field_name", "field_group", "business_definition"]
)

field_profile = pd.DataFrame(
    {
        "field_name": impression_fact.columns,
        "data_type": impression_fact.dtypes.astype(str).values,
        "missing_count": impression_fact.isna().sum().values,
        "missing_rate_percent": (impression_fact.isna().mean().values * 100).round(4),
        "distinct_value_count": [impression_fact[column].nunique(dropna = False)
                                 for column in impression_fact.columns
        ]
    }
)

analysis_field_catalog = (analysis_field_catalog
                          .merge(field_profile, on = "field_name", how = "left")
                          .sort_values(["field_group", "field_name"])
                          .reset_index(drop = True)
)

analysis_field_catalog

,field_name,field_group,business_definition,data_type,missing_count,missing_rate_percent,distinct_value_count
0,comment_stay_time,behavior_measure,Comment area stay time,int32,0,0.0000,24967
1,event_content_duration_ms,behavior_measure,Content duration recorded on the event,int32,0,0.0000,5757
2,play_time_ms,behavior_measure,Observed play time,int32,0,0.0000,160587
3,playback_completion_rate,behavior_measure,"Play time divided by content duration, capped ...",float64,65778,2.5322,2171493
4,profile_stay_time,behavior_measure,Profile stay time,int32,0,0.0000,184
5,event_date,calendar,Source event date,datetime64[us],0,0.0000,30
6,event_date_key,calendar,Source event date key,int32,0,0.0000,30
7,event_weekday_name,calendar,Weekday derived from source event date,string,0,0.0000,7
8,is_weekend,calendar,Weekend flag derived from source event date,int8,0,0.0000,2
9,music_type,content_attribute,Music type,float64,79102,3.0451,6
10,video_age_days,content_attribute,Video age in days at event date,int64,0,0.0000,30
11,video_height,content_attribute,Video height,float64,0,0.0000,120
12,video_orientation,content_attribute,Video orientation,str,0,0.0000,3
13,video_type,content_attribute,Video type,string,0,0.0000,3
14,video_upload_date,content_attribute,Video upload date,datetime64[us],0,0.0000,3
15,video_upload_type,content_attribute,Video upload source type,string,0,0.0000,14
16,video_width,content_attribute,Video width,float64,0,0.0000,156
17,feed_tab_id,delivery_context,Feed tab identifier,int8,0,0.0000,15
18,traffic_source,delivery_context,Traffic allocation source,str,0,0.0000,2
19,creator_user_id,identifier,Video creator identifier,int64,0,0.0000,6510
20,event_timestamp_ms,identifier,Event timestamp in milliseconds,int64,0,0.0000,2511436
21,user_id,identifier,Impression viewer identifier,int32,0,0.0000,27285
22,video_id,identifier,Video identifier,int32,0,0.0000,7583
23,is_click,outcome,Primary engagement target,int8,0,0.0000,2
24,is_comment,outcome,Comment outcome,int8,0,0.0000,2
25,is_follow,outcome,Follow outcome,int8,0,0.0000,2
26,is_forward,outcome,Forward outcome,int8,0,0.0000,2
27,is_hate,outcome,Negative reaction outcome,int8,0,0.0000,2
28,is_high_value_engagement,outcome,Follow or comment or forward,int8,0,0.0000,2
29,is_like,outcome,Like outcome,int8,0,0.0000,2
30,is_meaningful_watch,outcome,Meaningful watch outcome,int8,0,0.0000,2
31,is_profile_enter,outcome,Profile entry outcome,int8,0,0.0000,2
32,is_social_engagement,outcome,Any social engagement outcome,int8,0,0.0000,2
33,has_play_time_exceeding_duration,quality_flag,Play time exceeds content duration,int8,0,0.0000,2
34,has_zero_duration,quality_flag,Event content duration equals zero,int8,0,0.0000,2
35,has_zero_play_time,quality_flag,Play time equals zero,int8,0,0.0000,2
36,fans_user_num,user_attribute,Fans count,int64,0,0.0000,2210
37,fans_user_num_range,user_attribute,Fans count band,string,0,0.0000,9
38,follow_user_num,user_attribute,Followed users count,int64,0,0.0000,2562
39,follow_user_num_range,user_attribute,Followed users count band,string,0,0.0000,8
40,friend_user_num,user_attribute,Friends count,int64,0,0.0000,1391
41,friend_user_num_range,user_attribute,Friends count band,string,0,0.0000,7
42,is_video_author,user_attribute,Whether the user is a video author,int64,0,0.0000,2
43,register_days,user_attribute,Days since registration,int64,0,0.0000,2813
44,register_days_range,user_attribute,Registration age band,string,0,0.0000,8
45,user_active_degree,user_attribute,User activity segment,string,0,0.0000,9

In [49]:
# Recording which fields are being excluded from the analysis base and why

excluded_field_review = pd.DataFrame(
    [
        ("event_timestamp_utc", "Redundant with event_timestamp_ms"),
        ("event_hour_bucket", "Raw hour field is not reliable enough for main analysis"),
        ("event_hour_of_day", "Derived from event_hour_bucket"),
        ("video_duration_ms", "Duplicates event_content_duration_ms where present"),
        ("playback_completion_rate_capped", "Replaced by a single standardized playback_completion_rate field"),
        ("music_id", "Very high-cardinality identifier with limited direct analytical value at this stage"),
        ("video_tag", "Moved to a separate bridge table because one video can carry multiple tags"),
        ("video_dimension_statistic.*", "Aggregate performance fields are post-outcome summaries and unsuitable for the impression-level analytical base")
    ],
    columns = ["excluded_field", "reason"]
)

excluded_field_review

                    excluded_field                                             reason
0              event_timestamp_utc                  Redundant with event_timestamp_ms
1                event_hour_bucket  Raw hour field is not reliable enough for main...
2                event_hour_of_day                     Derived from event_hour_bucket
3                video_duration_ms  Duplicates event_content_duration_ms where pre...
4  playback_completion_rate_capped  Replaced by a single standardized playback_com...
5                         music_id  Very high-cardinality identifier with limited ...
6                        video_tag  Moved to a separate bridge table because one v...
7      video_dimension_statistic.*  Aggregate performance fields are post-outcome ...

In [50]:
# Building the lean analysis base from the wider impression fact table

impression_analysis_base = impression_fact.copy()

impression_analysis_base["playback_completion_rate"] = np.where(
    impression_analysis_base["event_content_duration_ms"] > 0,
    (
        impression_analysis_base["play_time_ms"] / impression_analysis_base["event_content_duration_ms"]
    ).clip(lower = 0, upper = 1),
    np.nan
)


# Keeping only the fields that are justified for analysis and reporting
analysis_base_columns = ["user_id", "video_id", "creator_user_id", "event_timestamp_ms", "event_date_key", "event_date",
                         "traffic_source", "feed_tab_id",
                         "is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", "is_like", "is_follow",
                         "is_comment", "is_forward", "is_hate", "is_profile_enter",
                         "play_time_ms", "event_content_duration_ms", "playback_completion_rate", "profile_stay_time", "comment_stay_time",
                         "has_zero_duration", "has_zero_play_time", "has_play_time_exceeding_duration", "user_active_degree", 
                         "is_video_author", "follow_user_num", "follow_user_num_range", "fans_user_num", "fans_user_num_range", 
                         "friend_user_num", "friend_user_num_range", "register_days", "register_days_range", "video_type", 
                         "video_upload_date", "video_upload_type", "video_width", "video_height", "video_orientation", 
                         "music_type", "video_age_days"
]

impression_analysis_base = (impression_analysis_base[analysis_base_columns]
                            .sort_values(["event_date", "event_timestamp_ms", "user_id", "video_id"])
                            .reset_index(drop = True)
)

print(impression_analysis_base.shape)
impression_analysis_base.head()

(2597699, 44)

,user_id,video_id,creator_user_id,event_timestamp_ms,event_date_key,event_date,traffic_source,feed_tab_id,is_click,is_meaningful_watch,is_social_engagement,is_high_value_engagement,is_like,is_follow,is_comment,is_forward,is_hate,is_profile_enter,play_time_ms,event_content_duration_ms,playback_completion_rate,profile_stay_time,comment_stay_time,has_zero_duration,has_zero_play_time,has_play_time_exceeding_duration,user_active_degree,is_video_author,follow_user_num,follow_user_num_range,fans_user_num,fans_user_num_range,friend_user_num,friend_user_num_range,register_days,register_days_range,video_type,video_upload_date,video_upload_type,video_width,video_height,video_orientation,music_type,video_age_days
0,20853,222,6705448,1649475963278,20220409,2022-04-09,standard,1,0,0,0,0,0,0,0,0,0,0,1286,289866,0.004437,0,0,0,0,0,full_active,1,78,"(50,100]",66,"[10,100)",0,0,2479,730+,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,9.0,0
1,8286,222,6705448,1649476012164,20220409,2022-04-09,standard,1,0,0,0,0,0,0,0,0,0,0,1857,289866,0.006406,0,0,0,0,0,2_14_day_new,1,64,"(50,100]",47,"[10,100)",36,"[30,60)",1420,730+,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,9.0,0
2,7406,222,6705448,1649476421916,20220409,2022-04-09,standard,4,1,1,0,0,0,0,0,0,0,1,25750,289866,0.088834,0,0,0,0,0,full_active,1,32,"(10,50]",53,"[10,100)",32,"[30,60)",102,91-180,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,9.0,0
3,25934,6580,4854468,1649476523839,20220409,2022-04-09,standard,0,0,0,0,0,0,0,0,0,0,0,0,55960,0.000000,0,0,0,1,0,full_active,0,78,"(50,100]",0,0,0,0,89,61-90,NORMAL,2022-04-09,LongImport,720.0,1280.0,vertical,9.0,0
4,2073,4566,5597283,1649476630340,20220409,2022-04-09,standard,2,0,1,0,0,0,0,0,0,0,0,14904,14700,1.000000,0,1641,0,0,1,high_active,1,153,"(150,250]",11,"[10,100)",1,"[1,5)",1711,730+,NORMAL,2022-04-09,Web,720.0,1280.0,vertical,4.0,0

In [51]:
# Splitting multi-tag videos into a bridge table for clean tag analysis

video_tag_bridge = (video_attributes[["video_id", "video_tag"]]
                    .dropna(subset = ["video_tag"])
                    .assign(video_tag = lambda frame: frame["video_tag"].astype("string").str.split(","))
                    .explode("video_tag")
                    .assign(video_tag = lambda frame: frame["video_tag"].str.strip())
                    .query("video_tag.notna()", engine = "python")
                    .drop_duplicates()
                    .reset_index(drop = True)
)

video_tag_bridge.head()

   video_id video_tag
0         0        39
1         1         2
2         2         1
3         3         7
4         4         9

In [52]:
# Confirming that the analysis base is structurally ready to use
analysis_base_readiness = pd.DataFrame(
    {
        "metric_name": ["row_count", "column_count", "duplicate_event_key_count", 
                        "missing_event_date_count", "missing_playback_completion_rate_count",
                        "missing_music_type_count", "missing_video_age_days_count"
        ],
        "value": [int(len(impression_analysis_base)), 
                  int(impression_analysis_base.shape[1]),
                  int(impression_analysis_base.duplicated(
                      subset = ["user_id", "video_id", "event_timestamp_ms"]
                    ).sum()
                ),
                  int(impression_analysis_base["event_date"].isna().sum()),
                  int(impression_analysis_base["playback_completion_rate"].isna().sum()),
                  int(impression_analysis_base["music_type"].isna().sum()),
                  int(impression_analysis_base["video_age_days"].isna().sum()),
        ]
    }
)

analysis_base_readiness

                              metric_name    value
0                               row_count  2597699
1                            column_count       44
2               duplicate_event_key_count        0
3                missing_event_date_count        0
4  missing_playback_completion_rate_count    65778
5                missing_music_type_count    79102
6            missing_video_age_days_count        0

In [53]:
# Summarizing the outcome rates that define the engagement landscape
target_summary = pd.DataFrame(
    {
        "target_name": ["is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", "is_like",
                        "is_follow", "is_comment", "is_forward", "is_hate", "is_profile_enter",
        ],
        "positive_count": [int(impression_analysis_base[column].sum())
                           for column in ["is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", "is_like", 
                                          "is_follow", "is_comment", "is_forward", "is_hate", "is_profile_enter"
            ]
        ],
        "positive_rate_percent": [round(impression_analysis_base[column].mean() * 100, 4)
                                  for column in ["is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", 
                                                 "is_like", "is_follow", "is_comment", "is_forward", "is_hate", "is_profile_enter"
            ]
        ],
    }
).sort_values("positive_rate_percent", ascending = False).reset_index(drop = True)

target_summary

                target_name  positive_count  positive_rate_percent
0                  is_click          864730                33.2883
1       is_meaningful_watch          575167                22.1414
2          is_profile_enter           40915                 1.5750
3      is_social_engagement           38023                 1.4637
4                   is_like           32039                 1.2334
5  is_high_value_engagement            7575                 0.2916
6                is_comment            4041                 0.1556
7                   is_hate            2056                 0.0791
8                 is_follow            1821                 0.0701
9                is_forward            1776                 0.0684

In [54]:
# Selecting the main categorical dimensions for segment-level analysis

selected_categorical_fields = ["traffic_source", "feed_tab_id", "user_active_degree", "follow_user_num_range", 
                               "fans_user_num_range", "friend_user_num_range", "register_days_range", 
                               "video_type", "video_upload_type", "video_orientation", "music_type"
]

categorical_field_quality = pd.DataFrame(
    {
        "field_name": selected_categorical_fields,
        "distinct_value_count": [impression_analysis_base[field].nunique(dropna = False)
                                 for field in selected_categorical_fields
        ],
        "missing_count": [int(impression_analysis_base[field].isna().sum())
                          for field in selected_categorical_fields
        ],
        "top_category": [impression_analysis_base[field].value_counts(dropna = False).index[0]
                         for field in selected_categorical_fields
        ],
        "top_category_count": [int(impression_analysis_base[field].value_counts(dropna = False).iloc[0])
                               for field in selected_categorical_fields
        ]
    }
)

categorical_field_quality

               field_name  distinct_value_count  missing_count top_category  top_category_count
0          traffic_source                     2              0     standard             1411650
1             feed_tab_id                    15              0            1             2236411
2      user_active_degree                     9              0  full_active             1889845
3   follow_user_num_range                     8              0         500+              537421
4     fans_user_num_range                     9              0     [10,100)              991288
5   friend_user_num_range                     7              0       [5,30)              726049
6     register_days_range                     8              0         730+             1909229
7              video_type                     3              0       NORMAL             2568173
8       video_upload_type                    14              0   LongImport             1070378
9       video_orientation                     3              0     vertical             1959315
10             music_type                     6          79102          9.0             2292634

In [55]:
# Comparing engagement rates across the key categorical segments
categorical_target_profiles = []

for field_name in selected_categorical_fields:
    field_profile = (
        impression_analysis_base
        .groupby(field_name, dropna = False, as_index = False)
        .agg(impression_count = ("user_id", "size"),
             click_rate_percent = ("is_click", lambda s: round(s.mean() * 100, 4)),
             meaningful_watch_rate_percent = ("is_meaningful_watch", lambda s: round(s.mean() * 100, 4)),
             social_engagement_rate_percent = ("is_social_engagement", lambda s: round(s.mean() * 100, 4)),
             high_value_engagement_rate_percent = ("is_high_value_engagement", lambda s: round(s.mean() * 100, 4))
        )
        .sort_values("impression_count", ascending = False)
        .head(20)
        .reset_index(drop = True)
    )

    field_profile.insert(0, "field_name", field_name)
    categorical_target_profiles.append(field_profile)

categorical_target_profiles = pd.concat(categorical_target_profiles, ignore_index = True)
categorical_target_profiles.head(50)

,field_name,traffic_source,impression_count,click_rate_percent,meaningful_watch_rate_percent,social_engagement_rate_percent,high_value_engagement_rate_percent,feed_tab_id,user_active_degree,follow_user_num_range,fans_user_num_range,friend_user_num_range,register_days_range,video_type,video_upload_type,video_orientation,music_type
0,traffic_source,standard,1411650,46.4560,33.6059,2.2252,0.4575,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
1,traffic_source,random,1186049,17.6160,8.4962,0.5574,0.0942,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
2,feed_tab_id,NaN,2236411,34.0898,22.4224,1.5149,0.3000,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
3,feed_tab_id,NaN,177846,9.0837,4.1210,0.4959,0.1198,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
4,feed_tab_id,NaN,93165,61.5499,48.3261,1.8934,0.2769,4.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
5,feed_tab_id,NaN,49128,47.4373,37.2659,2.4365,0.6493,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
6,feed_tab_id,NaN,20236,17.7357,8.8703,0.9834,0.2669,6.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
7,feed_tab_id,NaN,7470,0.0000,3.4003,0.3347,0.0669,11.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
8,feed_tab_id,NaN,4008,2.2455,0.3992,0.0998,0.0250,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
9,feed_tab_id,NaN,3909,4.0931,1.8931,0.1023,0.0000,8.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
10,feed_tab_id,NaN,2009,28.0737,17.0234,1.4933,0.4978,5.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
11,feed_tab_id,NaN,1472,13.5870,10.2582,0.4755,0.0679,12.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
12,feed_tab_id,NaN,546,0.0000,7.1429,0.5495,0.0000,14.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
13,feed_tab_id,NaN,504,40.2778,20.6349,3.5714,0.5952,7.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
14,feed_tab_id,NaN,444,99.3243,17.7928,1.3514,0.2252,9.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
15,feed_tab_id,NaN,399,34.8371,25.3133,0.2506,0.0000,13.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
16,feed_tab_id,NaN,152,100.0000,63.1579,1.9737,0.0000,10.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
17,user_active_degree,NaN,1889845,32.4007,21.4899,1.2854,0.2672,NaN,full_active,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
18,user_active_degree,NaN,462463,35.0034,23.4659,1.8518,0.3369,NaN,high_active,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
19,user_active_degree,NaN,166902,37.1895,24.7307,2.2996,0.4176,NaN,middle_active,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
20,user_active_degree,NaN,55735,35.4517,23.9616,1.5017,0.3068,NaN,2_14_day_new,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
21,user_active_degree,NaN,15407,38.5020,25.6247,2.3431,0.4024,NaN,low_active,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
22,user_active_degree,NaN,4481,40.1473,29.3015,2.0754,0.5356,NaN,single_low_active,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
23,user_active_degree,NaN,1228,34.0391,21.9055,1.4658,0.7329,NaN,30day_retention,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
24,user_active_degree,NaN,1111,39.3339,27.0027,1.6202,0.4500,NaN,day_new,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
25,user_active_degree,NaN,527,21.6319,11.3852,0.1898,0.0000,NaN,UNKNOWN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
26,follow_user_num_range,NaN,537421,33.8842,22.5605,2.2958,0.4425,NaN,<NA>,500+,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
27,follow_user_num_range,NaN,479351,33.3591,22.2384,0.9292,0.2343,NaN,<NA>,"(10,50]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
28,follow_user_num_range,NaN,411614,33.1169,21.9652,1.6275,0.3000,NaN,<NA>,"(250,500]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
29,follow_user_num_range,NaN,388119,33.3004,22.2728,1.1143,0.2231,NaN,<NA>,"(50,100]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
30,follow_user_num_range,NaN,349969,33.4541,22.2743,1.5756,0.2895,NaN,<NA>,"(150,250]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
31,follow_user_num_range,NaN,252544,33.3257,22.1759,1.3625,0.2602,NaN,<NA>,"(100,150]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
32,follow_user_num_range,NaN,161343,31.3909,20.4725,0.7462,0.1766,NaN,<NA>,"(0,10]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
33,follow_user_num_range,NaN,17338,30.4245,20.0542,0.2768,0.1038,NaN,<NA>,0,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
34,fans_user_num_range,NaN,991288,33.5672,22.4114,1.3859,0.3037,NaN,<NA>,<NA>,"[10,100)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
35,fans_user_num_range,NaN,875764,32.6143,21.5953,1.7143,0.3023,NaN,<NA>,<NA>,"[100,1k)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
36,fans_user_num_range,NaN,467709,34.5076,23.1353,1.2050,0.2679,NaN,<NA>,<NA>,"[1,10)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
37,fans_user_num_range,NaN,144442,31.5400,20.4207,1.8243,0.2970,NaN,<NA>,<NA>,"[1k,5k)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
38,fans_user_num_range,NaN,100515,33.7303,22.4225,0.7203,0.1960,NaN,<NA>,<NA>,0,<NA>,<NA>,<NA>,<NA>,NaN,NaN
39,fans_user_num_range,NaN,9102,29.2793,19.3474,1.2305,0.1978,NaN,<NA>,<NA>,"[5k,1w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
40,fans_user_num_range,NaN,7871,31.5462,20.6708,1.2832,0.2287,NaN,<NA>,<NA>,"[1w,10w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
41,fans_user_num_range,NaN,911,34.5774,24.2591,6.3666,0.2195,NaN,<NA>,<NA>,"[10w,100w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
42,fans_user_num_range,NaN,97,40.2062,32.9897,6.1856,0.0000,NaN,<NA>,<NA>,"[100w,1000w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
43,friend_user_num_range,NaN,726049,33.6400,22.4797,1.4058,0.3023,NaN,<NA>,<NA>,<NA>,"[5,30)",<NA>,<NA>,<NA>,NaN,NaN
44,friend_user_num_range,NaN,478219,33.8370,22.7028,1.2168,0.2756,NaN,<NA>,<NA>,<NA>,"[1,5)",<NA>,<NA>,<NA>,NaN,NaN
45,friend_user_num_range,NaN,324869,32.8025,21.2729,1.9987,0.3395,NaN,<NA>,<NA>,<NA>,250+,<NA>,<NA>,<NA>,NaN,NaN
46,friend_user_num_range,NaN,298947,33.4822,22.2996,0.7573,0.2188,NaN,<NA>,<NA>,<NA>,0,<NA>,<NA>,<NA>,NaN,NaN
47,friend_user_num_range,NaN,271666,32.8996,21.9818,1.8210,0.3052,NaN,<NA>,<NA>,<NA>,"[60,120)",<NA>,<NA>,<NA>,NaN,NaN
48,friend_user_num_range,NaN,271016,32.6376,21.7504,1.4036,0.2790,NaN,<NA>,<NA>,<NA>,"[30,60)",<NA>,<NA>,<NA>,NaN,NaN
49,friend_user_num_range,NaN,226933,32.6894,21.5689,1.9781,0.3173,NaN,<NA>,<NA>,<NA>,"[120,250)",<NA>,<NA>,<NA>,NaN,NaN

In [56]:
# Profiling the main numeric fields to understand scale and sparsity

selected_numeric_fields = ["play_time_ms", "event_content_duration_ms", "playback_completion_rate", "profile_stay_time",
                           "comment_stay_time", "follow_user_num", "fans_user_num",
                           "friend_user_num", "register_days", "video_width", "video_height", "video_age_days"
]

numeric_field_profile = []

for field_name in selected_numeric_fields:
    series = impression_analysis_base[field_name]

    numeric_field_profile.append(
        {
            "field_name": field_name,
            "missing_count": int(series.isna().sum()),
            "missing_rate_percent": round(series.isna().mean() * 100, 4),
            "minimum_value": series.min(),
            "p01_value": series.quantile(0.01),
            "median_value": series.median(),
            "p99_value": series.quantile(0.99),
            "maximum_value": series.max(),
            "zero_value_rate_percent": round((series.fillna(0).eq(0)).mean() * 100, 4)
        }
    )

numeric_field_profile = pd.DataFrame(numeric_field_profile)
numeric_field_profile

                   field_name  missing_count  missing_rate_percent  minimum_value  p01_value  median_value  p99_value  maximum_value  zero_value_rate_percent
0                play_time_ms              0                0.0000            0.0        0.0   2865.000000  176995.02      1023809.0                   7.5694
1   event_content_duration_ms              0                0.0000            0.0        0.0  73566.000000  465041.00      1177720.0                   2.5322
2    playback_completion_rate          65778                2.5322            0.0        0.0      0.055252       1.00            1.0                   9.9019
3           profile_stay_time              0                0.0000            0.0        0.0      0.000000       0.00       300000.0                  99.9929
4           comment_stay_time              0                0.0000            0.0        0.0      0.000000    9727.04       300000.0                  96.6682
5             follow_user_num              0                0.0000            0.0        1.0    151.000000    3993.00         5003.0                   0.6674
6               fans_user_num              0                0.0000            0.0        0.0     55.000000    4109.00      1986249.0                   3.8694
7             friend_user_num              0                0.0000            0.0        0.0     18.000000    1581.00         4995.0                  11.5081
8               register_days              0                0.0000           14.0       47.0   1186.000000    2702.00         3624.0                   0.0000
9                 video_width              0                0.0000          270.0      720.0    720.000000    1280.00         2400.0                   0.0000
10               video_height              0                0.0000          448.0      720.0   1280.000000    1440.00         2400.0                   0.0000
11             video_age_days              0                0.0000            0.0        0.0     15.000000      29.00           29.0                   7.0454

In [57]:
# Checking simple numeric associations with click and high-value engagement
candidate_numeric_fields = ["follow_user_num", "fans_user_num", "friend_user_num", "register_days",
                            "event_content_duration_ms", "video_width", "video_height", "video_age_days"
]

candidate_numeric_association = []

for field_name in candidate_numeric_fields:
    valid_rows = impression_analysis_base[[field_name, "is_click", "is_high_value_engagement"]].dropna()

    candidate_numeric_association.append(
        {
            "field_name": field_name,
            "row_count_used": int(len(valid_rows)),
            "correlation_with_click": round(valid_rows[field_name].corr(valid_rows["is_click"]), 6),
            "correlation_with_high_value_engagement": round(
                valid_rows[field_name].corr(valid_rows["is_high_value_engagement"]),
                6
            )
        }
    )

candidate_numeric_association = (
    pd.DataFrame(candidate_numeric_association)
    .sort_values("correlation_with_click", key = lambda s: s.abs(), ascending = False)
    .reset_index(drop = True)
)

candidate_numeric_association

                  field_name  row_count_used  correlation_with_click  correlation_with_high_value_engagement
0             video_age_days         2597699               -0.237346                               -0.025258
1              register_days         2597699               -0.032549                               -0.012668
2               video_height         2597699               -0.024519                                0.000828
3  event_content_duration_ms         2597699               -0.011129                               -0.004228
4            friend_user_num         2597699               -0.010206                                0.001197
5            follow_user_num         2597699                0.003744                                0.021147
6                video_width         2597699               -0.000830                               -0.000073
7              fans_user_num         2597699               -0.000501                               -0.000539

In [58]:
# Measuring how video tags are relating to impression-level outcomes
video_tag_performance = (
    impression_analysis_base[
        [
            "video_id", "is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement"
        ]
    ]
    .merge(video_tag_bridge, on = "video_id", how = "inner")
    .groupby("video_tag", as_index = False)
    .agg(impression_count = ("video_id", "size"),
         distinct_video_count = ("video_id", "nunique"),
         click_rate_percent = ("is_click", lambda s: round(s.mean() * 100, 4)),
         meaningful_watch_rate_percent = ("is_meaningful_watch", lambda s: round(s.mean() * 100, 4)),
         social_engagement_rate_percent = ("is_social_engagement", lambda s: round(s.mean() * 100, 4)),
         high_value_engagement_rate_percent = ("is_high_value_engagement", lambda s: round(s.mean() * 100, 4))
    )
    .sort_values("impression_count", ascending = False)
    .reset_index(drop = True)
)

video_tag_performance.head(30)

   video_tag  impression_count  distinct_video_count  click_rate_percent  meaningful_watch_rate_percent  social_engagement_rate_percent  high_value_engagement_rate_percent
0         39            581755                  1446             39.6003                        26.8584                          1.2433                              0.2534
1          3            213848                   732             33.0267                        24.2738                          1.6086                              0.3362
2         12            212959                   606             30.7130                        19.1370                          0.9406                              0.2376
3          9            204384                   419             44.1458                        31.3782                          1.7859                              0.4247
4         20            170508                   675             25.1736                        16.2086                          1.9389                              0.3331
5          6            165654                   400             35.8718                        23.5165                          1.8895                              0.3495
6         68            119077                   428             31.2344                        18.8769                          1.1530                              0.1890
7         62            116579                   489             21.6248                        12.2990                          0.9093                              0.1964
8          7            109971                   383             29.3023                        18.8486                          1.2612                              0.1991
9         43            104551                   428             32.0418                        20.2064                          0.8914                              0.1884
10        17             91262                   220             40.4287                        29.7462                          1.6436                              0.2904
11         2             79711                   296             19.4415                         9.2998                          1.4665                              0.2823
12        15             76517                   245             30.9513                        21.8592                          1.2063                              0.2771
13        11             71706                   181             36.1518                        25.3577                          1.2858                              0.2413
14         1             64965                   254             19.8091                         9.0064                          1.1314                              0.1909
15        28             61895                   145             40.2827                        26.4642                          1.2909                              0.3167
16         8             57804                   177             23.5918                        13.4697                          2.8164                              0.3512
17         4             54910                   177             24.8243                        14.5493                          1.3076                              0.2586
18        25             47750                   136             33.9372                        23.0702                          1.3529                              0.2911
19        67             47254                   206             12.0286                         3.6738                          1.8686                              0.2095
20        60             38382                   144             24.7798                        14.1499                          0.8207                              0.1641
21        19             29754                    99             23.8422                        13.3293                          3.1525                              0.5142
22        18             29205                   102             28.5259                        17.9764                          0.9793                              0.2123
23         5             29112                   102             23.2962                        13.9736                          1.4564                              0.2611
24        26             28672                    82             21.2786                        11.4711                          3.0029                              0.3488
25        10             25304                    89             25.8971                        14.3495                          0.9248                              0.1857
26        29             19405                    35             45.6686                        34.3314                          1.2110                              0.3247
27        42             18690                    75             22.6378                        12.9856                          0.6742                              0.1819
28        27             16923                    58             23.4769                        14.3473                          0.9986                              0.2068
29        36             14061                    46             27.3736                        17.6801                          0.6899                              0.1636

In [59]:
# Testing whether music ID is analytically useful before excluding it

music_id_profile = pd.DataFrame(
    {
        "field_name": ["music_id"],
        "missing_count": [int(impression_fact["music_id"].isna().sum())],
        "missing_rate_percent": [round(impression_fact["music_id"].isna().mean() * 100, 4)],
        "distinct_value_count": [int(impression_fact["music_id"].nunique(dropna = False))],
        "top_value": [impression_fact["music_id"].value_counts(dropna = False).index[0]],
        "top_value_count": [int(impression_fact["music_id"].value_counts(dropna = False).iloc[0])]
    }
)

music_id_target_profile = (
    impression_fact
    .groupby("music_id", as_index = False)
    .agg(impression_count = ("user_id", "size"),
         click_rate_percent = ("is_click", lambda s: round(s.mean() * 100, 4)),
         meaningful_watch_rate_percent = ("is_meaningful_watch", lambda s: round(s.mean() * 100, 4)),
         social_engagement_rate_percent = ("is_social_engagement", lambda s: round(s.mean() * 100, 4)),
         high_value_engagement_rate_percent = ("is_high_value_engagement", lambda s: round(s.mean() * 100, 4))
    )
    .sort_values("impression_count", ascending = False)
    .head(20)
    .reset_index(drop = True)
)

display(music_id_profile)
display(music_id_target_profile)

  field_name  missing_count  missing_rate_percent  distinct_value_count  top_value  top_value_count
0   music_id              0                   0.0                  7202          0            81443

      music_id  impression_count  click_rate_percent  meaningful_watch_rate_percent  social_engagement_rate_percent  high_value_engagement_rate_percent
0            0             81443             37.2641                        25.6462                          1.3077                              0.2689
1   9152913689             10515             57.0043                        39.8859                          1.5407                              0.3233
2   9167116455              9911             60.8617                        50.2068                          3.9956                              0.6962
3   9139255224              7824             63.5225                        63.3308                          1.1247                              0.3579
4   6202189854              7769             48.3331                        43.0042                          0.6565                              0.2188
5   9141209460              6561             47.1574                        30.9252                          1.5242                              0.7011
6   9107419068              6211             28.5622                         9.6925                          1.8999                              0.3059
7   9155224806              5014             60.3311                        49.7407                          2.9318                              2.3933
8   9151301996              4975             54.4523                        42.8342                          3.5578                              0.7236
9   9143427573              4798             58.4827                        44.4977                          1.5006                              0.2501
10  9155443780              4721             49.8200                        30.0996                          0.9108                              0.3177
11  9159785535              4552             58.8533                        48.5281                          1.7135                              0.3735
12  9143725912              4480             59.3080                        53.5268                          1.3393                              0.2902
13  9143054632              4427             62.0736                        43.6187                          0.3840                              0.1129
14  9169685313              4384             48.6314                        37.8650                          1.3914                              0.4106
15  8862696427              4311             35.9777                        25.3769                          5.0568                              0.8119
16  9139455385              4287             45.6263                        36.1791                          1.2596                              0.3732
17  9153920360              4209             56.2604                        44.2861                          1.0691                              0.2376
18  9147430433              4049             36.9721                        21.6103                          1.9264                              0.4693
19  9168454214              4025             28.1491                        19.7516                          1.5652                              0.6708

In [60]:
# Preparing the leakage-safe base for click prediction work

click_model_base_columns = ["user_id", "video_id", "creator_user_id", "event_timestamp_ms", "traffic_source", "feed_tab_id",
                            "user_active_degree", "is_video_author", "follow_user_num", "follow_user_num_range", "fans_user_num",
                            "fans_user_num_range", "friend_user_num", "friend_user_num_range", "register_days", "register_days_range", 
                            "video_type", "video_upload_date", "video_upload_type", "video_width", "video_height", "video_orientation",
                            "music_type", "video_age_days", "is_click"
]

click_model_base = (impression_analysis_base[click_model_base_columns]
                    .sort_values(["event_timestamp_ms", "user_id", "video_id"])
                    .reset_index(drop = True)
)

pd.DataFrame(
    {
        "dataset_name": ["click_model_base"],
        "row_count": [len(click_model_base)],
        "column_count": [click_model_base.shape[1]],
        "duplicate_event_key_count": [
            int(click_model_base.duplicated(subset = ["user_id", "video_id", "event_timestamp_ms"]).sum())
        ],
        "missing_music_type_count": [int(click_model_base["music_type"].isna().sum())]
    }
)

       dataset_name  row_count  column_count  duplicate_event_key_count  missing_music_type_count
0  click_model_base    2597699            25                          0                     79102

In [61]:
# Saving the analysis-ready impression base for downstream use.
upload_dataframe_to_parquet_blob(impression_analysis_base,
                                 container_names["curated"],
                                 "impression_analysis_base.parquet"
)

pd.DataFrame(
    {
        "dataset_name": ["impression_analysis_base"],
        "row_count": [len(impression_analysis_base)],
        "column_count": [impression_analysis_base.shape[1]],
        "duplicate_event_key_count": 
            [
                int(impression_analysis_base.duplicated(
                        subset = ["user_id", "video_id", "event_timestamp_ms"]
                    ).sum()
                )
            ]
    }
)

               dataset_name  row_count  column_count  duplicate_event_key_count
0  impression_analysis_base    2597699            44                          0

In [62]:
# Saving the tag bridge for tag-level analysis and reporting
upload_dataframe_to_parquet_blob(video_tag_bridge, 
                                 container_names["curated"], 
                                 "video_tag_bridge.parquet"
)

pd.DataFrame(
    {
        "dataset_name": ["video_tag_bridge"],
        "row_count": [len(video_tag_bridge)],
        "column_count": [video_tag_bridge.shape[1]],
        "duplicate_row_count": [int(video_tag_bridge.duplicated().sum())]
    }
)

       dataset_name  row_count  column_count  duplicate_row_count
0  video_tag_bridge       9310             2                    0

In [63]:
# Verifying that the analysis base is complete and uniquely keyed

required_analysis_columns = ["user_id", "video_id", "event_timestamp_ms", "event_date", "traffic_source", "feed_tab_id",
                             "is_click", "is_meaningful_watch", "is_social_engagement", "is_high_value_engagement", "is_like",
                             "is_follow", "is_comment", "is_forward", "is_profile_enter", "user_active_degree",
                             "follow_user_num_range", "fans_user_num_range", "friend_user_num_range", "register_days_range",
                             "video_type", "video_upload_type", "video_orientation", "music_type", "video_age_days"
]

missing_analysis_columns = [column_name
                            for column_name in required_analysis_columns
                            if column_name not in impression_analysis_base.columns
]

if missing_analysis_columns:
    raise KeyError(f"Missing required analysis columns : {missing_analysis_columns}")

analysis_row_count = len(impression_analysis_base)
analysis_distinct_user_count = impression_analysis_base["user_id"].nunique()
analysis_distinct_video_count = impression_analysis_base["video_id"].nunique()

pd.DataFrame(
    {
        "metric_name": ["analysis_row_count", 
                        "analysis_distinct_user_count",
                        "analysis_distinct_video_count",
                        "duplicate_event_key_count"
        ],
        "value": [int(analysis_row_count),
                  int(analysis_distinct_user_count),
                  int(analysis_distinct_video_count),
                  int(impression_analysis_base.duplicated(
                        subset = ["user_id", "video_id", "event_timestamp_ms"]
                    ).sum()
                )
        ]
    }
)

                     metric_name    value
0             analysis_row_count  2597699
1   analysis_distinct_user_count    27285
2  analysis_distinct_video_count     7583
3      duplicate_event_key_count        0

In [64]:
# Summarizing the overall impression-to-engagement outcome rates

overall_funnel_summary = pd.DataFrame(
    {
        "funnel_stage": ["impressions", 
                         "clicks",
                         "meaningful_watches",
                         "profile_enters",
                         "likes",
                         "high_value_engagements",
                         "comments",
                         "follows",
                         "forwards"
        ],
        "event_count": [int(len(impression_analysis_base)),
                        int(impression_analysis_base["is_click"].sum()),
                        int(impression_analysis_base["is_meaningful_watch"].sum()),
                        int(impression_analysis_base["is_profile_enter"].sum()),
                        int(impression_analysis_base["is_like"].sum()),
                        int(impression_analysis_base["is_high_value_engagement"].sum()),
                        int(impression_analysis_base["is_comment"].sum()),
                        int(impression_analysis_base["is_follow"].sum()),
                        int(impression_analysis_base["is_forward"].sum())
        ]
    }
)

overall_funnel_summary["rate_from_impressions_percent"] = (
    overall_funnel_summary["event_count"] / len(impression_analysis_base) * 100
).round(4)

overall_funnel_summary

             funnel_stage  event_count  rate_from_impressions_percent
0             impressions      2597699                       100.0000
1                  clicks       864730                        33.2883
2      meaningful_watches       575167                        22.1414
3          profile_enters        40915                         1.5750
4                   likes        32039                         1.2334
5  high_value_engagements         7575                         0.2916
6                comments         4041                         0.1556
7                 follows         1821                         0.0701
8                forwards         1776                         0.0684

In [65]:
# Building reusable grouped funnel summaries for comparison views

def build_funnel_summary(dataframe, group_columns):
    grouped_summary = (
        dataframe.groupby(group_columns, dropna = False, as_index = False)
        .agg(impression_count = ("user_id", "size"),
             click_count = ("is_click", "sum"),
             meaningful_watch_count = ("is_meaningful_watch", "sum"),
             profile_enter_count = ("is_profile_enter", "sum"),
             like_count = ("is_like", "sum"),
             high_value_engagement_count = ("is_high_value_engagement", "sum"),
             comment_count = ("is_comment", "sum"),
             follow_count = ("is_follow", "sum"),
             forward_count = ("is_forward", "sum")
        )
    )

    # Converting grouped counts into comparable impression-level rates
    grouped_summary["click_rate_percent"] = (
        grouped_summary["click_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["meaningful_watch_rate_percent"] = (
        grouped_summary["meaningful_watch_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["profile_enter_rate_percent"] = (
        grouped_summary["profile_enter_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["like_rate_percent"] = (
        grouped_summary["like_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["high_value_engagement_rate_percent"] = (
        grouped_summary["high_value_engagement_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["comment_rate_percent"] = (
        grouped_summary["comment_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["follow_rate_percent"] = (
        grouped_summary["follow_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    grouped_summary["forward_rate_percent"] = (
        grouped_summary["forward_count"] / grouped_summary["impression_count"] * 100
    ).round(4)

    return grouped_summary.sort_values("impression_count", ascending = False).reset_index(drop = True)


traffic_source_funnel_summary = build_funnel_summary(
    impression_analysis_base,
    ["traffic_source"]
)

feed_tab_funnel_summary = build_funnel_summary(
    impression_analysis_base,
    ["feed_tab_id"]
)

display(traffic_source_funnel_summary)
display(feed_tab_funnel_summary)

,traffic_source,impression_count,click_count,meaningful_watch_count,profile_enter_count,like_count,high_value_engagement_count,comment_count,follow_count,forward_count,click_rate_percent,meaningful_watch_rate_percent,profile_enter_rate_percent,like_rate_percent,high_value_engagement_rate_percent,comment_rate_percent,follow_rate_percent,forward_rate_percent
0,standard,1411650,655796,474398,34318,26348,6458,3630,1511,1374,46.456,33.6059,2.4311,1.8665,0.4575,0.2571,0.1070,0.0973
1,random,1186049,208934,100769,6597,5691,1117,411,310,402,17.616,8.4962,0.5562,0.4798,0.0942,0.0347,0.0261,0.0339

,feed_tab_id,impression_count,click_count,meaningful_watch_count,profile_enter_count,like_count,high_value_engagement_count,comment_count,follow_count,forward_count,click_rate_percent,meaningful_watch_rate_percent,profile_enter_rate_percent,like_rate_percent,high_value_engagement_rate_percent,comment_rate_percent,follow_rate_percent,forward_rate_percent
0,1,2236411,762389,501456,35685,28596,6710,3574,1599,1597,34.0898,22.4224,1.5956,1.2787,0.3000,0.1598,0.0715,0.0714
1,0,177846,16155,7329,1225,711,213,126,54,35,9.0837,4.1210,0.6888,0.3998,0.1198,0.0708,0.0304,0.0197
2,4,93165,57343,45023,2720,1540,258,179,40,39,61.5499,48.3261,2.9196,1.6530,0.2769,0.1921,0.0429,0.0419
3,2,49128,23305,18308,1138,945,319,136,88,95,47.4373,37.2659,2.3164,1.9235,0.6493,0.2768,0.1791,0.1934
4,6,20236,3589,1795,122,160,54,21,27,7,17.7357,8.8703,0.6029,0.7907,0.2669,0.1038,0.1334,0.0346
5,11,7470,0,254,0,23,5,0,5,0,0.0000,3.4003,0.0000,0.3079,0.0669,0.0000,0.0669,0.0000
6,3,4008,90,16,2,3,1,1,0,0,2.2455,0.3992,0.0499,0.0749,0.0250,0.0250,0.0000,0.0000
7,8,3909,160,74,0,4,0,0,0,0,4.0931,1.8931,0.0000,0.1023,0.0000,0.0000,0.0000,0.0000
8,5,2009,564,342,20,22,10,3,4,3,28.0737,17.0234,0.9955,1.0951,0.4978,0.1493,0.1991,0.1493
9,12,1472,200,151,0,6,1,0,1,0,13.5870,10.2582,0.0000,0.4076,0.0679,0.0000,0.0679,0.0000
10,14,546,0,39,0,3,0,0,0,0,0.0000,7.1429,0.0000,0.5495,0.0000,0.0000,0.0000,0.0000
11,7,504,203,104,0,17,3,1,2,0,40.2778,20.6349,0.0000,3.3730,0.5952,0.1984,0.3968,0.0000
12,9,444,441,79,2,5,1,0,1,0,99.3243,17.7928,0.4505,1.1261,0.2252,0.0000,0.2252,0.0000
13,13,399,139,101,0,1,0,0,0,0,34.8371,25.3133,0.0000,0.2506,0.0000,0.0000,0.0000,0.0000
14,10,152,152,96,1,3,0,0,0,0,100.0000,63.1579,0.6579,1.9737,0.0000,0.0000,0.0000,0.0000

In [66]:
# Comparing funnel outcomes across key user and content segments

segment_fields = ["user_active_degree", "follow_user_num_range", "fans_user_num_range", "friend_user_num_range",
                  "register_days_range", "video_type", "video_upload_type", "video_orientation", "music_type"
]

segment_funnel_summary_list = []

for field_name in segment_fields:
    segment_summary = build_funnel_summary(
        impression_analysis_base,
        [field_name]
    )
    segment_summary.insert(0, "segment_field", field_name)
    segment_funnel_summary_list.append(segment_summary)

segment_funnel_summary = pd.concat(segment_funnel_summary_list, ignore_index = True)

segment_funnel_summary.head(100)

,segment_field,user_active_degree,impression_count,click_count,meaningful_watch_count,profile_enter_count,like_count,high_value_engagement_count,comment_count,follow_count,forward_count,click_rate_percent,meaningful_watch_rate_percent,profile_enter_rate_percent,like_rate_percent,high_value_engagement_rate_percent,comment_rate_percent,follow_rate_percent,forward_rate_percent,follow_user_num_range,fans_user_num_range,friend_user_num_range,register_days_range,video_type,video_upload_type,video_orientation,music_type
0,user_active_degree,full_active,1889845,612323,406125,29569,20175,5049,2856,1041,1198,32.4007,21.4899,1.5646,1.0675,0.2672,0.1511,0.0551,0.0634,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
1,user_active_degree,high_active,462463,161878,108521,7179,7407,1558,682,532,356,35.0034,23.4659,1.5523,1.6016,0.3369,0.1475,0.1150,0.0770,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
2,user_active_degree,middle_active,166902,62070,41276,2869,3331,697,351,183,167,37.1895,24.7307,1.7190,1.9958,0.4176,0.2103,0.1096,0.1001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
3,user_active_degree,2_14_day_new,55735,19759,13355,898,703,171,97,37,38,35.4517,23.9616,1.6112,1.2613,0.3068,0.1740,0.0664,0.0682,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
4,user_active_degree,low_active,15407,5932,3948,249,321,62,35,14,13,38.5020,25.6247,1.6161,2.0835,0.4024,0.2272,0.0909,0.0844,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
5,user_active_degree,single_low_active,4481,1799,1313,93,78,24,10,10,4,40.1473,29.3015,2.0754,1.7407,0.5356,0.2232,0.2232,0.0893,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
6,user_active_degree,30day_retention,1228,418,269,32,10,9,8,1,0,34.0391,21.9055,2.6059,0.8143,0.7329,0.6515,0.0814,0.0000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
7,user_active_degree,day_new,1111,437,300,23,13,5,2,3,0,39.3339,27.0027,2.0702,1.1701,0.4500,0.1800,0.2700,0.0000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
8,user_active_degree,UNKNOWN,527,114,60,3,1,0,0,0,0,21.6319,11.3852,0.5693,0.1898,0.0000,0.0000,0.0000,0.0000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
9,follow_user_num_range,<NA>,537421,182101,121245,8874,10768,2378,908,941,563,33.8842,22.5605,1.6512,2.0036,0.4425,0.1690,0.1751,0.1048,500+,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
10,follow_user_num_range,<NA>,479351,159907,106600,7220,3436,1123,705,134,288,33.3591,22.2384,1.5062,0.7168,0.2343,0.1471,0.0280,0.0601,"(10,50]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
11,follow_user_num_range,<NA>,411614,136314,90412,6681,5730,1235,701,301,242,33.1169,21.9652,1.6231,1.3921,0.3000,0.1703,0.0731,0.0588,"(250,500]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
12,follow_user_num_range,<NA>,388119,129245,86445,6224,3575,866,519,134,218,33.3004,22.2728,1.6036,0.9211,0.2231,0.1337,0.0345,0.0562,"(50,100]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
13,follow_user_num_range,<NA>,349969,117079,77953,5722,4653,1013,590,173,256,33.4541,22.2743,1.6350,1.3295,0.2895,0.1686,0.0494,0.0731,"(150,250]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
14,follow_user_num_range,<NA>,252544,84162,56004,3830,2901,657,418,114,129,33.3257,22.1759,1.5166,1.1487,0.2602,0.1655,0.0451,0.0511,"(100,150]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
15,follow_user_num_range,<NA>,161343,50647,33031,2101,943,285,195,19,72,31.3909,20.4725,1.3022,0.5845,0.1766,0.1209,0.0118,0.0446,"(0,10]",<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
16,follow_user_num_range,<NA>,17338,5275,3477,263,33,18,5,5,8,30.4245,20.0542,1.5169,0.1903,0.1038,0.0288,0.0288,0.0461,0,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
17,fans_user_num_range,<NA>,991288,332748,222162,14557,11338,3011,1558,764,718,33.5672,22.4114,1.4685,1.1438,0.3037,0.1572,0.0771,0.0724,<NA>,"[10,100)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
18,fans_user_num_range,<NA>,875764,285624,189124,15539,12972,2647,1516,503,648,32.6143,21.5953,1.7743,1.4812,0.3023,0.1731,0.0574,0.0740,<NA>,"[100,1k)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
19,fans_user_num_range,<NA>,467709,161395,108206,6626,4642,1253,584,396,279,34.5076,23.1353,1.4167,0.9925,0.2679,0.1249,0.0847,0.0597,<NA>,"[1,10)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
20,fans_user_num_range,<NA>,144442,45557,29496,2594,2287,429,274,68,93,31.5400,20.4207,1.7959,1.5833,0.2970,0.1897,0.0471,0.0644,<NA>,"[1k,5k)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
21,fans_user_num_range,<NA>,100515,33904,22538,1312,555,197,83,85,31,33.7303,22.4225,1.3053,0.5522,0.1960,0.0826,0.0846,0.0308,<NA>,0,<NA>,<NA>,<NA>,<NA>,NaN,NaN
22,fans_user_num_range,<NA>,9102,2665,1761,113,99,18,14,3,1,29.2793,19.3474,1.2415,1.0877,0.1978,0.1538,0.0330,0.0110,<NA>,"[5k,1w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
23,fans_user_num_range,<NA>,7871,2483,1627,137,84,18,11,2,5,31.5462,20.6708,1.7406,1.0672,0.2287,0.1398,0.0254,0.0635,<NA>,"[1w,10w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
24,fans_user_num_range,<NA>,911,315,221,27,56,2,1,0,1,34.5774,24.2591,2.9638,6.1471,0.2195,0.1098,0.0000,0.1098,<NA>,"[10w,100w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
25,fans_user_num_range,<NA>,97,39,32,10,6,0,0,0,0,40.2062,32.9897,10.3093,6.1856,0.0000,0.0000,0.0000,0.0000,<NA>,"[100w,1000w)",<NA>,<NA>,<NA>,<NA>,NaN,NaN
26,friend_user_num_range,<NA>,726049,244243,163214,11142,8433,2195,1153,532,530,33.6400,22.4797,1.5346,1.1615,0.3023,0.1588,0.0733,0.0730,<NA>,<NA>,"[5,30)",<NA>,<NA>,<NA>,NaN,NaN
27,friend_user_num_range,<NA>,478219,161815,108569,6734,4756,1318,644,396,288,33.8370,22.7028,1.4081,0.9945,0.2756,0.1347,0.0828,0.0602,<NA>,<NA>,"[1,5)",<NA>,<NA>,<NA>,NaN,NaN
28,friend_user_num_range,<NA>,324869,106565,69109,5792,5654,1103,619,196,297,32.8025,21.2729,1.7829,1.7404,0.3395,0.1905,0.0603,0.0914,<NA>,<NA>,250+,<NA>,<NA>,<NA>,NaN,NaN
29,friend_user_num_range,<NA>,298947,100094,66664,4089,1691,654,328,198,131,33.4822,22.2996,1.3678,0.5657,0.2188,0.1097,0.0662,0.0438,<NA>,<NA>,0,<NA>,<NA>,<NA>,NaN,NaN
30,friend_user_num_range,<NA>,271666,89377,59717,4859,4321,829,498,168,172,32.8996,21.9818,1.7886,1.5906,0.3052,0.1833,0.0618,0.0633,<NA>,<NA>,"[60,120)",<NA>,<NA>,<NA>,NaN,NaN
31,friend_user_num_range,<NA>,271016,88453,58947,4382,3246,756,392,195,173,32.6376,21.7504,1.6169,1.1977,0.2790,0.1446,0.0720,0.0638,<NA>,<NA>,"[30,60)",<NA>,<NA>,<NA>,NaN,NaN
32,friend_user_num_range,<NA>,226933,74183,48947,3917,3938,720,407,136,185,32.6894,21.5689,1.7261,1.7353,0.3173,0.1793,0.0599,0.0815,<NA>,<NA>,"[120,250)",<NA>,<NA>,<NA>,NaN,NaN
33,register_days_range,<NA>,1909229,616458,408778,29733,20359,4861,2655,1032,1211,32.2883,21.4106,1.5573,1.0663,0.2546,0.1391,0.0541,0.0634,<NA>,<NA>,<NA>,730+,<NA>,<NA>,NaN,NaN
34,register_days_range,<NA>,334336,118972,79376,5591,5318,1153,646,283,232,35.5846,23.7414,1.6723,1.5906,0.3449,0.1932,0.0846,0.0694,<NA>,<NA>,<NA>,366-730,<NA>,<NA>,NaN,NaN
35,register_days_range,<NA>,179607,66080,44589,2968,3537,786,399,233,162,36.7914,24.8259,1.6525,1.9693,0.4376,0.2222,0.1297,0.0902,<NA>,<NA>,<NA>,181-365,<NA>,<NA>,NaN,NaN
36,register_days_range,<NA>,97700,35201,23723,1503,1593,440,216,143,88,36.0297,24.2815,1.5384,1.6305,0.4504,0.2211,0.1464,0.0901,<NA>,<NA>,<NA>,91-180,<NA>,<NA>,NaN,NaN
37,register_days_range,<NA>,34847,12751,8560,510,467,141,68,41,34,36.5914,24.5645,1.4635,1.3401,0.4046,0.1951,0.1177,0.0976,<NA>,<NA>,<NA>,61-90,<NA>,<NA>,NaN,NaN
38,register_days_range,<NA>,32011,11945,8084,501,630,153,46,73,35,37.3153,25.2538,1.5651,1.9681,0.4780,0.1437,0.2280,0.1093,<NA>,<NA>,<NA>,31-60,<NA>,<NA>,NaN,NaN
39,register_days_range,<NA>,9946,3313,2048,108,129,41,11,16,14,33.3099,20.5912,1.0859,1.2970,0.4122,0.1106,0.1609,0.1408,<NA>,<NA>,<NA>,15-30,<NA>,<NA>,NaN,NaN
40,register_days_range,<NA>,23,10,9,1,6,0,0,0,0,43.4783,39.1304,4.3478,26.0870,0.0000,0.0000,0.0000,0.0000,<NA>,<NA>,<NA>,8-14,<NA>,<NA>,NaN,NaN
41,video_type,<NA>,2568173,853990,567552,40168,31678,7474,3986,1791,1757,33.2528,22.0994,1.5641,1.2335,0.2910,0.1552,0.0697,0.0684,<NA>,<NA>,<NA>,<NA>,NORMAL,<NA>,NaN,NaN
42,video_type,<NA>,27185,9489,6616,648,346,98,53,30,18,34.9053,24.3370,2.3837,1.2728,0.3605,0.1950,0.1104,0.0662,<NA>,<NA>,<NA>,<NA>,AD,<NA>,NaN,NaN
43,video_type,<NA>,2341,1251,999,99,15,3,2,0,1,53.4387,42.6741,4.2290,0.6408,0.1282,0.0854,0.0000,0.0427,<NA>,<NA>,<NA>,<NA>,UNKNOWN,<NA>,NaN,NaN
44,video_upload_type,<NA>,1070378,375385,251984,18131,12897,3221,1765,745,739,35.0703,23.5416,1.6939,1.2049,0.3009,0.1649,0.0696,0.0690,<NA>,<NA>,<NA>,<NA>,<NA>,LongImport,NaN,NaN
45,video_upload_type,<NA>,800372,280368,189258,13313,8546,2292,1161,615,536,35.0297,23.6463,1.6634,1.0678,0.2864,0.1451,0.0768,0.0670,<NA>,<NA>,<NA>,<NA>,<NA>,Web,NaN,NaN
46,video_upload_type,<NA>,344584,108113,73387,4802,6458,1137,676,243,225,31.3749,21.2973,1.3936,1.8741,0.3300,0.1962,0.0705,0.0653,<NA>,<NA>,<NA>,<NA>,<NA>,ShortImport,NaN,NaN
47,video_upload_type,<NA>,254400,74991,47277,2976,2273,575,272,142,166,29.4776,18.5837,1.1698,0.8935,0.2260,0.1069,0.0558,0.0653,<NA>,<NA>,<NA>,<NA>,<NA>,Kmovie,NaN,NaN
48,video_upload_type,<NA>,43145,6700,2069,419,1043,149,68,17,64,15.5290,4.7955,0.9711,2.4174,0.3453,0.1576,0.0394,0.1483,<NA>,<NA>,<NA>,<NA>,<NA>,LongPicture,NaN,NaN
49,video_upload_type,<NA>,29547,9777,6747,664,357,109,59,33,20,33.0897,22.8348,2.2473,1.2082,0.3689,0.1997,0.1117,0.0677,<NA>,<NA>,<NA>,<NA>,<NA>,UNKNOWN,NaN,NaN
50,video_upload_type,<NA>,15600,1514,470,100,157,22,7,7,8,9.7051,3.0128,0.6410,1.0064,0.1410,0.0449,0.0449,0.0513,<NA>,<NA>,<NA>,<NA>,<NA>,PictureSet,NaN,NaN
51,video_upload_type,<NA>,14382,2719,1114,261,147,29,20,4,5,18.9056,7.7458,1.8148,1.0221,0.2016,0.1391,0.0278,0.0348,<NA>,<NA>,<NA>,<NA>,<NA>,ShortCamera,NaN,NaN
52,video_upload_type,<NA>,14079,2483,1278,68,88,18,8,6,4,17.6362,9.0773,0.4830,0.6250,0.1278,0.0568,0.0426,0.0284,<NA>,<NA>,<NA>,<NA>,<NA>,LongCamera,NaN,NaN
53,video_upload_type,<NA>,8777,2416,1492,169,70,19,5,6,8,27.5265,16.9990,1.9255,0.7975,0.2165,0.0570,0.0684,0.0911,<NA>,<NA>,<NA>,<NA>,<NA>,ShareFromOtherApp,NaN,NaN
54,video_upload_type,<NA>,1773,192,68,9,1,2,0,2,0,10.8291,3.8353,0.5076,0.0564,0.1128,0.0000,0.1128,0.0000,<NA>,<NA>,<NA>,<NA>,<NA>,FollowShoot,NaN,NaN
55,video_upload_type,<NA>,340,47,16,1,0,0,0,0,0,13.8235,4.7059,0.2941,0.0000,0.0000,0.0000,0.0000,0.0000,<NA>,<NA>,<NA>,<NA>,<NA>,AiCutVideo,NaN,NaN
56,video_upload_type,<NA>,165,15,3,1,2,2,0,1,1,9.0909,1.8182,0.6061,1.2121,1.2121,0.0000,0.6061,0.6061,<NA>,<NA>,<NA>,<NA>,<NA>,LipsSync,NaN,NaN
57,video_upload_type,<NA>,157,10,4,1,0,0,0,0,0,6.3694,2.5478,0.6369,0.0000,0.0000,0.0000,0.0000,0.0000,<NA>,<NA>,<NA>,<NA>,<NA>,PhotoCopy,NaN,NaN
58,video_orientation,<NA>,1959315,643815,427614,29721,22972,5729,3074,1365,1339,32.8592,21.8247,1.5169,1.1725,0.2924,0.1569,0.0697,0.0683,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,vertical,NaN
59,video_orientation,<NA>,600056,210546,141479,10647,7840,1688,882,428,390,35.0877,23.5776,1.7743,1.3065,0.2813,0.1470,0.0713,0.0650,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,horizontal,NaN
60,video_orientation,<NA>,38328,10369,6074,547,1227,158,85,28,47,27.0533,15.8474,1.4272,3.2013,0.4122,0.2218,0.0731,0.1226,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,square,NaN
61,music_type,<NA>,2292634,777348,519853,37057,27826,6782,3602,1631,1606,33.9063,22.6749,1.6164,1.2137,0.2958,0.1571,0.0711,0.0701,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,9.0
62,music_type,<NA>,212288,55494,33968,2494,3204,539,291,133,118,26.1409,16.0009,1.1748,1.5093,0.2539,0.1371,0.0627,0.0556,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,4.0
63,music_type,<NA>,79102,29098,19888,1218,875,216,130,48,41,36.7854,25.1422,1.5398,1.1062,0.2731,0.1643,0.0607,0.0518,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
64,music_type,<NA>,9517,1837,971,101,57,20,6,6,8,19.3023,10.2028,1.0613,0.5989,0.2102,0.0630,0.0630,0.0841,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,8.0
65,music_type,<NA>,2991,688,372,28,19,7,4,1,2,23.0023,12.4373,0.9361,0.6352,0.2340,0.1337,0.0334,0.0669,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,7.0
66,music_type,<NA>,1167,265,115,17,58,11,8,2,1,22.7078,9.8543,1.4567,4.9700,0.9426,0.6855,0.1714,0.0857,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,11.0

In [67]:
# Measuring what clicked impressions are converting into next

clicked_impressions = impression_analysis_base.loc[
    impression_analysis_base["is_click"] == 1
].copy()

post_click_conversion_summary = pd.DataFrame(
    {
        "conversion_name": ["click_to_meaningful_watch",
                            "click_to_profile_enter",
                            "click_to_like",
                            "click_to_high_value_engagement",
                            "click_to_comment",
                            "click_to_follow",
                            "click_to_forward"
        ],
        "converted_count": [int(clicked_impressions["is_meaningful_watch"].sum()),
                            int(clicked_impressions["is_profile_enter"].sum()),
                            int(clicked_impressions["is_like"].sum()),
                            int(clicked_impressions["is_high_value_engagement"].sum()),
                            int(clicked_impressions["is_comment"].sum()),
                            int(clicked_impressions["is_follow"].sum()),
                            int(clicked_impressions["is_forward"].sum())
        ]
    }
)

post_click_conversion_summary["clicked_impression_count"] = int(len(clicked_impressions))
post_click_conversion_summary["conversion_rate_percent"] = (
    post_click_conversion_summary["converted_count"] / len(clicked_impressions) * 100
).round(4)

post_click_conversion_summary

                  conversion_name  converted_count  clicked_impression_count  conversion_rate_percent
0       click_to_meaningful_watch           572884                    864730                  66.2500
1          click_to_profile_enter            36707                    864730                   4.2449
2                   click_to_like            25764                    864730                   2.9794
3  click_to_high_value_engagement             6942                    864730                   0.8028
4                click_to_comment             3926                    864730                   0.4540
5                 click_to_follow             1574                    864730                   0.1820
6                click_to_forward             1504                    864730                   0.1739

In [68]:
# Tracking daily movement in core engagement rates

post_click_conversion_by_traffic_source = (
    clicked_impressions
    .groupby("traffic_source", as_index = False)
    .agg(clicked_impression_count = ("user_id", "size"),
         meaningful_watch_count = ("is_meaningful_watch", "sum"),
         profile_enter_count = ("is_profile_enter", "sum"),
         like_count = ("is_like", "sum"),
         high_value_engagement_count = ("is_high_value_engagement", "sum"),
         comment_count = ("is_comment", "sum"),follow_count = ("is_follow", "sum"),
         forward_count = ("is_forward", "sum")
    )
)

post_click_conversion_by_traffic_source["click_to_meaningful_watch_rate_percent"] = (
    post_click_conversion_by_traffic_source["meaningful_watch_count"] 
    / post_click_conversion_by_traffic_source["clicked_impression_count"] 
    * 100
).round(4)

post_click_conversion_by_traffic_source["click_to_profile_enter_rate_percent"] = (
    post_click_conversion_by_traffic_source["profile_enter_count"] 
    / post_click_conversion_by_traffic_source["clicked_impression_count"] 
    * 100
).round(4)

post_click_conversion_by_traffic_source["click_to_like_rate_percent"] = (
    post_click_conversion_by_traffic_source["like_count"]
    / post_click_conversion_by_traffic_source["clicked_impression_count"]
    * 100
).round(4)

post_click_conversion_by_traffic_source["click_to_high_value_engagement_rate_percent"] = (
    post_click_conversion_by_traffic_source["high_value_engagement_count"]
    / post_click_conversion_by_traffic_source["clicked_impression_count"]
    * 100
).round(4)

post_click_conversion_by_traffic_source["click_to_comment_rate_percent"] = (
    post_click_conversion_by_traffic_source["comment_count"]
    / post_click_conversion_by_traffic_source["clicked_impression_count"]
    * 100
).round(4)

post_click_conversion_by_traffic_source["click_to_follow_rate_percent"] = (
    post_click_conversion_by_traffic_source["follow_count"]
    / post_click_conversion_by_traffic_source["clicked_impression_count"]
    * 100
).round(4)

post_click_conversion_by_traffic_source["click_to_forward_rate_percent"] = (
    post_click_conversion_by_traffic_source["forward_count"]
    / post_click_conversion_by_traffic_source["clicked_impression_count"]
    * 100
).round(4)

post_click_conversion_by_traffic_source

,traffic_source,clicked_impression_count,meaningful_watch_count,profile_enter_count,like_count,high_value_engagement_count,comment_count,follow_count,forward_count,click_to_meaningful_watch_rate_percent,click_to_profile_enter_rate_percent,click_to_like_rate_percent,click_to_high_value_engagement_rate_percent,click_to_comment_rate_percent,click_to_follow_rate_percent,click_to_forward_rate_percent
0,random,208934,100404,4284,3482,909,397,230,287,48.0554,2.0504,1.6666,0.4351,0.1900,0.1101,0.1374
1,standard,655796,472480,32423,22282,6033,3529,1344,1217,72.0468,4.9441,3.3977,0.9200,0.5381,0.2049,0.1856

In [69]:
# Tracking daily movement in core engagement rates

daily_funnel_summary = (impression_analysis_base
                        .groupby("event_date", as_index = False)
                        .agg(impression_count = ("user_id", "size"),
                             click_count = ("is_click", "sum"),
                             meaningful_watch_count = ("is_meaningful_watch", "sum"),
                             social_engagement_count = ("is_social_engagement", "sum"),
                             high_value_engagement_count = ("is_high_value_engagement", "sum")
    )
    .sort_values("event_date")
    .reset_index(drop = True)
)

daily_funnel_summary["click_rate_percent"] = (
    daily_funnel_summary["click_count"] / daily_funnel_summary["impression_count"] * 100
).round(4)

daily_funnel_summary["meaningful_watch_rate_percent"] = (
    daily_funnel_summary["meaningful_watch_count"] / daily_funnel_summary["impression_count"] * 100
).round(4)

daily_funnel_summary["social_engagement_rate_percent"] = (
    daily_funnel_summary["social_engagement_count"] / daily_funnel_summary["impression_count"] * 100
).round(4)

daily_funnel_summary["high_value_engagement_rate_percent"] = (
    daily_funnel_summary["high_value_engagement_count"] / daily_funnel_summary["impression_count"] * 100
).round(4)

daily_funnel_summary

,event_date,impression_count,click_count,meaningful_watch_count,social_engagement_count,high_value_engagement_count,click_rate_percent,meaningful_watch_rate_percent,social_engagement_rate_percent,high_value_engagement_rate_percent
0,2022-04-09,52390,23510,17697,1084,213,44.8750,33.7793,2.0691,0.4066
1,2022-04-10,226043,106015,77428,5061,963,46.9004,34.2537,2.2390,0.4260
2,2022-04-11,275743,127042,92548,5865,1252,46.0726,33.5631,2.1270,0.4540
3,2022-04-12,162146,75021,54832,3521,762,46.2676,33.8164,2.1715,0.4699
4,2022-04-13,91714,41651,29785,2034,426,45.4140,32.4760,2.2178,0.4645
5,2022-04-14,68971,31551,22601,1497,331,45.7453,32.7688,2.1705,0.4799
6,2022-04-15,58239,29413,21320,1570,299,50.5040,36.6078,2.6958,0.5134
7,2022-04-16,60538,31308,22910,1710,301,51.7163,37.8440,2.8247,0.4972
8,2022-04-17,43567,21757,15970,1103,208,49.9392,36.6562,2.5317,0.4774
9,2022-04-18,24140,11259,8092,499,108,46.6404,33.5211,2.0671,0.4474
10,2022-04-19,19973,9150,6578,447,85,45.8118,32.9345,2.2380,0.4256
11,2022-04-20,20402,9002,6449,434,105,44.1231,31.6096,2.1272,0.5147
12,2022-04-21,19695,8846,6262,408,87,44.9150,31.7949,2.0716,0.4417
13,2022-04-22,46665,14196,9081,654,104,30.4211,19.4600,1.4015,0.2229
14,2022-04-23,78681,21626,13485,931,164,27.4857,17.1388,1.1833,0.2084
15,2022-04-24,62374,15296,9033,587,120,24.5230,14.4820,0.9411,0.1924
16,2022-04-25,56478,13363,7883,525,98,23.6605,13.9576,0.9296,0.1735
17,2022-04-26,56492,13154,7781,492,102,23.2847,13.7736,0.8709,0.1806
18,2022-04-27,55496,12876,7602,494,112,23.2017,13.6983,0.8902,0.2018
19,2022-04-28,54141,12529,7218,501,103,23.1414,13.3319,0.9254,0.1902
20,2022-04-29,64787,15146,8705,573,98,23.3781,13.4363,0.8844,0.1513
21,2022-04-30,83174,20399,11960,845,148,24.5257,14.3795,1.0159,0.1779
22,2022-05-01,82230,19914,11581,773,148,24.2174,14.0837,0.9400,0.1800
23,2022-05-02,104988,23981,13444,946,173,22.8417,12.8053,0.9011,0.1648
24,2022-05-03,128154,28466,15737,1035,205,22.2123,12.2798,0.8076,0.1600
25,2022-05-04,125716,27554,15016,952,166,21.9177,11.9444,0.7573,0.1320
26,2022-05-05,110247,23198,12464,749,163,21.0418,11.3055,0.6794,0.1478
27,2022-05-06,116790,24884,13449,822,157,21.3066,11.5155,0.7038,0.1344
28,2022-05-07,117343,24843,13275,844,178,21.1713,11.3130,0.7193,0.1517
29,2022-05-08,130382,27780,14981,1067,196,21.3066,11.4901,0.8184,0.1503

In [70]:
# Breaking daily performance by traffic source mix
daily_traffic_source_summary = (impression_analysis_base
                                .groupby(["event_date", "traffic_source"], as_index = False)
                                .agg(impression_count = ("user_id", "size"),
                                     click_count = ("is_click", "sum"),
                                     meaningful_watch_count = ("is_meaningful_watch", "sum"),
                                     social_engagement_count = ("is_social_engagement", "sum"),
                                     high_value_engagement_count = ("is_high_value_engagement", "sum")
    )
    .sort_values(["event_date", "traffic_source"])
    .reset_index(drop = True)
)

daily_traffic_source_summary["traffic_source_share_of_day_percent"] = (
    daily_traffic_source_summary["impression_count"]
    / daily_traffic_source_summary.groupby("event_date")["impression_count"].transform("sum")
    * 100
).round(4)

daily_traffic_source_summary["click_rate_percent"] = (
    daily_traffic_source_summary["click_count"]
    / daily_traffic_source_summary["impression_count"]
    * 100
).round(4)

daily_traffic_source_summary["meaningful_watch_rate_percent"] = (
    daily_traffic_source_summary["meaningful_watch_count"]
    / daily_traffic_source_summary["impression_count"]
    * 100
).round(4)

daily_traffic_source_summary["social_engagement_rate_percent"] = (
    daily_traffic_source_summary["social_engagement_count"]
    / daily_traffic_source_summary["impression_count"]
    * 100
).round(4)

daily_traffic_source_summary["high_value_engagement_rate_percent"] = (
    daily_traffic_source_summary["high_value_engagement_count"]
    / daily_traffic_source_summary["impression_count"]
    * 100
).round(4)

daily_traffic_source_summary

,event_date,traffic_source,impression_count,click_count,meaningful_watch_count,social_engagement_count,high_value_engagement_count,traffic_source_share_of_day_percent,click_rate_percent,meaningful_watch_rate_percent,social_engagement_rate_percent,high_value_engagement_rate_percent
0,2022-04-09,standard,52390,23510,17697,1084,213,100.0000,44.8750,33.7793,2.0691,0.4066
1,2022-04-10,standard,226043,106015,77428,5061,963,100.0000,46.9004,34.2537,2.2390,0.4260
2,2022-04-11,standard,275743,127042,92548,5865,1252,100.0000,46.0726,33.5631,2.1270,0.4540
3,2022-04-12,standard,162146,75021,54832,3521,762,100.0000,46.2676,33.8164,2.1715,0.4699
4,2022-04-13,standard,91714,41651,29785,2034,426,100.0000,45.4140,32.4760,2.2178,0.4645
5,2022-04-14,standard,68971,31551,22601,1497,331,100.0000,45.7453,32.7688,2.1705,0.4799
6,2022-04-15,standard,58239,29413,21320,1570,299,100.0000,50.5040,36.6078,2.6958,0.5134
7,2022-04-16,standard,60538,31308,22910,1710,301,100.0000,51.7163,37.8440,2.8247,0.4972
8,2022-04-17,standard,43567,21757,15970,1103,208,100.0000,49.9392,36.6562,2.5317,0.4774
9,2022-04-18,standard,24140,11259,8092,499,108,100.0000,46.6404,33.5211,2.0671,0.4474
10,2022-04-19,standard,19973,9150,6578,447,85,100.0000,45.8118,32.9345,2.2380,0.4256
11,2022-04-20,standard,20402,9002,6449,434,105,100.0000,44.1231,31.6096,2.1272,0.5147
12,2022-04-21,standard,19695,8846,6262,408,87,100.0000,44.9150,31.7949,2.0716,0.4417
13,2022-04-22,random,24849,4259,2047,148,26,53.2498,17.1395,8.2378,0.5956,0.1046
14,2022-04-22,standard,21816,9937,7034,506,78,46.7502,45.5491,32.2424,2.3194,0.3575
15,2022-04-23,random,52358,9151,4519,300,44,66.5447,17.4777,8.6310,0.5730,0.0840
16,2022-04-23,standard,26323,12475,8966,631,120,33.4553,47.3920,34.0615,2.3971,0.4559
17,2022-04-24,random,44440,7381,3552,221,44,71.2476,16.6089,7.9928,0.4973,0.0990
18,2022-04-24,standard,17934,7915,5481,366,76,28.7524,44.1340,30.5621,2.0408,0.4238
19,2022-04-25,random,41837,6868,3250,209,28,74.0766,16.4161,7.7682,0.4996,0.0669
20,2022-04-25,standard,14641,6495,4633,316,70,25.9234,44.3617,31.6440,2.1583,0.4781
21,2022-04-26,random,42367,6826,3288,229,41,74.9965,16.1116,7.7608,0.5405,0.0968
22,2022-04-26,standard,14125,6328,4493,263,61,25.0035,44.8000,31.8088,1.8619,0.4319
23,2022-04-27,random,41736,6906,3368,235,46,75.2054,16.5469,8.0698,0.5631,0.1102
24,2022-04-27,standard,13760,5970,4234,259,66,24.7946,43.3866,30.7703,1.8823,0.4797
25,2022-04-28,random,40748,6749,3204,232,44,75.2627,16.5628,7.8630,0.5694,0.1080
26,2022-04-28,standard,13393,5780,4014,269,59,24.7373,43.1569,29.9709,2.0085,0.4405
27,2022-04-29,random,49593,8344,3969,278,44,76.5478,16.8250,8.0031,0.5606,0.0887
28,2022-04-29,standard,15194,6802,4736,295,54,23.4522,44.7677,31.1702,1.9416,0.3554
29,2022-04-30,random,62716,10702,5146,341,45,75.4034,17.0642,8.2052,0.5437,0.0718
30,2022-04-30,standard,20458,9697,6814,504,103,24.5966,47.3996,33.3073,2.4636,0.5035
31,2022-05-01,random,62043,10594,5017,320,63,75.4506,17.0753,8.0863,0.5158,0.1015
32,2022-05-01,standard,20187,9320,6564,453,85,24.5494,46.1683,32.5160,2.2440,0.4211
33,2022-05-02,random,85871,15179,7212,502,81,81.7913,17.6765,8.3986,0.5846,0.0943
34,2022-05-02,standard,19117,8802,6232,444,92,18.2087,46.0428,32.5993,2.3225,0.4812
35,2022-05-03,random,109626,20053,9776,623,108,85.5424,18.2922,8.9176,0.5683,0.0985
36,2022-05-03,standard,18528,8413,5961,412,97,14.4576,45.4070,32.1729,2.2237,0.5235
37,2022-05-04,random,108543,19798,9531,601,76,86.3398,18.2398,8.7809,0.5537,0.0700
38,2022-05-04,standard,17173,7756,5485,351,90,13.6602,45.1639,31.9397,2.0439,0.5241
39,2022-05-05,random,97170,17464,8464,518,103,88.1385,17.9726,8.7105,0.5331,0.1060
40,2022-05-05,standard,13077,5734,4000,231,60,11.8615,43.8480,30.5881,1.7665,0.4588
41,2022-05-06,random,103245,19065,9397,565,100,88.4023,18.4658,9.1017,0.5472,0.0969
42,2022-05-06,standard,13545,5819,4052,257,57,11.5977,42.9605,29.9151,1.8974,0.4208
43,2022-05-07,random,103982,18923,9099,568,108,88.6137,18.1983,8.7506,0.5462,0.1039
44,2022-05-07,standard,13361,5920,4176,276,70,11.3863,44.3081,31.2551,2.0657,0.5239
45,2022-05-08,random,114925,20672,9930,721,116,88.1448,17.9874,8.6404,0.6274,0.1009
46,2022-05-08,standard,15457,7108,5051,346,80,11.8552,45.9856,32.6778,2.2385,0.5176

In [71]:
# Reshaping daily traffic mix for later rate decomposition

daily_traffic_source_mix = (daily_traffic_source_summary
                            .pivot(index = "event_date",
                                   columns = "traffic_source",
                                   values = "traffic_source_share_of_day_percent"
                            )
                            .reset_index()
)

daily_traffic_source_mix.columns.name = None
daily_traffic_source_mix = daily_traffic_source_mix.rename(
    columns = {"random": "random_traffic_share_percent",
               "standard": "standard_traffic_share_percent"
    }
)

daily_traffic_source_mix

   event_date  random_traffic_share_percent  standard_traffic_share_percent
0  2022-04-09                           NaN                        100.0000
1  2022-04-10                           NaN                        100.0000
2  2022-04-11                           NaN                        100.0000
3  2022-04-12                           NaN                        100.0000
4  2022-04-13                           NaN                        100.0000
5  2022-04-14                           NaN                        100.0000
6  2022-04-15                           NaN                        100.0000
7  2022-04-16                           NaN                        100.0000
8  2022-04-17                           NaN                        100.0000
9  2022-04-18                           NaN                        100.0000
10 2022-04-19                           NaN                        100.0000
11 2022-04-20                           NaN                        100.0000
12 2022-04-21                           NaN                        100.0000
13 2022-04-22                       53.2498                         46.7502
14 2022-04-23                       66.5447                         33.4553
15 2022-04-24                       71.2476                         28.7524
16 2022-04-25                       74.0766                         25.9234
17 2022-04-26                       74.9965                         25.0035
18 2022-04-27                       75.2054                         24.7946
19 2022-04-28                       75.2627                         24.7373
20 2022-04-29                       76.5478                         23.4522
21 2022-04-30                       75.4034                         24.5966
22 2022-05-01                       75.4506                         24.5494
23 2022-05-02                       81.7913                         18.2087
24 2022-05-03                       85.5424                         14.4576
25 2022-05-04                       86.3398                         13.6602
26 2022-05-05                       88.1385                         11.8615
27 2022-05-06                       88.4023                         11.5977
28 2022-05-07                       88.6137                         11.3863
29 2022-05-08                       88.1448                         11.8552

In [72]:
# Setting overall rate benchmarks for segment lift comparisons
overall_rate_benchmark = {"click_rate_percent": round(impression_analysis_base["is_click"].mean() * 100, 4),
                          "meaningful_watch_rate_percent": round(impression_analysis_base["is_meaningful_watch"].mean() * 100, 4),
                          "social_engagement_rate_percent": round(impression_analysis_base["is_social_engagement"].mean() * 100, 4),
                          "high_value_engagement_rate_percent": round(impression_analysis_base["is_high_value_engagement"].mean() * 100, 4)
}

overall_rate_benchmark

{'click_rate_percent': np.float64(33.2883),
 'meaningful_watch_rate_percent': np.float64(22.1414),
 'social_engagement_rate_percent': np.float64(1.4637),
 'high_value_engagement_rate_percent': np.float64(0.2916)}

In [73]:
# Building segment lifts against overall outcome benchmarks

segment_reporting_minimum_impression_count = 1000

def build_segment_rate_comparison(dataframe, segment_fields, minimum_impression_count):
    segment_rate_comparison_list = []

    for field_name in segment_fields:
        segment_summary = (dataframe
                           .groupby(field_name, dropna = False, as_index = False)
                           .agg(impression_count = ("user_id", "size"),
                                click_count = ("is_click", "sum"),
                                meaningful_watch_count = ("is_meaningful_watch", "sum"),
                                social_engagement_count = ("is_social_engagement", "sum"),
                                high_value_engagement_count = ("is_high_value_engagement", "sum")
            )
        )

        segment_summary["click_rate_percent"] = (
            segment_summary["click_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["meaningful_watch_rate_percent"] = (
            segment_summary["meaningful_watch_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["social_engagement_rate_percent"] = (
            segment_summary["social_engagement_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["high_value_engagement_rate_percent"] = (
            segment_summary["high_value_engagement_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["click_rate_lift_vs_overall"] = (
            segment_summary["click_rate_percent"] / overall_rate_benchmark["click_rate_percent"]
        ).round(4)

        segment_summary["meaningful_watch_rate_lift_vs_overall"] = (
            segment_summary["meaningful_watch_rate_percent"] / overall_rate_benchmark["meaningful_watch_rate_percent"]
        ).round(4)

        segment_summary["social_engagement_rate_lift_vs_overall"] = (
            segment_summary["social_engagement_rate_percent"] / overall_rate_benchmark["social_engagement_rate_percent"]
        ).round(4)

        segment_summary["high_value_engagement_rate_lift_vs_overall"] = (
            segment_summary["high_value_engagement_rate_percent"] / overall_rate_benchmark["high_value_engagement_rate_percent"]
        ).round(4)

        segment_summary = (
            segment_summary.loc[segment_summary["impression_count"] >= minimum_impression_count]
            .rename(columns = {field_name: "segment_value"})
            .copy()
        )

        segment_summary.insert(0, "segment_field", field_name)
        segment_rate_comparison_list.append(segment_summary)

    return (pd.concat(segment_rate_comparison_list, ignore_index = True)
            .sort_values(["segment_field", "impression_count"], ascending = [True, False])
            .reset_index(drop = True)
    )

segment_rate_comparison = build_segment_rate_comparison(impression_analysis_base,
                                                        segment_fields,
                                                        segment_reporting_minimum_impression_count
)

segment_rate_comparison

,segment_field,segment_value,impression_count,click_count,meaningful_watch_count,social_engagement_count,high_value_engagement_count,click_rate_percent,meaningful_watch_rate_percent,social_engagement_rate_percent,high_value_engagement_rate_percent,click_rate_lift_vs_overall,meaningful_watch_rate_lift_vs_overall,social_engagement_rate_lift_vs_overall,high_value_engagement_rate_lift_vs_overall
0,fans_user_num_range,"[10,100)",991288,332748,222162,13738,3011,33.5672,22.4114,1.3859,0.3037,1.0084,1.0122,0.9468,1.0415
1,fans_user_num_range,"[100,1k)",875764,285624,189124,15013,2647,32.6143,21.5953,1.7143,0.3023,0.9798,0.9753,1.1712,1.0367
2,fans_user_num_range,"[1,10)",467709,161395,108206,5636,1253,34.5076,23.1353,1.2050,0.2679,1.0366,1.0449,0.8233,0.9187
3,fans_user_num_range,"[1k,5k)",144442,45557,29496,2635,429,31.5400,20.4207,1.8243,0.2970,0.9475,0.9223,1.2464,1.0185
4,fans_user_num_range,0,100515,33904,22538,724,197,33.7303,22.4225,0.7203,0.1960,1.0133,1.0127,0.4921,0.6722
5,fans_user_num_range,"[5k,1w)",9102,2665,1761,112,18,29.2793,19.3474,1.2305,0.1978,0.8796,0.8738,0.8407,0.6783
6,fans_user_num_range,"[1w,10w)",7871,2483,1627,101,18,31.5462,20.6708,1.2832,0.2287,0.9477,0.9336,0.8767,0.7843
7,follow_user_num_range,500+,537421,182101,121245,12338,2378,33.8842,22.5605,2.2958,0.4425,1.0179,1.0189,1.5685,1.5175
8,follow_user_num_range,"(10,50]",479351,159907,106600,4454,1123,33.3591,22.2384,0.9292,0.2343,1.0021,1.0044,0.6348,0.8035
9,follow_user_num_range,"(250,500]",411614,136314,90412,6699,1235,33.1169,21.9652,1.6275,0.3000,0.9949,0.9920,1.1119,1.0288
10,follow_user_num_range,"(50,100]",388119,129245,86445,4325,866,33.3004,22.2728,1.1143,0.2231,1.0004,1.0059,0.7613,0.7651
11,follow_user_num_range,"(150,250]",349969,117079,77953,5514,1013,33.4541,22.2743,1.5756,0.2895,1.0050,1.0060,1.0765,0.9928
12,follow_user_num_range,"(100,150]",252544,84162,56004,3441,657,33.3257,22.1759,1.3625,0.2602,1.0011,1.0016,0.9309,0.8923
13,follow_user_num_range,"(0,10]",161343,50647,33031,1204,285,31.3909,20.4725,0.7462,0.1766,0.9430,0.9246,0.5098,0.6056
14,follow_user_num_range,0,17338,5275,3477,48,18,30.4245,20.0542,0.2768,0.1038,0.9140,0.9057,0.1891,0.3560
15,friend_user_num_range,"[5,30)",726049,244243,163214,10207,2195,33.6400,22.4797,1.4058,0.3023,1.0106,1.0153,0.9604,1.0367
16,friend_user_num_range,"[1,5)",478219,161815,108569,5819,1318,33.8370,22.7028,1.2168,0.2756,1.0165,1.0254,0.8313,0.9451
17,friend_user_num_range,250+,324869,106565,69109,6493,1103,32.8025,21.2729,1.9987,0.3395,0.9854,0.9608,1.3655,1.1643
18,friend_user_num_range,0,298947,100094,66664,2264,654,33.4822,22.2996,0.7573,0.2188,1.0058,1.0071,0.5174,0.7503
19,friend_user_num_range,"[60,120)",271666,89377,59717,4947,829,32.8996,21.9818,1.8210,0.3052,0.9883,0.9928,1.2441,1.0466
20,friend_user_num_range,"[30,60)",271016,88453,58947,3804,756,32.6376,21.7504,1.4036,0.2790,0.9805,0.9823,0.9589,0.9568
21,friend_user_num_range,"[120,250)",226933,74183,48947,4489,720,32.6894,21.5689,1.9781,0.3173,0.9820,0.9741,1.3514,1.0881
22,music_type,9.0,2292634,777348,519853,33218,6782,33.9063,22.6749,1.4489,0.2958,1.0186,1.0241,0.9899,1.0144
23,music_type,4.0,212288,55494,33968,3595,539,26.1409,16.0009,1.6935,0.2539,0.7853,0.7227,1.1570,0.8707
24,music_type,NaN,79102,29098,19888,1047,216,36.7854,25.1422,1.3236,0.2731,1.1051,1.1355,0.9043,0.9366
25,music_type,8.0,9517,1837,971,72,20,19.3023,10.2028,0.7565,0.2102,0.5799,0.4608,0.5168,0.7209
26,music_type,7.0,2991,688,372,25,7,23.0023,12.4373,0.8358,0.2340,0.6910,0.5617,0.5710,0.8025
27,music_type,11.0,1167,265,115,66,11,22.7078,9.8543,5.6555,0.9426,0.6822,0.4451,3.8638,3.2325
28,register_days_range,730+,1909229,616458,408778,24286,4861,32.2883,21.4106,1.2720,0.2546,0.9700,0.9670,0.8690,0.8731
29,register_days_range,366-730,334336,118972,79376,6242,1153,35.5846,23.7414,1.8670,0.3449,1.0690,1.0723,1.2755,1.1828
30,register_days_range,181-365,179607,66080,44589,4124,786,36.7914,24.8259,2.2961,0.4376,1.1052,1.1212,1.5687,1.5007
31,register_days_range,91-180,97700,35201,23723,1896,440,36.0297,24.2815,1.9406,0.4504,1.0824,1.0967,1.3258,1.5446
32,register_days_range,61-90,34847,12751,8560,572,141,36.5914,24.5645,1.6415,0.4046,1.0992,1.1094,1.1215,1.3875
33,register_days_range,31-60,32011,11945,8084,735,153,37.3153,25.2538,2.2961,0.4780,1.1210,1.1406,1.5687,1.6392
34,register_days_range,15-30,9946,3313,2048,162,41,33.3099,20.5912,1.6288,0.4122,1.0006,0.9300,1.1128,1.4136
35,user_active_degree,full_active,1889845,612323,406125,24293,5049,32.4007,21.4899,1.2854,0.2672,0.9733,0.9706,0.8782,0.9163
36,user_active_degree,high_active,462463,161878,108521,8564,1558,35.0034,23.4659,1.8518,0.3369,1.0515,1.0598,1.2651,1.1553
37,user_active_degree,middle_active,166902,62070,41276,3838,697,37.1895,24.7307,2.2996,0.4176,1.1172,1.1169,1.5711,1.4321
38,user_active_degree,2_14_day_new,55735,19759,13355,837,171,35.4517,23.9616,1.5017,0.3068,1.0650,1.0822,1.0260,1.0521
39,user_active_degree,low_active,15407,5932,3948,361,62,38.5020,25.6247,2.3431,0.4024,1.1566,1.1573,1.6008,1.3800
40,user_active_degree,single_low_active,4481,1799,1313,93,24,40.1473,29.3015,2.0754,0.5356,1.2060,1.3234,1.4179,1.8368
41,user_active_degree,30day_retention,1228,418,269,18,9,34.0391,21.9055,1.4658,0.7329,1.0226,0.9893,1.0014,2.5134
42,user_active_degree,day_new,1111,437,300,18,5,39.3339,27.0027,1.6202,0.4500,1.1816,1.2196,1.1069,1.5432
43,video_orientation,vertical,1959315,643815,427614,27542,5729,32.8592,21.8247,1.4057,0.2924,0.9871,0.9857,0.9604,1.0027
44,video_orientation,horizontal,600056,210546,141479,9152,1688,35.0877,23.5776,1.5252,0.2813,1.0541,1.0649,1.0420,0.9647
45,video_orientation,square,38328,10369,6074,1329,158,27.0533,15.8474,3.4674,0.4122,0.8127,0.7157,2.3689,1.4136
46,video_type,NORMAL,2568173,853990,567552,37586,7474,33.2528,22.0994,1.4635,0.2910,0.9989,0.9981,0.9999,0.9979
47,video_type,AD,27185,9489,6616,419,98,34.9053,24.3370,1.5413,0.3605,1.0486,1.0992,1.0530,1.2363
48,video_type,UNKNOWN,2341,1251,999,18,3,53.4387,42.6741,0.7689,0.1282,1.6053,1.9273,0.5253,0.4396
49,video_upload_type,LongImport,1070378,375385,251984,15456,3221,35.0703,23.5416,1.4440,0.3009,1.0535,1.0632,0.9865,1.0319
50,video_upload_type,Web,800372,280368,189258,10395,2292,35.0297,23.6463,1.2988,0.2864,1.0523,1.0680,0.8873,0.9822
51,video_upload_type,ShortImport,344584,108113,73387,7308,1137,31.3749,21.2973,2.1208,0.3300,0.9425,0.9619,1.4489,1.1317
52,video_upload_type,Kmovie,254400,74991,47277,2740,575,29.4776,18.5837,1.0770,0.2260,0.8855,0.8393,0.7358,0.7750
53,video_upload_type,LongPicture,43145,6700,2069,1150,149,15.5290,4.7955,2.6654,0.3453,0.4665,0.2166,1.8210,1.1842
54,video_upload_type,UNKNOWN,29547,9777,6747,439,109,33.0897,22.8348,1.4858,0.3689,0.9940,1.0313,1.0151,1.2651
55,video_upload_type,PictureSet,15600,1514,470,172,22,9.7051,3.0128,1.1026,0.1410,0.2915,0.1361,0.7533,0.4835
56,video_upload_type,ShortCamera,14382,2719,1114,171,29,18.9056,7.7458,1.1890,0.2016,0.5679,0.3498,0.8123,0.6914
57,video_upload_type,LongCamera,14079,2483,1278,100,18,17.6362,9.0773,0.7103,0.1278,0.5298,0.4100,0.4853,0.4383
58,video_upload_type,ShareFromOtherApp,8777,2416,1492,87,19,27.5265,16.9990,0.9912,0.2165,0.8269,0.7677,0.6772,0.7425
59,video_upload_type,FollowShoot,1773,192,68,2,2,10.8291,3.8353,0.1128,0.1128,0.3253,0.1732,0.0771,0.3868

In [74]:
# Keeping only segments with enough volume for reporting
clicked_impression_reporting_minimum_count = 500

def build_post_click_segment_conversion_comparison(dataframe, segment_fields, minimum_impression_count):
    clicked_dataframe = dataframe.loc[dataframe["is_click"] == 1].copy()
    segment_conversion_list = []

    overall_clicked_meaningful_watch_rate_percent = round(
        clicked_dataframe["is_meaningful_watch"].mean() * 100,
        4
    )
    overall_clicked_profile_enter_rate_percent = round(
        clicked_dataframe["is_profile_enter"].mean() * 100,
        4
    )
    overall_clicked_like_rate_percent = round(
        clicked_dataframe["is_like"].mean() * 100,
        4
    )
    overall_clicked_high_value_engagement_rate_percent = round(
        clicked_dataframe["is_high_value_engagement"].mean() * 100,
        4
    )

    for field_name in segment_fields:
        segment_summary = (clicked_dataframe
                           .groupby(field_name, dropna = False, as_index = False)
                           .agg(clicked_impression_count = ("user_id", "size"),
                                meaningful_watch_count = ("is_meaningful_watch", "sum"),
                                profile_enter_count = ("is_profile_enter", "sum"),
                                like_count = ("is_like", "sum"),
                                high_value_engagement_count = ("is_high_value_engagement", "sum")
            )
        )

        segment_summary["click_to_meaningful_watch_rate_percent"] = (
            segment_summary["meaningful_watch_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_profile_enter_rate_percent"] = (
            segment_summary["profile_enter_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_like_rate_percent"] = (
            segment_summary["like_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_high_value_engagement_rate_percent"] = (
            segment_summary["high_value_engagement_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_meaningful_watch_rate_lift_vs_overall"] = (
            segment_summary["click_to_meaningful_watch_rate_percent"] / overall_clicked_meaningful_watch_rate_percent
        ).round(4)

        segment_summary["click_to_profile_enter_rate_lift_vs_overall"] = (
            segment_summary["click_to_profile_enter_rate_percent"] / overall_clicked_profile_enter_rate_percent
        ).round(4)

        segment_summary["click_to_like_rate_lift_vs_overall"] = (
            segment_summary["click_to_like_rate_percent"] / overall_clicked_like_rate_percent
        ).round(4)

        segment_summary["click_to_high_value_engagement_rate_lift_vs_overall"] = (
            segment_summary["click_to_high_value_engagement_rate_percent"] / overall_clicked_high_value_engagement_rate_percent
        ).round(4)

        segment_summary = (
            segment_summary.loc[segment_summary["clicked_impression_count"] >= minimum_impression_count]
            .rename(columns = {field_name: "segment_value"})
            .copy()
        )

        segment_summary.insert(0, "segment_field", field_name)
        segment_conversion_list.append(segment_summary)

    return (
        pd.concat(segment_conversion_list, ignore_index = True)
        .sort_values(["segment_field", "clicked_impression_count"], ascending = [True, False])
        .reset_index(drop = True)
    )

post_click_segment_conversion_comparison = build_post_click_segment_conversion_comparison(
    impression_analysis_base,
    segment_fields,
    clicked_impression_reporting_minimum_count,
)

post_click_segment_conversion_comparison

,segment_field,segment_value,clicked_impression_count,meaningful_watch_count,profile_enter_count,like_count,high_value_engagement_count,click_to_meaningful_watch_rate_percent,click_to_profile_enter_rate_percent,click_to_like_rate_percent,click_to_high_value_engagement_rate_percent,click_to_meaningful_watch_rate_lift_vs_overall,click_to_profile_enter_rate_lift_vs_overall,click_to_like_rate_lift_vs_overall,click_to_high_value_engagement_rate_lift_vs_overall
0,fans_user_num_range,"[10,100)",332748,221285,13033,9266,2789,66.5023,3.9168,2.7847,0.8382,1.0038,0.9227,0.9347,1.0441
1,fans_user_num_range,"[100,1k)",285624,188320,14048,10177,2391,65.9328,4.9184,3.5631,0.8371,0.9952,1.1587,1.1959,1.0427
2,fans_user_num_range,"[1,10)",161395,107816,5864,3860,1148,66.8026,3.6333,2.3916,0.7113,1.0083,0.8559,0.8027,0.8860
3,fans_user_num_range,"[1k,5k)",45557,29368,2348,1793,400,64.4643,5.1540,3.9357,0.8780,0.9730,1.2142,1.3210,1.0937
4,fans_user_num_range,0,33904,22473,1155,455,176,66.2842,3.4067,1.3420,0.5191,1.0005,0.8025,0.4504,0.6466
5,fans_user_num_range,"[5k,1w)",2665,1750,98,87,18,65.6660,3.6773,3.2645,0.6754,0.9912,0.8663,1.0957,0.8413
6,fans_user_num_range,"[1w,10w)",2483,1620,125,67,18,65.2437,5.0342,2.6983,0.7249,0.9848,1.1859,0.9057,0.9030
7,follow_user_num_range,500+,182101,120722,8024,8625,2105,66.2940,4.4063,4.7364,1.1560,1.0007,1.0380,1.5897,1.4400
8,follow_user_num_range,"(10,50]",159907,106197,6419,2725,1030,66.4117,4.0142,1.7041,0.6441,1.0024,0.9457,0.5720,0.8023
9,follow_user_num_range,"(250,500]",136314,90065,6048,4634,1164,66.0717,4.4368,3.3995,0.8539,0.9973,1.0452,1.1410,1.0637
10,follow_user_num_range,"(50,100]",129245,86156,5584,2933,815,66.6610,4.3205,2.2693,0.6306,1.0062,1.0178,0.7617,0.7855
11,follow_user_num_range,"(150,250]",117079,77664,5110,3714,940,66.3347,4.3646,3.1722,0.8029,1.0013,1.0282,1.0647,1.0001
12,follow_user_num_range,"(100,150]",84162,55717,3432,2356,603,66.2021,4.0778,2.7994,0.7165,0.9993,0.9606,0.9396,0.8925
13,follow_user_num_range,"(0,10]",50647,32891,1848,750,268,64.9417,3.6488,1.4808,0.5292,0.9803,0.8596,0.4970,0.6592
14,follow_user_num_range,0,5275,3472,242,27,17,65.8199,4.5877,0.5118,0.3223,0.9935,1.0808,0.1718,0.4015
15,friend_user_num_range,"[5,30)",244243,162626,9944,6881,2038,66.5837,4.0714,2.8173,0.8344,1.0050,0.9591,0.9456,1.0394
16,friend_user_num_range,"[1,5)",161815,108105,6018,3917,1202,66.8078,3.7191,2.4207,0.7428,1.0084,0.8761,0.8125,0.9253
17,friend_user_num_range,250+,106565,68849,5266,4485,996,64.6075,4.9416,4.2087,0.9346,0.9752,1.1641,1.4126,1.1642
18,friend_user_num_range,0,100094,66430,3582,1406,601,66.3676,3.5786,1.4047,0.6004,1.0018,0.8430,0.4715,0.7479
19,friend_user_num_range,"[60,120)",89377,59428,4419,3420,742,66.4914,4.9442,3.8265,0.8302,1.0036,1.1647,1.2843,1.0341
20,friend_user_num_range,"[30,60)",88453,58729,3954,2612,705,66.3957,4.4702,2.9530,0.7970,1.0022,1.0531,0.9911,0.9928
21,friend_user_num_range,"[120,250)",74183,48717,3524,3043,658,65.6714,4.7504,4.1020,0.8870,0.9913,1.1191,1.3768,1.1049
22,music_type,9.0,777348,517969,33469,22665,6232,66.6328,4.3055,2.9157,0.8017,1.0058,1.0143,0.9786,0.9986
23,music_type,4.0,55494,33748,2016,2274,478,60.8138,3.6328,4.0977,0.8614,0.9179,0.8558,1.3753,1.0730
24,music_type,NaN,29098,19715,1113,733,200,67.7538,3.8250,2.5191,0.6873,1.0227,0.9011,0.8455,0.8561
25,music_type,8.0,1837,967,74,35,16,52.6402,4.0283,1.9053,0.8710,0.7946,0.9490,0.6395,1.0850
26,music_type,7.0,688,370,23,18,7,53.7791,3.3430,2.6163,1.0174,0.8118,0.7875,0.8781,1.2673
27,register_days_range,730+,616458,407105,26755,16510,4438,66.0394,4.3401,2.6782,0.7199,0.9968,1.0224,0.8989,0.8967
28,register_days_range,366-730,118972,79075,4993,4167,1044,66.4652,4.1968,3.5025,0.8775,1.0032,0.9887,1.1756,1.0930
29,register_days_range,181-365,66080,44433,2656,2844,746,67.2412,4.0194,4.3039,1.1289,1.0150,0.9469,1.4446,1.4062
30,register_days_range,91-180,35201,23628,1314,1296,407,67.1231,3.7328,3.6817,1.1562,1.0132,0.8794,1.2357,1.4402
31,register_days_range,61-90,12751,8544,449,356,135,67.0065,3.5213,2.7919,1.0587,1.0114,0.8295,0.9371,1.3188
32,register_days_range,31-60,11945,8048,443,481,136,67.3755,3.7087,4.0268,1.1386,1.0170,0.8737,1.3515,1.4183
33,register_days_range,15-30,3313,2042,96,105,36,61.6360,2.8977,3.1693,1.0866,0.9304,0.6826,1.0637,1.3535
34,user_active_degree,full_active,612323,404819,26616,16326,4653,66.1120,4.3467,2.6662,0.7599,0.9979,1.0240,0.8949,0.9466
35,user_active_degree,high_active,161878,108004,6354,5831,1413,66.7194,3.9252,3.6021,0.8729,1.0071,0.9247,1.2090,1.0873
36,user_active_degree,middle_active,62070,41011,2590,2696,637,66.0722,4.1727,4.3435,1.0263,0.9973,0.9830,1.4578,1.2784
37,user_active_degree,2_14_day_new,19759,13245,787,586,155,67.0327,3.9830,2.9657,0.7845,1.0118,0.9383,0.9954,0.9772
38,user_active_degree,low_active,5932,3908,225,245,50,65.8800,3.7930,4.1301,0.8429,0.9944,0.8935,1.3862,1.0500
39,user_active_degree,single_low_active,1799,1272,83,64,21,70.7059,4.6137,3.5575,1.1673,1.0673,1.0869,1.1940,1.4540
40,video_orientation,vertical,643815,425720,26500,18676,5218,66.1246,4.1161,2.9008,0.8105,0.9981,0.9697,0.9736,1.0096
41,video_orientation,horizontal,210546,141117,9736,6282,1581,67.0243,4.6242,2.9837,0.7509,1.0117,1.0894,1.0014,0.9354
42,video_orientation,square,10369,6047,471,806,143,58.3181,4.5424,7.7732,1.3791,0.8803,1.0701,2.6090,1.7179
43,video_type,NORMAL,853990,565290,36012,25452,6846,66.1940,4.2169,2.9804,0.8016,0.9992,0.9934,1.0003,0.9985
44,video_type,AD,9489,6596,597,298,93,69.5121,6.2915,3.1405,0.9801,1.0492,1.4821,1.0541,1.2209
45,video_type,UNKNOWN,1251,998,98,14,3,79.7762,7.8337,1.1191,0.2398,1.2042,1.8454,0.3756,0.2987
46,video_upload_type,LongImport,375385,251334,16562,10937,2999,66.9537,4.4120,2.9135,0.7989,1.0106,1.0394,0.9779,0.9951
47,video_upload_type,Web,280368,188783,12104,7287,2094,67.3340,4.3172,2.5991,0.7469,1.0164,1.0170,0.8724,0.9304
48,video_upload_type,ShortImport,108113,72440,4011,4504,1014,67.0040,3.7100,4.1660,0.9379,1.0114,0.8740,1.3983,1.1683
49,video_upload_type,Kmovie,74991,47121,2632,1796,520,62.8355,3.5098,2.3950,0.6934,0.9485,0.8268,0.8039,0.8637
50,video_upload_type,UNKNOWN,9777,6727,610,302,102,68.8043,6.2391,3.0889,1.0433,1.0386,1.4698,1.0368,1.2996
51,video_upload_type,LongPicture,6700,2059,324,647,131,30.7313,4.8358,9.6567,1.9552,0.4639,1.1392,3.2412,2.4355
52,video_upload_type,ShortCamera,2719,1104,196,85,26,40.6032,7.2085,3.1261,0.9562,0.6129,1.6982,1.0492,1.1911
53,video_upload_type,LongCamera,2483,1273,45,53,14,51.2686,1.8123,2.1345,0.5638,0.7739,0.4269,0.7164,0.7023
54,video_upload_type,ShareFromOtherApp,2416,1485,159,59,17,61.4652,6.5811,2.4421,0.7036,0.9278,1.5504,0.8197,0.8764
55,video_upload_type,PictureSet,1514,467,59,91,21,30.8454,3.8970,6.0106,1.3871,0.4656,0.9180,2.0174,1.7278

In [75]:
# Ranking segments by high-value engagement potential

segment_priority_view = (
    segment_rate_comparison[
        ["segment_field", "segment_value", "impression_count", 
         "click_rate_percent", "click_rate_lift_vs_overall",
         "meaningful_watch_rate_percent", "meaningful_watch_rate_lift_vs_overall", 
         "high_value_engagement_rate_percent",
         "high_value_engagement_rate_lift_vs_overall"
        ]
    ]
    .sort_values(["high_value_engagement_rate_lift_vs_overall", "impression_count"],
                 ascending = [False, False]
    )
    .reset_index(drop = True)
)

segment_priority_view

,segment_field,segment_value,impression_count,click_rate_percent,click_rate_lift_vs_overall,meaningful_watch_rate_percent,meaningful_watch_rate_lift_vs_overall,high_value_engagement_rate_percent,high_value_engagement_rate_lift_vs_overall
0,music_type,11.0,1167,22.7078,0.6822,9.8543,0.4451,0.9426,3.2325
1,user_active_degree,30day_retention,1228,34.0391,1.0226,21.9055,0.9893,0.7329,2.5134
2,user_active_degree,single_low_active,4481,40.1473,1.2060,29.3015,1.3234,0.5356,1.8368
3,register_days_range,31-60,32011,37.3153,1.1210,25.2538,1.1406,0.4780,1.6392
4,register_days_range,91-180,97700,36.0297,1.0824,24.2815,1.0967,0.4504,1.5446
5,user_active_degree,day_new,1111,39.3339,1.1816,27.0027,1.2196,0.4500,1.5432
6,follow_user_num_range,500+,537421,33.8842,1.0179,22.5605,1.0189,0.4425,1.5175
7,register_days_range,181-365,179607,36.7914,1.1052,24.8259,1.1212,0.4376,1.5007
8,user_active_degree,middle_active,166902,37.1895,1.1172,24.7307,1.1169,0.4176,1.4321
9,video_orientation,square,38328,27.0533,0.8127,15.8474,0.7157,0.4122,1.4136
10,register_days_range,15-30,9946,33.3099,1.0006,20.5912,0.9300,0.4122,1.4136
11,register_days_range,61-90,34847,36.5914,1.0992,24.5645,1.1094,0.4046,1.3875
12,user_active_degree,low_active,15407,38.5020,1.1566,25.6247,1.1573,0.4024,1.3800
13,video_upload_type,UNKNOWN,29547,33.0897,0.9940,22.8348,1.0313,0.3689,1.2651
14,video_type,AD,27185,34.9053,1.0486,24.3370,1.0992,0.3605,1.2363
15,video_upload_type,LongPicture,43145,15.5290,0.4665,4.7955,0.2166,0.3453,1.1842
16,register_days_range,366-730,334336,35.5846,1.0690,23.7414,1.0723,0.3449,1.1828
17,friend_user_num_range,250+,324869,32.8025,0.9854,21.2729,0.9608,0.3395,1.1643
18,user_active_degree,high_active,462463,35.0034,1.0515,23.4659,1.0598,0.3369,1.1553
19,video_upload_type,ShortImport,344584,31.3749,0.9425,21.2973,0.9619,0.3300,1.1317
20,friend_user_num_range,"[120,250)",226933,32.6894,0.9820,21.5689,0.9741,0.3173,1.0881
21,user_active_degree,2_14_day_new,55735,35.4517,1.0650,23.9616,1.0822,0.3068,1.0521
22,friend_user_num_range,"[60,120)",271666,32.8996,0.9883,21.9818,0.9928,0.3052,1.0466
23,fans_user_num_range,"[10,100)",991288,33.5672,1.0084,22.4114,1.0122,0.3037,1.0415
24,fans_user_num_range,"[100,1k)",875764,32.6143,0.9798,21.5953,0.9753,0.3023,1.0367
25,friend_user_num_range,"[5,30)",726049,33.6400,1.0106,22.4797,1.0153,0.3023,1.0367
26,video_upload_type,LongImport,1070378,35.0703,1.0535,23.5416,1.0632,0.3009,1.0319
27,follow_user_num_range,"(250,500]",411614,33.1169,0.9949,21.9652,0.9920,0.3000,1.0288
28,fans_user_num_range,"[1k,5k)",144442,31.5400,0.9475,20.4207,0.9223,0.2970,1.0185
29,music_type,9.0,2292634,33.9063,1.0186,22.6749,1.0241,0.2958,1.0144
30,video_orientation,vertical,1959315,32.8592,0.9871,21.8247,0.9857,0.2924,1.0027
31,video_type,NORMAL,2568173,33.2528,0.9989,22.0994,0.9981,0.2910,0.9979
32,follow_user_num_range,"(150,250]",349969,33.4541,1.0050,22.2743,1.0060,0.2895,0.9928
33,video_upload_type,Web,800372,35.0297,1.0523,23.6463,1.0680,0.2864,0.9822
34,video_orientation,horizontal,600056,35.0877,1.0541,23.5776,1.0649,0.2813,0.9647
35,friend_user_num_range,"[30,60)",271016,32.6376,0.9805,21.7504,0.9823,0.2790,0.9568
36,friend_user_num_range,"[1,5)",478219,33.8370,1.0165,22.7028,1.0254,0.2756,0.9451
37,music_type,NaN,79102,36.7854,1.1051,25.1422,1.1355,0.2731,0.9366
38,fans_user_num_range,"[1,10)",467709,34.5076,1.0366,23.1353,1.0449,0.2679,0.9187
39,user_active_degree,full_active,1889845,32.4007,0.9733,21.4899,0.9706,0.2672,0.9163
40,follow_user_num_range,"(100,150]",252544,33.3257,1.0011,22.1759,1.0016,0.2602,0.8923
41,register_days_range,730+,1909229,32.2883,0.9700,21.4106,0.9670,0.2546,0.8731
42,music_type,4.0,212288,26.1409,0.7853,16.0009,0.7227,0.2539,0.8707
43,follow_user_num_range,"(10,50]",479351,33.3591,1.0021,22.2384,1.0044,0.2343,0.8035
44,music_type,7.0,2991,23.0023,0.6910,12.4373,0.5617,0.2340,0.8025
45,fans_user_num_range,"[1w,10w)",7871,31.5462,0.9477,20.6708,0.9336,0.2287,0.7843
46,video_upload_type,Kmovie,254400,29.4776,0.8855,18.5837,0.8393,0.2260,0.7750
47,follow_user_num_range,"(50,100]",388119,33.3004,1.0004,22.2728,1.0059,0.2231,0.7651
48,friend_user_num_range,0,298947,33.4822,1.0058,22.2996,1.0071,0.2188,0.7503
49,video_upload_type,ShareFromOtherApp,8777,27.5265,0.8269,16.9990,0.7677,0.2165,0.7425
50,music_type,8.0,9517,19.3023,0.5799,10.2028,0.4608,0.2102,0.7209
51,video_upload_type,ShortCamera,14382,18.9056,0.5679,7.7458,0.3498,0.2016,0.6914
52,fans_user_num_range,"[5k,1w)",9102,29.2793,0.8796,19.3474,0.8738,0.1978,0.6783
53,fans_user_num_range,0,100515,33.7303,1.0133,22.4225,1.0127,0.1960,0.6722
54,follow_user_num_range,"(0,10]",161343,31.3909,0.9430,20.4725,0.9246,0.1766,0.6056
55,video_upload_type,PictureSet,15600,9.7051,0.2915,3.0128,0.1361,0.1410,0.4835
56,video_type,UNKNOWN,2341,53.4387,1.6053,42.6741,1.9273,0.1282,0.4396
57,video_upload_type,LongCamera,14079,17.6362,0.5298,9.0773,0.4100,0.1278,0.4383
58,video_upload_type,FollowShoot,1773,10.8291,0.3253,3.8353,0.1732,0.1128,0.3868
59,follow_user_num_range,0,17338,30.4245,0.9140,20.0542,0.9057,0.1038,0.3560

In [76]:
# Establishing traffic-source baselines for fair comparisons
traffic_source_benchmark = (impression_analysis_base
                            .groupby("traffic_source", as_index = False)
                            .agg(impression_count = ("user_id", "size"),
                                 click_rate = ("is_click", "mean"),
                                 meaningful_watch_rate = ("is_meaningful_watch", "mean"),
                                 social_engagement_rate = ("is_social_engagement", "mean"),
                                 high_value_engagement_rate = ("is_high_value_engagement", "mean")
    )
)

traffic_source_benchmark["click_rate_percent"] = (
    traffic_source_benchmark["click_rate"] * 100
).round(4)

traffic_source_benchmark["meaningful_watch_rate_percent"] = (
    traffic_source_benchmark["meaningful_watch_rate"] * 100
).round(4)

traffic_source_benchmark["social_engagement_rate_percent"] = (
    traffic_source_benchmark["social_engagement_rate"] * 100
).round(4)

traffic_source_benchmark["high_value_engagement_rate_percent"] = (
    traffic_source_benchmark["high_value_engagement_rate"] * 100
).round(4)

traffic_source_benchmark

,traffic_source,impression_count,click_rate,meaningful_watch_rate,social_engagement_rate,high_value_engagement_rate,click_rate_percent,meaningful_watch_rate_percent,social_engagement_rate_percent,high_value_engagement_rate_percent
0,random,1186049,0.17616,0.084962,0.005574,0.000942,17.616,8.4962,0.5574,0.0942
1,standard,1411650,0.46456,0.336059,0.022252,0.004575,46.456,33.6059,2.2252,0.4575

In [77]:
# Separating daily rate shifts from traffic-mix effects

daily_rate_decomposition = daily_funnel_summary.merge(daily_traffic_source_mix,
                                                      on = "event_date",
                                                      how = "left"
)

daily_rate_decomposition["random_traffic_share_percent"] = (
    daily_rate_decomposition["random_traffic_share_percent"].fillna(0)
)

daily_rate_decomposition["standard_traffic_share_percent"] = (
    daily_rate_decomposition["standard_traffic_share_percent"].fillna(100)
)

traffic_source_rate_lookup = (traffic_source_benchmark
                              .set_index("traffic_source")[
                                    ["click_rate", "meaningful_watch_rate", "social_engagement_rate", "high_value_engagement_rate"]
    ]
    .to_dict("index")
)

daily_rate_decomposition["expected_click_rate_from_traffic_mix_percent"] = (
    daily_rate_decomposition["standard_traffic_share_percent"] / 100 * traffic_source_rate_lookup["standard"]["click_rate"]
    + daily_rate_decomposition["random_traffic_share_percent"] / 100 * traffic_source_rate_lookup["random"]["click_rate"]
) * 100

daily_rate_decomposition["expected_meaningful_watch_rate_from_traffic_mix_percent"] = (
    daily_rate_decomposition["standard_traffic_share_percent"] / 100 * traffic_source_rate_lookup["standard"]["meaningful_watch_rate"]
    + daily_rate_decomposition["random_traffic_share_percent"] / 100 * traffic_source_rate_lookup["random"]["meaningful_watch_rate"]
) * 100

daily_rate_decomposition["expected_social_engagement_rate_from_traffic_mix_percent"] = (
    daily_rate_decomposition["standard_traffic_share_percent"] / 100 * traffic_source_rate_lookup["standard"]["social_engagement_rate"]
    + daily_rate_decomposition["random_traffic_share_percent"] / 100 * traffic_source_rate_lookup["random"]["social_engagement_rate"]
) * 100

daily_rate_decomposition["expected_high_value_engagement_rate_from_traffic_mix_percent"] = (
    daily_rate_decomposition["standard_traffic_share_percent"] / 100 * traffic_source_rate_lookup["standard"]["high_value_engagement_rate"]
    + daily_rate_decomposition["random_traffic_share_percent"] / 100 * traffic_source_rate_lookup["random"]["high_value_engagement_rate"]
) * 100

daily_rate_decomposition["click_rate_gap_vs_mix_expectation_percent_points"] = (
    daily_rate_decomposition["click_rate_percent"] - daily_rate_decomposition["expected_click_rate_from_traffic_mix_percent"]
).round(4)

daily_rate_decomposition["meaningful_watch_rate_gap_vs_mix_expectation_percent_points"] = (
    daily_rate_decomposition["meaningful_watch_rate_percent"] - daily_rate_decomposition["expected_meaningful_watch_rate_from_traffic_mix_percent"]
).round(4)

daily_rate_decomposition["social_engagement_rate_gap_vs_mix_expectation_percent_points"] = (
    daily_rate_decomposition["social_engagement_rate_percent"] - daily_rate_decomposition["expected_social_engagement_rate_from_traffic_mix_percent"]
).round(4)

daily_rate_decomposition["high_value_engagement_rate_gap_vs_mix_expectation_percent_points"] = (
    daily_rate_decomposition["high_value_engagement_rate_percent"] - daily_rate_decomposition["expected_high_value_engagement_rate_from_traffic_mix_percent"]
).round(4)

daily_rate_decomposition[
    [
        "event_date",
        "impression_count",
        "standard_traffic_share_percent",
        "random_traffic_share_percent",
        "click_rate_percent",
        "expected_click_rate_from_traffic_mix_percent",
        "click_rate_gap_vs_mix_expectation_percent_points",
        "meaningful_watch_rate_percent",
        "expected_meaningful_watch_rate_from_traffic_mix_percent",
        "meaningful_watch_rate_gap_vs_mix_expectation_percent_points",
        "social_engagement_rate_percent",
        "expected_social_engagement_rate_from_traffic_mix_percent",
        "social_engagement_rate_gap_vs_mix_expectation_percent_points",
        "high_value_engagement_rate_percent",
        "expected_high_value_engagement_rate_from_traffic_mix_percent",
        "high_value_engagement_rate_gap_vs_mix_expectation_percent_points"
    ]
]

,event_date,impression_count,standard_traffic_share_percent,random_traffic_share_percent,click_rate_percent,expected_click_rate_from_traffic_mix_percent,click_rate_gap_vs_mix_expectation_percent_points,meaningful_watch_rate_percent,expected_meaningful_watch_rate_from_traffic_mix_percent,meaningful_watch_rate_gap_vs_mix_expectation_percent_points,social_engagement_rate_percent,expected_social_engagement_rate_from_traffic_mix_percent,social_engagement_rate_gap_vs_mix_expectation_percent_points,high_value_engagement_rate_percent,expected_high_value_engagement_rate_from_traffic_mix_percent,high_value_engagement_rate_gap_vs_mix_expectation_percent_points
0,2022-04-09,52390,100.0000,0.0000,44.8750,46.455991,-1.5810,33.7793,33.605922,0.1734,2.0691,2.225197,-0.1561,0.4066,0.457479,-0.0509
1,2022-04-10,226043,100.0000,0.0000,46.9004,46.455991,0.4444,34.2537,33.605922,0.6478,2.2390,2.225197,0.0138,0.4260,0.457479,-0.0315
2,2022-04-11,275743,100.0000,0.0000,46.0726,46.455991,-0.3834,33.5631,33.605922,-0.0428,2.1270,2.225197,-0.0982,0.4540,0.457479,-0.0035
3,2022-04-12,162146,100.0000,0.0000,46.2676,46.455991,-0.1884,33.8164,33.605922,0.2105,2.1715,2.225197,-0.0537,0.4699,0.457479,0.0124
4,2022-04-13,91714,100.0000,0.0000,45.4140,46.455991,-1.0420,32.4760,33.605922,-1.1299,2.2178,2.225197,-0.0074,0.4645,0.457479,0.0070
5,2022-04-14,68971,100.0000,0.0000,45.7453,46.455991,-0.7107,32.7688,33.605922,-0.8371,2.1705,2.225197,-0.0547,0.4799,0.457479,0.0224
6,2022-04-15,58239,100.0000,0.0000,50.5040,46.455991,4.0480,36.6078,33.605922,3.0019,2.6958,2.225197,0.4706,0.5134,0.457479,0.0559
7,2022-04-16,60538,100.0000,0.0000,51.7163,46.455991,5.2603,37.8440,33.605922,4.2381,2.8247,2.225197,0.5995,0.4972,0.457479,0.0397
8,2022-04-17,43567,100.0000,0.0000,49.9392,46.455991,3.4832,36.6562,33.605922,3.0503,2.5317,2.225197,0.3065,0.4774,0.457479,0.0199
9,2022-04-18,24140,100.0000,0.0000,46.6404,46.455991,0.1844,33.5211,33.605922,-0.0848,2.0671,2.225197,-0.1581,0.4474,0.457479,-0.0101
10,2022-04-19,19973,100.0000,0.0000,45.8118,46.455991,-0.6442,32.9345,33.605922,-0.6714,2.2380,2.225197,0.0128,0.4256,0.457479,-0.0319
11,2022-04-20,20402,100.0000,0.0000,44.1231,46.455991,-2.3329,31.6096,33.605922,-1.9963,2.1272,2.225197,-0.0980,0.5147,0.457479,0.0572
12,2022-04-21,19695,100.0000,0.0000,44.9150,46.455991,-1.5410,31.7949,33.605922,-1.8110,2.0716,2.225197,-0.1536,0.4417,0.457479,-0.0158
13,2022-04-22,46665,46.7502,53.2498,30.4211,31.098736,-0.6776,19.4600,20.235041,-0.7750,1.4015,1.337097,0.0644,0.2229,0.264022,-0.0411
14,2022-04-23,78681,33.4553,66.5447,27.4857,27.264484,0.2212,17.1388,16.896728,0.2421,1.1833,1.115365,0.0679,0.2084,0.215722,-0.0073
15,2022-04-24,62374,28.7524,71.2476,24.5230,25.908166,-1.3852,14.4820,15.715842,-1.2338,0.9411,1.036930,-0.0958,0.1924,0.198636,-0.0062
16,2022-04-25,56478,25.9234,74.0766,23.6605,25.092282,-1.4318,13.9576,15.005488,-1.0479,0.9296,0.989747,-0.0601,0.1735,0.188358,-0.0149
17,2022-04-26,56492,25.0035,74.9965,23.2847,24.826982,-1.5423,13.7736,14.774503,-1.0009,0.8709,0.974405,-0.1035,0.1806,0.185016,-0.0044
18,2022-04-27,55496,24.7946,75.2054,23.2017,24.766736,-1.5650,13.6983,14.722049,-1.0237,0.8902,0.970921,-0.0807,0.2018,0.184257,0.0175
19,2022-04-28,54141,24.7373,75.2627,23.1414,24.750210,-1.6088,13.3319,14.707661,-1.3758,0.9254,0.969966,-0.0446,0.1902,0.184049,0.0062
20,2022-04-29,64787,23.4522,76.5478,23.3781,24.379587,-1.0015,13.4363,14.384976,-0.9487,0.8844,0.948533,-0.0641,0.1513,0.179380,-0.0281
21,2022-04-30,83174,24.5966,75.4034,24.5257,24.709632,-0.1839,14.3795,14.672332,-0.2928,1.0159,0.967619,0.0483,0.1779,0.183538,-0.0056
22,2022-05-01,82230,24.5494,75.4506,24.2174,24.696020,-0.4786,14.0837,14.660480,-0.5768,0.9400,0.966832,-0.0268,0.1800,0.183366,-0.0034
23,2022-05-02,104988,18.2087,81.7913,22.8417,22.867360,-0.0257,12.8053,13.068347,-0.2630,0.9011,0.861082,0.0400,0.1648,0.160331,0.0045
24,2022-05-03,128154,14.4576,85.5424,22.2123,21.785542,0.4268,12.2798,12.126456,0.1533,0.8076,0.798521,0.0091,0.1600,0.146703,0.0133
25,2022-05-04,125716,13.6602,86.3398,21.9177,21.555572,0.3621,11.9444,11.926231,0.0182,0.7573,0.785222,-0.0279,0.1320,0.143806,-0.0118
26,2022-05-05,110247,11.8615,88.1385,21.0418,21.036826,0.0050,11.3055,11.474583,-0.1691,0.6794,0.755223,-0.0758,0.1478,0.137271,0.0105
27,2022-05-06,116790,11.5977,88.4023,21.3066,20.960746,0.3459,11.5155,11.408343,0.1072,0.7038,0.750823,-0.0470,0.1344,0.136313,-0.0019
28,2022-05-07,117343,11.3863,88.6137,21.1713,20.899779,0.2715,11.3130,11.355261,-0.0423,0.7193,0.747298,-0.0280,0.1517,0.135545,0.0162
29,2022-05-08,130382,11.8552,88.1448,21.3066,21.035010,0.2716,11.4901,11.473001,0.0171,0.8184,0.755118,0.0633,0.1503,0.137248,0.0131

In [78]:
# Calculating uncertainty bounds for segment-level rate comparisons

def wilson_interval(success_count, total_count, z_value = 1.96):
    if total_count == 0:
        return np.nan, np.nan

    proportion = success_count / total_count
    denominator = 1 + (z_value ** 2) / total_count
    center = (proportion + (z_value ** 2) / (2 * total_count)) / denominator
    margin = (z_value * np.sqrt((
                                    proportion * (1 - proportion) + (z_value ** 2) / (4 * total_count)
                                ) / total_count
        )
    ) / denominator

    return center, margin


def build_segment_rate_comparison_within_traffic_source(dataframe, segment_fields, minimum_impression_count):
    traffic_source_baseline = (dataframe
                               .groupby("traffic_source", as_index = False)
                               .agg(traffic_source_impression_count = ("user_id", "size"),
                                    traffic_source_click_rate = ("is_click", "mean"),
                                    traffic_source_meaningful_watch_rate = ("is_meaningful_watch", "mean"),
                                    traffic_source_social_engagement_rate = ("is_social_engagement", "mean"),
                                    traffic_source_high_value_engagement_rate = ("is_high_value_engagement", "mean")
        )
    )

    comparison_tables = []

    for field_name in segment_fields:
        segment_summary = (dataframe
                           .groupby(["traffic_source", field_name], dropna = False, as_index = False)
                           .agg(impression_count = ("user_id", "size"),
                                click_count = ("is_click", "sum"),
                                meaningful_watch_count = ("is_meaningful_watch", "sum"),
                                social_engagement_count = ("is_social_engagement", "sum"),
                                high_value_engagement_count = ("is_high_value_engagement", "sum")
            )
            .rename(columns = {field_name: "segment_value"})
        )

        segment_summary = segment_summary.loc[
            segment_summary["impression_count"] >= minimum_impression_count
        ].copy()

        segment_summary["click_rate_percent"] = (
            segment_summary["click_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["meaningful_watch_rate_percent"] = (
            segment_summary["meaningful_watch_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["social_engagement_rate_percent"] = (
            segment_summary["social_engagement_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        segment_summary["high_value_engagement_rate_percent"] = (
            segment_summary["high_value_engagement_count"] / segment_summary["impression_count"] * 100
        ).round(4)

        click_interval = segment_summary.apply(
            lambda row: wilson_interval(row["click_count"], row["impression_count"]),
            axis = 1
        )

        high_value_interval = segment_summary.apply(
            lambda row: wilson_interval(row["high_value_engagement_count"], row["impression_count"]),
            axis = 1
        )

        segment_summary["click_rate_center"] = [interval[0] for interval in click_interval]
        segment_summary["click_rate_margin"] = [interval[1] for interval in click_interval]
        segment_summary["high_value_engagement_rate_center"] = [interval[0] for interval in high_value_interval]
        segment_summary["high_value_engagement_rate_margin"] = [interval[1] for interval in high_value_interval]

        segment_summary["click_rate_lower_bound_percent"] = (
            (segment_summary["click_rate_center"] - segment_summary["click_rate_margin"]) * 100
        ).round(4)

        segment_summary["click_rate_upper_bound_percent"] = (
            (segment_summary["click_rate_center"] + segment_summary["click_rate_margin"]) * 100
        ).round(4)

        segment_summary["high_value_engagement_rate_lower_bound_percent"] = (
            (
                segment_summary["high_value_engagement_rate_center"] - segment_summary["high_value_engagement_rate_margin"]
            ) * 100
        ).round(4)

        segment_summary["high_value_engagement_rate_upper_bound_percent"] = (
            (
                segment_summary["high_value_engagement_rate_center"] + segment_summary["high_value_engagement_rate_margin"]
            ) * 100
        ).round(4)

        segment_summary = segment_summary.merge(traffic_source_baseline,
                                                on = "traffic_source", 
                                                how = "left"
        )

        segment_summary["traffic_source_click_rate_percent"] = (
            segment_summary["traffic_source_click_rate"] * 100
        ).round(4)

        segment_summary["traffic_source_high_value_engagement_rate_percent"] = (
            segment_summary["traffic_source_high_value_engagement_rate"] * 100
        ).round(4)

        segment_summary["click_rate_lift_within_traffic_source"] = (
            segment_summary["click_rate_percent"] / segment_summary["traffic_source_click_rate_percent"]
        ).round(4)

        segment_summary["high_value_engagement_rate_lift_within_traffic_source"] = (
            segment_summary["high_value_engagement_rate_percent"] / segment_summary["traffic_source_high_value_engagement_rate_percent"]
        ).round(4)

        segment_summary["click_rate_confidently_above_traffic_source"] = (
            segment_summary["click_rate_lower_bound_percent"] > segment_summary["traffic_source_click_rate_percent"]
        )

        segment_summary["high_value_engagement_rate_confidently_above_traffic_source"] = (
            segment_summary["high_value_engagement_rate_lower_bound_percent"] > segment_summary["traffic_source_high_value_engagement_rate_percent"]
        )

        segment_summary.insert(0, "segment_field", field_name)
        comparison_tables.append(segment_summary)

    return (pd.concat(comparison_tables, ignore_index = True)
            .sort_values(["segment_field", "traffic_source", "impression_count"],
                         ascending = [True, True, False]
        )
        .reset_index(drop = True)
    )


segment_rate_comparison_within_traffic_source = build_segment_rate_comparison_within_traffic_source(
    impression_analysis_base,
    segment_fields,
    minimum_impression_count = 1000
)

segment_rate_comparison_within_traffic_source[
    [
        "segment_field", 
        "traffic_source",
        "segment_value",
        "impression_count",
        "click_rate_percent",
        "traffic_source_click_rate_percent",
        "click_rate_lift_within_traffic_source",
        "click_rate_lower_bound_percent",
        "click_rate_upper_bound_percent",
        "click_rate_confidently_above_traffic_source",
        "high_value_engagement_rate_percent",
        "traffic_source_high_value_engagement_rate_percent",
        "high_value_engagement_rate_lift_within_traffic_source",
        "high_value_engagement_rate_lower_bound_percent",
        "high_value_engagement_rate_upper_bound_percent",
        "high_value_engagement_rate_confidently_above_traffic_source"
    ]
]

,segment_field,traffic_source,segment_value,impression_count,click_rate_percent,traffic_source_click_rate_percent,click_rate_lift_within_traffic_source,click_rate_lower_bound_percent,click_rate_upper_bound_percent,click_rate_confidently_above_traffic_source,high_value_engagement_rate_percent,traffic_source_high_value_engagement_rate_percent,high_value_engagement_rate_lift_within_traffic_source,high_value_engagement_rate_lower_bound_percent,high_value_engagement_rate_upper_bound_percent,high_value_engagement_rate_confidently_above_traffic_source
0,fans_user_num_range,random,"[10,100)",457791,17.5471,17.616,0.9961,17.4372,17.6575,False,0.1044,0.0942,1.1083,0.0955,0.1142,True
1,fans_user_num_range,random,"[100,1k)",380239,17.5455,17.616,0.9960,17.4250,17.6668,False,0.0934,0.0942,0.9915,0.0841,0.1036,False
2,fans_user_num_range,random,"[1,10)",225066,18.0680,17.616,1.0257,17.9096,18.2275,True,0.0942,0.0942,1.0000,0.0823,0.1077,False
3,fans_user_num_range,random,"[1k,5k)",65279,17.2659,17.616,0.9801,16.9779,17.5578,False,0.0797,0.0942,0.8461,0.0608,0.1044,False
4,fans_user_num_range,random,0,49483,17.7758,17.616,1.0091,17.4415,18.1152,False,0.0384,0.0942,0.4076,0.0246,0.0600,False
5,fans_user_num_range,random,"[5k,1w)",4198,12.1486,17.616,0.6896,11.1948,13.1717,False,0.0238,0.0942,0.2527,0.0042,0.1348,False
6,fans_user_num_range,random,"[1w,10w)",3562,15.7496,17.616,0.8941,14.5903,16.9827,False,0.0000,0.0942,0.0000,0.0000,0.1077,False
7,fans_user_num_range,standard,"[10,100)",533497,47.3140,46.456,1.0185,47.1801,47.4480,True,0.4748,0.4575,1.0378,0.4567,0.4936,False
8,fans_user_num_range,standard,"[100,1k)",495525,44.1772,46.456,0.9509,44.0390,44.3155,False,0.4625,0.4575,1.0109,0.4440,0.4818,False
9,fans_user_num_range,standard,"[1,10)",242643,49.7562,46.456,1.0710,49.5573,49.9552,True,0.4290,0.4575,0.9377,0.4038,0.4558,False
10,fans_user_num_range,standard,"[1k,5k)",79163,43.3106,46.456,0.9323,42.9658,43.6561,False,0.4762,0.4575,1.0409,0.4306,0.5267,False
11,fans_user_num_range,standard,0,51032,49.2005,46.456,1.0591,48.7668,49.6343,True,0.3488,0.4575,0.7624,0.3013,0.4038,False
12,fans_user_num_range,standard,"[5k,1w)",4904,43.9437,46.456,0.9459,42.5599,45.3370,False,0.3467,0.4575,0.7578,0.2166,0.5545,False
13,fans_user_num_range,standard,"[1w,10w)",4309,44.6043,46.456,0.9601,43.1256,46.0927,False,0.4177,0.4575,0.9130,0.2644,0.6594,False
14,follow_user_num_range,random,500+,258413,18.4697,17.616,1.0485,18.3205,18.6197,True,0.1412,0.0942,1.4989,0.1275,0.1565,True
15,follow_user_num_range,random,"(10,50]",214277,17.4526,17.616,0.9907,17.2925,17.6139,False,0.0803,0.0942,0.8524,0.0691,0.0932,False
16,follow_user_num_range,random,"(250,500]",187701,17.3728,17.616,0.9862,17.2021,17.5449,False,0.0975,0.0942,1.0350,0.0844,0.1127,False
17,follow_user_num_range,random,"(50,100]",167839,17.2671,17.616,0.9802,17.0871,17.4487,False,0.0769,0.0942,0.8163,0.0647,0.0913,False
18,follow_user_num_range,random,"(150,250]",161034,17.6044,17.616,0.9993,17.4191,17.7911,False,0.0789,0.0942,0.8376,0.0663,0.0938,False
19,follow_user_num_range,random,"(100,150]",112508,17.2948,17.616,0.9818,17.0749,17.5169,False,0.0835,0.0942,0.8864,0.0683,0.1022,False
20,follow_user_num_range,random,"(0,10]",75711,17.0794,17.616,0.9695,16.8130,17.3492,False,0.0594,0.0942,0.6306,0.0444,0.0795,False
21,follow_user_num_range,random,0,8566,17.2893,17.616,0.9815,16.5032,18.1047,False,0.0233,0.0942,0.2473,0.0064,0.0851,False
22,follow_user_num_range,standard,500+,279008,48.1610,46.456,1.0367,47.9756,48.3464,True,0.7215,0.4575,1.5770,0.6908,0.7536,True
23,follow_user_num_range,standard,"(10,50]",265074,46.2173,46.456,0.9949,46.0275,46.4071,False,0.3588,0.4575,0.7843,0.3367,0.3823,False
24,follow_user_num_range,standard,"(250,500]",223913,46.3149,46.456,0.9970,46.1084,46.5215,False,0.4698,0.4575,1.0269,0.4423,0.4990,False
25,follow_user_num_range,standard,"(50,100]",220280,45.5166,46.456,0.9798,45.3087,45.7247,False,0.3346,0.4575,0.7314,0.3113,0.3596,False
26,follow_user_num_range,standard,"(150,250]",188935,46.9632,46.456,1.0109,46.7383,47.1883,True,0.4689,0.4575,1.0249,0.4391,0.5008,False
27,follow_user_num_range,standard,"(100,150]",140036,46.2053,46.456,0.9946,45.9442,46.4665,False,0.4020,0.4575,0.8787,0.3702,0.4366,False
28,follow_user_num_range,standard,"(0,10]",85632,44.0443,46.456,0.9481,43.7120,44.3771,False,0.2803,0.4575,0.6127,0.2470,0.3180,False
29,follow_user_num_range,standard,0,8772,43.2513,46.456,0.9310,42.2177,44.2908,False,0.1824,0.4575,0.3987,0.1123,0.2961,False
30,friend_user_num_range,random,"[5,30)",334148,17.7795,17.616,1.0093,17.6503,17.9096,True,0.1077,0.0942,1.1433,0.0972,0.1194,True
31,friend_user_num_range,random,"[1,5)",226221,17.6571,17.616,1.0023,17.5005,17.8147,False,0.1034,0.0942,1.0977,0.0910,0.1176,False
32,friend_user_num_range,random,250+,148316,18.1484,17.616,1.0302,17.9531,18.3454,True,0.1052,0.0942,1.1168,0.0899,0.1230,False
33,friend_user_num_range,random,0,143344,17.5975,17.616,0.9989,17.4013,17.7955,False,0.0614,0.0942,0.6518,0.0498,0.0756,False
34,friend_user_num_range,random,"[30,60)",119570,17.1807,17.616,0.9753,16.9680,17.3956,False,0.0811,0.0942,0.8609,0.0665,0.0989,False
35,friend_user_num_range,random,"[60,120)",115302,17.0413,17.616,0.9674,16.8254,17.2595,False,0.0841,0.0942,0.8928,0.0690,0.1026,False
36,friend_user_num_range,random,"[120,250)",99148,17.3942,17.616,0.9874,17.1595,17.6314,False,0.0857,0.0942,0.9098,0.0693,0.1060,False
37,friend_user_num_range,standard,"[5,30)",391901,47.1632,46.456,1.0152,47.0069,47.3195,True,0.4682,0.4575,1.0234,0.4473,0.4901,False
38,friend_user_num_range,standard,"[1,5)",251998,48.3619,46.456,1.0410,48.1668,48.5570,True,0.4302,0.4575,0.9403,0.4054,0.4565,False
39,friend_user_num_range,standard,250+,176553,45.1128,46.456,0.9711,44.8808,45.3450,False,0.5364,0.4575,1.1725,0.5034,0.5715,True
40,friend_user_num_range,standard,"[60,120)",156364,44.5934,46.456,0.9599,44.3471,44.8399,False,0.4681,0.4575,1.0232,0.4355,0.5032,False
41,friend_user_num_range,standard,0,155603,48.1154,46.456,1.0357,47.8672,48.3637,True,0.3637,0.4575,0.7950,0.3350,0.3949,False
42,friend_user_num_range,standard,"[30,60)",151446,44.8411,46.456,0.9652,44.5907,45.0917,False,0.4351,0.4575,0.9510,0.4032,0.4696,False
43,friend_user_num_range,standard,"[120,250)",127785,44.5569,46.456,0.9591,44.2845,44.8296,False,0.4969,0.4575,1.0861,0.4598,0.5370,True
44,music_type,random,9.0,1042841,17.7558,17.616,1.0079,17.6826,17.8293,True,0.0946,0.0942,1.0042,0.0889,0.1007,False
45,music_type,random,4.0,103618,15.3825,17.616,0.8732,15.1641,15.6034,False,0.0984,0.0942,1.0446,0.0811,0.1195,False
46,music_type,random,NaN,30770,20.7637,17.616,1.1787,20.3142,21.2206,True,0.0715,0.0942,0.7590,0.0472,0.1082,False
47,music_type,random,8.0,6196,16.0910,17.616,0.9134,15.1971,17.0269,False,0.0646,0.0942,0.6858,0.0251,0.1659,False
48,music_type,random,7.0,2127,17.9126,17.616,1.0168,16.3412,19.5996,False,0.0470,0.0942,0.4989,0.0083,0.2658,False
49,music_type,standard,9.0,1249793,47.3825,46.456,1.0199,47.2950,47.4700,True,0.4637,0.4575,1.0136,0.4519,0.4757,False
50,music_type,standard,4.0,108670,36.3992,46.456,0.7835,36.1136,36.6857,False,0.4021,0.4575,0.8789,0.3662,0.4416,False
51,music_type,standard,NaN,48332,46.9854,46.456,1.0114,46.5407,47.4306,True,0.4014,0.4575,0.8774,0.3488,0.4618,False
52,music_type,standard,8.0,3321,25.2936,46.456,0.5445,23.8443,26.8000,False,0.4818,0.4575,1.0531,0.2968,0.7812,False
53,register_days_range,random,730+,860367,16.9674,17.616,0.9632,16.8882,17.0469,False,0.0839,0.0942,0.8907,0.0780,0.0903,False
54,register_days_range,random,366-730,155187,19.3173,17.616,1.0966,19.1217,19.5145,True,0.1044,0.0942,1.1083,0.0895,0.1217,False
55,register_days_range,random,181-365,83818,18.8313,17.616,1.0690,18.5680,19.0974,True,0.1336,0.0942,1.4183,0.1111,0.1607,True
56,register_days_range,random,91-180,48134,19.2317,17.616,1.0917,18.8821,19.5863,True,0.1433,0.0942,1.5212,0.1133,0.1814,True
57,register_days_range,random,61-90,17968,19.7407,17.616,1.1206,19.1651,20.3291,True,0.1169,0.0942,1.2410,0.0765,0.1786,False
58,register_days_range,random,31-60,15095,20.2915,17.616,1.1519,19.6575,20.9406,True,0.1590,0.0942,1.6879,0.1069,0.2365,True
59,register_days_range,random,15-30,5470,24.1499,17.616,1.3709,23.0341,25.3020,True,0.1280,0.0942,1.3588,0.0620,0.2639,False
60,register_days_range,standard,730+,1048862,44.8559,46.456,0.9656,44.7607,44.9511,False,0.3946,0.4575,0.8625,0.3828,0.4068,False
61,register_days_range,standard,366-730,179149,49.6760,46.456,1.0693,49.4444,49.9075,True,0.5532,0.4575,1.2092,0.5199,0.5886,True
62,register_days_range,standard,181-365,95789,52.5071,46.456,1.1303,52.1907,52.8232,True,0.7036,0.4575,1.5379,0.6526,0.7586,True
63,register_days_range,standard,91-180,49566,52.3423,46.456,1.1267,51.9025,52.7818,True,0.7485,0.4575,1.6361,0.6763,0.8283,True
64,register_days_range,standard,31-60,16916,52.5065,46.456,1.1302,51.7535,53.2584,True,0.7626,0.4575,1.6669,0.6422,0.9053,True
65,register_days_range,standard,61-90,16879,54.5293,46.456,1.1738,53.7771,55.2794,True,0.7109,0.4575,1.5539,0.5949,0.8494,True
66,register_days_range,standard,15-30,4476,44.5040,46.456,0.9580,43.0534,45.9641,False,0.7596,0.4575,1.6603,0.5441,1.0596,True
67,user_active_degree,random,full_active,833260,16.9184,17.616,0.9604,16.8380,16.9990,False,0.0845,0.0942,0.8970,0.0785,0.0910,False
68,user_active_degree,random,high_active,235289,19.0234,17.616,1.0799,18.8653,19.1825,True,0.1224,0.0942,1.2994,0.1091,0.1374,True
69,user_active_degree,random,middle_active,82845,19.7598,17.616,1.1217,19.4900,20.0323,True,0.1098,0.0942,1.1656,0.0895,0.1348,False
70,user_active_degree,random,2_14_day_new,23214,18.3941,17.616,1.0442,17.9009,18.8977,True,0.1034,0.0942,1.0977,0.0695,0.1538,False
71,user_active_degree,random,low_active,8619,23.4714,17.616,1.3324,22.5886,24.3779,True,0.0928,0.0942,0.9851,0.0470,0.1831,False
72,user_active_degree,random,single_low_active,1570,19.3631,17.616,1.0992,17.4842,21.3915,False,0.0000,0.0942,0.0000,0.0000,0.2441,False
73,user_active_degree,standard,full_active,1056585,44.6106,46.456,0.9603,44.5158,44.7054,False,0.4112,0.4575,0.8988,0.3992,0.4236,False
74,user_active_degree,standard,high_active,227174,51.5543,46.456,1.1097,51.3488,51.7598,True,0.5590,0.4575,1.2219,0.5292,0.5906,True
75,user_active_degree,standard,middle_active,84057,54.3679,46.456,1.1703,54.0310,54.7044,True,0.7209,0.4575,1.5757,0.6660,0.7804,True
76,user_active_degree,standard,2_14_day_new,32521,47.6277,46.456,1.0252,47.0852,48.1708,True,0.4520,0.4575,0.9880,0.3847,0.5310,False
77,user_active_degree,standard,low_active,6788,57.5869,46.456,1.2396,56.4073,58.7580,True,0.7955,0.4575,1.7388,0.6102,1.0365,True
78,user_active_degree,standard,single_low_active,2911,51.3569,46.456,1.1055,49.5406,53.1696,True,0.8245,0.4575,1.8022,0.5547,1.2239,True
79,video_orientation,random,vertical,887495,17.9827,17.616,1.0208,17.9030,18.0628,True,0.0971,0.0942,1.0308,0.0909,0.1038,False
80,video_orientation,random,horizontal,281763,16.8081,17.616,0.9541,16.6705,16.9466,False,0.0852,0.0942,0.9045,0.0751,0.0967,False
81,video_orientation,random,square,16791,11.7861,17.616,0.6691,11.3071,12.2826,False,0.0893,0.0942,0.9480,0.0541,0.1474,False
82,video_orientation,standard,vertical,1071820,45.1773,46.456,0.9725,45.0831,45.2715,False,0.4541,0.4575,0.9926,0.4415,0.4670,False
83,video_orientation,standard,horizontal,318293,51.2694,46.456,1.1036,51.0958,51.4431,True,0.4549,0.4575,0.9943,0.4321,0.4789,False
84,video_orientation,standard,square,21537,38.9562,46.456,0.8386,38.3070,39.6094,False,0.6640,0.4575,1.4514,0.5640,0.7816,True
85,video_type,random,NORMAL,1174235,17.6222,17.616,1.0004,17.5534,17.6912,False,0.0944,0.0942,1.0021,0.0890,0.1002,False
86,video_type,random,AD,11691,16.8164,17.616,0.9546,16.1493,17.5052,False,0.0684,0.0942,0.7261,0.0347,0.1350,False
87,video_type,standard,NORMAL,1393938,46.4199,46.456,0.9992,46.3371,46.5027,False,0.4566,0.4575,0.9980,0.4456,0.4679,False
88,video_type,standard,AD,15494,48.5543,46.456,1.0452,47.7678,49.3415,True,0.5809,0.4575,1.2697,0.4728,0.7134,True
89,video_type,standard,UNKNOWN,2218,54.5086,46.456,1.1733,52.4302,56.5714,True,0.1353,0.4575,0.2957,0.0460,0.3969,False
90,video_upload_type,random,LongImport,458185,18.2256,17.616,1.0346,18.1141,18.3377,True,0.0947,0.0942,1.0053,0.0862,0.1041,False
91,video_upload_type,random,Web,378724,18.0834,17.616,1.0265,17.9611,18.2063,True,0.0834,0.0942,0.8854,0.0747,0.0932,False
92,video_upload_type,random,ShortImport,143707,17.4918,17.616,0.9929,17.2963,17.6891,False,0.1225,0.0942,1.3004,0.1057,0.1419,True
93,video_upload_type,random,Kmovie,135817,17.6083,17.616,0.9996,17.4066,17.8117,False,0.0965,0.0942,1.0244,0.0813,0.1144,False
94,video_upload_type,random,LongPicture,21597,7.9039,17.616,0.4487,7.5515,8.2712,False,0.0880,0.0942,0.9342,0.0563,0.1374,False
95,video_upload_type,random,UNKNOWN,12329,16.4652,17.616,0.9347,15.8211,17.1303,False,0.0892,0.0942,0.9469,0.0498,0.1597,False
96,video_upload_type,random,PictureSet,11561,6.8766,17.616,0.3904,6.4295,7.3523,False,0.0692,0.0942,0.7346,0.0351,0.1365,False
97,video_upload_type,random,LongCamera,10336,12.1517,17.616,0.6898,11.5358,12.7957,False,0.0387,0.0942,0.4108,0.0151,0.0995,False
98,video_upload_type,random,ShortCamera,6971,12.8389,17.616,0.7288,12.0740,13.6447,False,0.0574,0.0942,0.6093,0.0223,0.1475,False
99,video_upload_type,random,ShareFromOtherApp,4576,21.3287,17.616,1.2108,20.1661,22.5393,True,0.2404,0.0942,2.5520,0.1343,0.4300,True
100,video_upload_type,random,FollowShoot,1613,10.2294,17.616,0.5807,8.8437,11.8040,False,0.0620,0.0942,0.6582,0.0109,0.3504,False
101,video_upload_type,standard,LongImport,612193,47.6774,46.456,1.0263,47.5523,47.8026,True,0.4552,0.4575,0.9950,0.4387,0.4724,False
102,video_upload_type,standard,Web,421648,50.2509,46.456,1.0817,50.1000,50.4018,True,0.4686,0.4575,1.0243,0.4485,0.4897,False
103,video_upload_type,standard,ShortImport,200877,41.3069,46.456,0.8892,41.0917,41.5224,False,0.4784,0.4575,1.0457,0.4492,0.5095,False
104,video_upload_type,standard,Kmovie,118583,43.0719,46.456,0.9272,42.7903,43.3540,False,0.3744,0.4575,0.8184,0.3412,0.4108,False
105,video_upload_type,standard,LongPicture,21548,23.1715,46.456,0.4988,22.6130,23.7396,False,0.6033,0.4575,1.3187,0.5083,0.7159,True
106,video_upload_type,standard,UNKNOWN,17218,44.9936,46.456,0.9685,44.2517,45.7377,False,0.5692,0.4575,1.2442,0.4673,0.6931,True
107,video_upload_type,standard,ShortCamera,7411,24.6121,46.456,0.5298,23.6447,25.6058,False,0.3373,0.4575,0.7373,0.2286,0.4975,False
108,video_upload_type,standard,ShareFromOtherApp,4201,34.2776,46.456,0.7379,32.8572,35.7266,False,0.1904,0.4575,0.4162,0.0965,0.3753,False
109,video_upload_type,standard,PictureSet,4039,17.8014,46.456,0.3832,16.6525,19.0116,False,0.3466,0.4575,0.7576,0.2066,0.5810,False
110,video_upload_type,standard,LongCamera,3743,32.7812,46.456,0.7056,31.2957,34.3020,False,0.3740,0.4575,0.8175,0.2229,0.6269,False

In [79]:
# Comparing post-click segment performance within each traffic source

def build_post_click_segment_conversion_within_traffic_source(dataframe, segment_fields, minimum_clicked_impression_count):
    clicked_dataframe = dataframe.loc[dataframe["is_click"] == 1].copy()

    traffic_source_post_click_baseline = (clicked_dataframe
                                          .groupby("traffic_source", as_index = False)
                                          .agg(clicked_impression_count_total = ("user_id", "size"),
                                               traffic_source_click_to_meaningful_watch_rate = ("is_meaningful_watch", "mean"),
                                               traffic_source_click_to_profile_enter_rate = ("is_profile_enter", "mean"),
                                               traffic_source_click_to_like_rate = ("is_like", "mean"),
                                               traffic_source_click_to_high_value_engagement_rate = ("is_high_value_engagement", "mean")
        )
    )

    comparison_tables = []

    for field_name in segment_fields:
        segment_summary = (
            clicked_dataframe
            .groupby(["traffic_source", field_name], dropna = False, as_index = False)
            .agg(clicked_impression_count = ("user_id", "size"),
                 meaningful_watch_count = ("is_meaningful_watch", "sum"),
                 profile_enter_count = ("is_profile_enter", "sum"),
                 like_count = ("is_like", "sum"),
                 high_value_engagement_count = ("is_high_value_engagement", "sum")
            )
            .rename(columns = {field_name: "segment_value"})
        )

        segment_summary = segment_summary.loc[
            segment_summary["clicked_impression_count"] >= minimum_clicked_impression_count
        ].copy()

        segment_summary["click_to_meaningful_watch_rate_percent"] = (
            segment_summary["meaningful_watch_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_profile_enter_rate_percent"] = (
            segment_summary["profile_enter_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_like_rate_percent"] = (
            segment_summary["like_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        segment_summary["click_to_high_value_engagement_rate_percent"] = (
            segment_summary["high_value_engagement_count"] / segment_summary["clicked_impression_count"] * 100
        ).round(4)

        # Estimating confidence bounds for post-click high-value conversion
        high_value_interval = segment_summary.apply(
            lambda row: wilson_interval(
                row["high_value_engagement_count"],
                row["clicked_impression_count"]
            ),
            axis = 1
        )

        segment_summary["click_to_high_value_engagement_rate_center"] = [
            interval[0] for interval in high_value_interval
        ]
        segment_summary["click_to_high_value_engagement_rate_margin"] = [
            interval[1] for interval in high_value_interval
        ]

        segment_summary["click_to_high_value_engagement_rate_lower_bound_percent"] = (
            (
                segment_summary["click_to_high_value_engagement_rate_center"] - segment_summary["click_to_high_value_engagement_rate_margin"]
            ) * 100
        ).round(4)

        segment_summary["click_to_high_value_engagement_rate_upper_bound_percent"] = (
            (
                segment_summary["click_to_high_value_engagement_rate_center"] + segment_summary["click_to_high_value_engagement_rate_margin"]
            ) * 100
        ).round(4)

        segment_summary = segment_summary.merge(traffic_source_post_click_baseline,
                                                on = "traffic_source",
                                                how = "left"
        )

        segment_summary["traffic_source_click_to_high_value_engagement_rate_percent"] = (
            segment_summary["traffic_source_click_to_high_value_engagement_rate"] * 100
        ).round(4)

        segment_summary["click_to_high_value_engagement_rate_lift_within_traffic_source"] = (
            segment_summary["click_to_high_value_engagement_rate_percent"] 
            / segment_summary["traffic_source_click_to_high_value_engagement_rate_percent"]
        ).round(4)

        segment_summary["click_to_high_value_engagement_confidently_above_traffic_source"] = (
            segment_summary["click_to_high_value_engagement_rate_lower_bound_percent"] 
            > segment_summary["traffic_source_click_to_high_value_engagement_rate_percent"]
        )

        segment_summary.insert(0, "segment_field", field_name)
        comparison_tables.append(segment_summary)

    return (pd.concat(comparison_tables, ignore_index = True)
            .sort_values(["segment_field", "traffic_source", "clicked_impression_count"],
                         ascending = [True, True, False]
            )
            .reset_index(drop = True)
    )


post_click_segment_conversion_within_traffic_source = build_post_click_segment_conversion_within_traffic_source(
    impression_analysis_base,
    segment_fields,
    minimum_clicked_impression_count = 500
)

post_click_segment_conversion_within_traffic_source[
    [
        "segment_field",
        "traffic_source",
        "segment_value",
        "clicked_impression_count",
        "click_to_meaningful_watch_rate_percent",
        "click_to_profile_enter_rate_percent",
        "click_to_like_rate_percent",
        "click_to_high_value_engagement_rate_percent",
        "traffic_source_click_to_high_value_engagement_rate_percent",
        "click_to_high_value_engagement_rate_lift_within_traffic_source",
        "click_to_high_value_engagement_rate_lower_bound_percent",
        "click_to_high_value_engagement_rate_upper_bound_percent",
        "click_to_high_value_engagement_confidently_above_traffic_source"
    ]
]

,segment_field,traffic_source,segment_value,clicked_impression_count,click_to_meaningful_watch_rate_percent,click_to_profile_enter_rate_percent,click_to_like_rate_percent,click_to_high_value_engagement_rate_percent,traffic_source_click_to_high_value_engagement_rate_percent,click_to_high_value_engagement_rate_lift_within_traffic_source,click_to_high_value_engagement_rate_lower_bound_percent,click_to_high_value_engagement_rate_upper_bound_percent,click_to_high_value_engagement_confidently_above_traffic_source
0,fans_user_num_range,random,"[10,100)",80329,48.2839,1.9022,1.5785,0.4880,0.4351,1.1216,0.4421,0.5386,True
1,fans_user_num_range,random,"[100,1k)",66715,48.1826,2.2634,2.0355,0.4392,0.4351,1.0094,0.3918,0.4923,False
2,fans_user_num_range,random,"[1,10)",40665,47.8274,1.8075,1.3919,0.4131,0.4351,0.9494,0.3553,0.4803,False
3,fans_user_num_range,random,"[1k,5k)",11271,47.0411,2.6173,1.8543,0.3549,0.4351,0.8157,0.2607,0.4829,False
4,fans_user_num_range,random,0,8796,47.4989,1.8986,0.7390,0.1705,0.4351,0.3919,0.1034,0.2812,False
5,fans_user_num_range,random,"[1w,10w)",561,47.0588,4.4563,1.0695,0.0000,0.4351,0.0000,0.0000,0.6801,False
6,fans_user_num_range,random,"[5k,1w)",510,45.8824,2.7451,0.5882,0.1961,0.4351,0.4507,0.0346,1.1022,False
7,fans_user_num_range,standard,"[10,100)",252419,72.3000,4.5579,3.1685,0.9496,0.9200,1.0322,0.9125,0.9882,False
8,fans_user_num_range,standard,"[100,1k)",218909,71.3424,5.7275,4.0286,0.9584,0.9200,1.0417,0.9184,1.0001,False
9,fans_user_num_range,standard,"[1,10)",120730,73.1939,4.2483,2.7284,0.8117,0.9200,0.8823,0.7627,0.8639,False
10,fans_user_num_range,standard,"[1k,5k)",34286,70.1919,5.9879,4.6200,1.0500,0.9200,1.1413,0.9474,1.1635,True
11,fans_user_num_range,standard,0,25108,72.8652,3.9350,1.5533,0.6412,0.9200,0.6970,0.5498,0.7478,False
12,fans_user_num_range,standard,"[5k,1w)",2155,70.3480,3.8979,3.8979,0.7889,0.9200,0.8575,0.4931,1.2598,False
13,fans_user_num_range,standard,"[1w,10w)",1922,70.5515,5.2029,3.1738,0.9365,0.9200,1.0179,0.5932,1.4756,False
14,follow_user_num_range,random,500+,47728,48.9147,2.2293,2.7384,0.6139,0.4351,1.4109,0.5477,0.6881,True
15,follow_user_num_range,random,"(10,50]",37397,47.7311,1.9039,0.9493,0.3637,0.4351,0.8359,0.3075,0.4300,False
16,follow_user_num_range,random,"(250,500]",32609,47.8150,2.0148,1.6959,0.4569,0.4351,1.0501,0.3893,0.5362,False
17,follow_user_num_range,random,"(50,100]",28981,48.1902,2.0669,1.2732,0.3830,0.4351,0.8803,0.3182,0.4610,False
18,follow_user_num_range,random,"(150,250]",28349,47.7971,2.0988,1.6826,0.3492,0.4351,0.8026,0.2870,0.4249,False
19,follow_user_num_range,random,"(100,150]",19458,47.4715,1.9581,1.5212,0.4214,0.4351,0.9685,0.3397,0.5227,False
20,follow_user_num_range,random,"(0,10]",12931,47.5369,1.7941,0.9357,0.2939,0.4351,0.6755,0.2142,0.4031,False
21,follow_user_num_range,random,0,1481,48.3457,2.9710,0.2701,0.0675,0.4351,0.1551,0.0119,0.3815,False
22,follow_user_num_range,standard,500+,134373,72.4669,5.1796,5.4460,1.3485,0.9200,1.4658,1.2882,1.4116,True
23,follow_user_num_range,standard,"(10,50]",122510,72.1141,4.6584,1.9345,0.7297,0.9200,0.7932,0.6836,0.7790,False
24,follow_user_num_range,standard,"(250,500]",103705,71.8124,5.1984,3.9352,0.9787,0.9200,1.0638,0.9206,1.0405,True
25,follow_user_num_range,standard,"(50,100]",100264,71.9999,4.9719,2.5572,0.7021,0.9200,0.7632,0.6523,0.7558,False
26,follow_user_num_range,standard,"(150,250]",88730,72.2574,5.0885,3.6481,0.9478,0.9200,1.0302,0.8862,1.0137,False
27,follow_user_num_range,standard,"(100,150]",64704,71.8348,4.7153,3.1837,0.8052,0.9200,0.8752,0.7392,0.8770,False
28,follow_user_num_range,standard,"(0,10]",37716,70.9089,4.2847,1.6677,0.6098,0.9200,0.6628,0.5361,0.6936,False
29,follow_user_num_range,standard,0,3794,72.6410,5.2188,0.6062,0.4217,0.9200,0.4584,0.2598,0.6840,False
30,friend_user_num_range,random,"[5,30)",59410,48.2966,2.0502,1.6748,0.4949,0.4351,1.1374,0.4416,0.5546,True
31,friend_user_num_range,random,"[1,5)",39944,48.5880,1.8351,1.4570,0.4857,0.4351,1.1163,0.4221,0.5588,False
32,friend_user_num_range,random,250+,26917,47.7133,2.3777,2.1251,0.4310,0.4351,0.9906,0.3595,0.5166,False
33,friend_user_num_range,random,0,25225,47.5520,1.7879,0.8325,0.2735,0.4351,0.6286,0.2162,0.3460,False
34,friend_user_num_range,random,"[30,60)",20543,47.8508,1.9763,1.4409,0.3992,0.4351,0.9175,0.3217,0.4952,False
35,friend_user_num_range,random,"[60,120)",19649,48.1399,2.3004,2.3564,0.4377,0.4351,1.0060,0.3546,0.5402,False
36,friend_user_num_range,random,"[120,250)",17246,47.4081,2.2266,2.1106,0.3943,0.4351,0.9062,0.3112,0.4995,False
37,friend_user_num_range,standard,"[5,30)",184833,72.4616,4.7210,3.1845,0.9436,0.9200,1.0257,0.9005,0.9887,False
38,friend_user_num_range,standard,"[1,5)",121871,72.7794,4.3366,2.7365,0.8271,0.9200,0.8990,0.7778,0.8795,False
39,friend_user_num_range,standard,250+,79648,70.3169,5.8081,4.9129,1.1049,0.9200,1.2010,1.0346,1.1799,True
40,friend_user_num_range,standard,0,74869,72.7070,4.1820,1.5975,0.7106,0.9200,0.7724,0.6529,0.7733,False
41,friend_user_num_range,standard,"[60,120)",69728,71.6627,5.6892,4.2408,0.9408,0.9200,1.0226,0.8718,1.0152,False
42,friend_user_num_range,standard,"[30,60)",67910,72.0056,5.2246,3.4104,0.9174,0.9200,0.9972,0.8484,0.9919,False
43,friend_user_num_range,standard,"[120,250)",56937,71.2033,5.5149,4.7052,1.0362,0.9200,1.1263,0.9563,1.1228,True
44,music_type,random,9.0,185165,48.0814,2.0474,1.6315,0.4337,0.4351,0.9968,0.4047,0.4646,False
45,music_type,random,4.0,15939,46.8411,2.1394,2.0829,0.5458,0.4351,1.2544,0.4428,0.6727,True
46,music_type,random,NaN,6389,50.8217,2.1600,1.6121,0.2504,0.4351,0.5755,0.1542,0.4064,False
47,music_type,random,8.0,997,44.2327,0.9027,1.5045,0.2006,0.4351,0.4610,0.0550,0.7285,False
48,music_type,standard,9.0,592183,72.4335,5.0116,3.3172,0.9168,0.9200,0.9965,0.8928,0.9414,False
49,music_type,standard,4.0,39555,66.4442,4.2346,4.9096,0.9885,0.9200,1.0745,0.8956,1.0909,False
50,music_type,standard,NaN,22709,72.5175,4.2935,2.7742,0.8103,0.9200,0.8808,0.7017,0.9355,False
51,music_type,standard,8.0,840,62.6190,7.7381,2.3810,1.6667,0.9200,1.8116,0.9953,2.7781,True
52,register_days_range,random,730+,145982,48.0100,2.0735,1.4851,0.3987,0.4351,0.9163,0.3676,0.4323,False
53,register_days_range,random,366-730,29978,48.2921,2.0782,1.8614,0.4303,0.4351,0.9890,0.3623,0.5110,False
54,register_days_range,random,181-365,15784,47.9726,2.0084,2.1541,0.6209,0.4351,1.4270,0.5098,0.7560,True
55,register_days_range,random,91-180,9257,48.1906,2.0309,1.9553,0.6266,0.4351,1.4401,0.4850,0.8090,True
56,register_days_range,random,61-90,3547,48.2661,1.7198,2.3118,0.5357,0.4351,1.2312,0.3432,0.8352,False
57,register_days_range,random,31-60,3063,48.6778,1.7303,3.4280,0.6203,0.4351,1.4256,0.3975,0.9668,False
58,register_days_range,random,15-30,1321,45.7229,1.1355,3.6336,0.3028,0.4351,0.6959,0.1178,0.7760,False
59,register_days_range,standard,730+,470476,71.6336,5.0434,3.0484,0.8196,0.9200,0.8909,0.7942,0.8458,False
60,register_days_range,standard,366-730,88994,72.5869,4.9104,4.0553,1.0282,0.9200,1.1176,0.9640,1.0966,True
61,register_days_range,standard,181-365,50296,73.2881,4.6505,4.9785,1.2884,0.9200,1.4004,1.1935,1.3907,True
62,register_days_range,standard,91-180,25944,73.8784,4.3401,4.2977,1.3452,0.9200,1.4622,1.2121,1.4928,True
63,register_days_range,standard,61-90,9204,74.2286,4.2156,2.9770,1.2603,0.9200,1.3699,1.0519,1.5094,True
64,register_days_range,standard,31-60,8882,73.8235,4.3909,4.2333,1.3173,0.9200,1.4318,1.1003,1.5763,True
65,register_days_range,standard,15-30,1992,72.1888,4.0663,2.8614,1.6064,0.9200,1.7461,1.1402,2.2590,True
66,user_active_degree,random,full_active,140974,47.8954,2.1188,1.5145,0.4072,0.4351,0.9359,0.3752,0.4418,False
67,user_active_degree,random,high_active,44760,48.9879,2.0040,1.9638,0.5206,0.4351,1.1965,0.4580,0.5916,True
68,user_active_degree,random,middle_active,16370,46.4936,1.7776,2.1319,0.4643,0.4351,1.0671,0.3711,0.5807,False
69,user_active_degree,random,2_14_day_new,4270,47.7752,1.5691,2.0375,0.3981,0.4351,0.9150,0.2487,0.6367,False
70,user_active_degree,random,low_active,2023,50.5190,1.5324,1.4829,0.3955,0.4351,0.9090,0.2005,0.7784,False
71,user_active_degree,standard,full_active,471349,71.5604,5.0131,3.0107,0.8654,0.9200,0.9407,0.8393,0.8922,False
72,user_active_degree,standard,high_active,117118,73.4960,4.6594,4.2282,1.0075,0.9200,1.0951,0.9519,1.0664,True
73,user_active_degree,standard,middle_active,45700,73.0853,5.0306,5.1357,1.2276,0.9200,1.3343,1.1306,1.3327,True
74,user_active_degree,standard,2_14_day_new,15489,72.3417,4.6485,3.2216,0.8910,0.9200,0.9685,0.7547,1.0516,False
75,user_active_degree,standard,low_active,3909,73.8296,4.9629,5.5001,1.0744,0.9200,1.1678,0.7959,1.4491,False
76,user_active_degree,standard,single_low_active,1495,73.8462,5.2174,4.1472,1.4047,0.9200,1.5268,0.9206,2.1379,True
77,video_orientation,random,vertical,159596,48.2963,2.0677,1.6178,0.4355,0.4351,1.0009,0.4043,0.4690,False
78,video_orientation,random,horizontal,47359,47.3975,1.9827,1.7652,0.4223,0.4351,0.9706,0.3678,0.4849,False
79,video_orientation,random,square,1979,44.3658,2.2739,3.2340,0.7074,0.4351,1.6258,0.4219,1.1840,False
80,video_orientation,standard,vertical,484219,72.0007,4.7912,3.3237,0.9341,0.9200,1.0153,0.9074,0.9616,False
81,video_orientation,standard,horizontal,163187,72.7203,5.3907,3.3373,0.8463,0.9200,0.9199,0.8030,0.8919,False
82,video_orientation,standard,square,8390,61.6091,5.0775,8.8439,1.5375,0.9200,1.6712,1.2956,1.8239,True
83,video_type,random,NORMAL,206926,48.0288,2.0447,1.6697,0.4364,0.4351,1.0030,0.4089,0.4657,False
84,video_type,random,AD,1966,50.5595,2.5941,1.3733,0.3052,0.4351,0.7014,0.1399,0.6643,False
85,video_type,standard,NORMAL,647064,72.0031,4.9116,3.3995,0.9185,0.9200,0.9984,0.8955,0.9420,False
86,video_type,standard,AD,7523,74.4650,7.2577,3.6023,1.1565,0.9200,1.2571,0.9386,1.4242,True
87,video_type,standard,UNKNOWN,1209,80.3970,7.9404,1.1580,0.2481,0.9200,0.2697,0.0844,0.7270,False
88,video_upload_type,random,LongImport,83507,47.1565,2.1819,1.5759,0.4371,0.4351,1.0046,0.3946,0.4842,False
89,video_upload_type,random,Web,68486,48.1558,1.7697,1.5288,0.3548,0.4351,0.8154,0.3130,0.4022,False
90,video_upload_type,random,ShortImport,25137,54.7440,2.2914,2.2278,0.5569,0.4351,1.2799,0.4722,0.6568,True
91,video_upload_type,random,Kmovie,23915,46.6653,1.9109,1.5388,0.4474,0.4351,1.0283,0.3704,0.5403,False
92,video_upload_type,random,UNKNOWN,2030,50.5419,2.7586,1.3793,0.4433,0.4351,1.0188,0.2334,0.8405,False
93,video_upload_type,random,LongPicture,1707,26.8893,3.1634,5.0967,1.0545,0.4351,2.4236,0.6680,1.6607,True
94,video_upload_type,random,LongCamera,1256,39.8089,1.4331,1.3535,0.3185,0.4351,0.7320,0.1239,0.8160,False
95,video_upload_type,random,ShareFromOtherApp,976,48.3607,3.1762,1.3320,0.9221,0.4351,2.1193,0.4859,1.7432,True
96,video_upload_type,random,ShortCamera,895,43.7989,3.2402,0.8939,0.3352,0.4351,0.7704,0.1141,0.9809,False
97,video_upload_type,random,PictureSet,795,25.7862,3.0189,4.5283,1.0063,0.4351,2.3128,0.5108,1.9730,True
98,video_upload_type,standard,LongImport,291878,72.6177,5.0501,3.2962,0.9024,0.9200,0.9809,0.8688,0.9374,False
99,video_upload_type,standard,Web,211882,73.5329,5.1406,2.9450,0.8736,0.9200,0.9496,0.8349,0.9141,False
100,video_upload_type,standard,ShortImport,82976,70.7180,4.1398,4.7532,1.0533,0.9200,1.1449,0.9861,1.1251,True
101,video_upload_type,standard,Kmovie,51076,70.4068,4.2584,2.7958,0.8086,0.9200,0.8789,0.7345,0.8901,False
102,video_upload_type,standard,UNKNOWN,7747,73.5898,7.1512,3.5369,1.2005,0.9200,1.3049,0.9810,1.4683,True
103,video_upload_type,standard,LongPicture,4993,32.0449,5.4076,11.2157,2.2632,0.9200,2.4600,1.8859,2.7139,True
104,video_upload_type,standard,ShortCamera,1824,39.0351,9.1557,4.2215,1.2610,0.9200,1.3707,0.8417,1.8851,False
105,video_upload_type,standard,ShareFromOtherApp,1440,70.3472,8.8889,3.1944,0.5556,0.9200,0.6039,0.2818,1.0925,False
106,video_upload_type,standard,LongCamera,1227,62.9992,2.2005,2.9340,0.8150,0.9200,0.8859,0.4433,1.4937,False
107,video_upload_type,standard,PictureSet,719,36.4395,4.8679,7.6495,1.8081,0.9200,1.9653,1.0596,3.0687,True

In [80]:
# Filtering pre-click priority segments to credible opportunities

minimum_priority_impression_count = 10000

pre_click_priority_segments = (
    segment_rate_comparison_within_traffic_source[
        [
            "segment_field",
            "traffic_source",
            "segment_value",
            "impression_count",
            "click_rate_percent",
            "traffic_source_click_rate_percent",
            "click_rate_lift_within_traffic_source",
            "click_rate_lower_bound_percent",
            "click_rate_upper_bound_percent",
            "click_rate_confidently_above_traffic_source",
            "high_value_engagement_rate_percent",
            "traffic_source_high_value_engagement_rate_percent",
            "high_value_engagement_rate_lift_within_traffic_source",
            "high_value_engagement_rate_lower_bound_percent",
            "high_value_engagement_rate_upper_bound_percent",
            "high_value_engagement_rate_confidently_above_traffic_source"
        ]
    ]
    .loc[lambda frame: frame["impression_count"] >= minimum_priority_impression_count]
    .loc[
        lambda frame:
        frame["click_rate_confidently_above_traffic_source"] | frame["high_value_engagement_rate_confidently_above_traffic_source"]
    ]
    .sort_values(
        [
            "high_value_engagement_rate_lift_within_traffic_source",
            "click_rate_lift_within_traffic_source",
            "impression_count"
        ],
        ascending = [False, False, False]
    )
    .reset_index(drop = True)
)

pre_click_priority_segments

,segment_field,traffic_source,segment_value,impression_count,click_rate_percent,traffic_source_click_rate_percent,click_rate_lift_within_traffic_source,click_rate_lower_bound_percent,click_rate_upper_bound_percent,click_rate_confidently_above_traffic_source,high_value_engagement_rate_percent,traffic_source_high_value_engagement_rate_percent,high_value_engagement_rate_lift_within_traffic_source,high_value_engagement_rate_lower_bound_percent,high_value_engagement_rate_upper_bound_percent,high_value_engagement_rate_confidently_above_traffic_source
0,register_days_range,random,31-60,15095,20.2915,17.616,1.1519,19.6575,20.9406,True,0.1590,0.0942,1.6879,0.1069,0.2365,True
1,register_days_range,standard,31-60,16916,52.5065,46.456,1.1302,51.7535,53.2584,True,0.7626,0.4575,1.6669,0.6422,0.9053,True
2,register_days_range,standard,91-180,49566,52.3423,46.456,1.1267,51.9025,52.7818,True,0.7485,0.4575,1.6361,0.6763,0.8283,True
3,follow_user_num_range,standard,500+,279008,48.1610,46.456,1.0367,47.9756,48.3464,True,0.7215,0.4575,1.5770,0.6908,0.7536,True
4,user_active_degree,standard,middle_active,84057,54.3679,46.456,1.1703,54.0310,54.7044,True,0.7209,0.4575,1.5757,0.6660,0.7804,True
5,register_days_range,standard,61-90,16879,54.5293,46.456,1.1738,53.7771,55.2794,True,0.7109,0.4575,1.5539,0.5949,0.8494,True
6,register_days_range,standard,181-365,95789,52.5071,46.456,1.1303,52.1907,52.8232,True,0.7036,0.4575,1.5379,0.6526,0.7586,True
7,register_days_range,random,91-180,48134,19.2317,17.616,1.0917,18.8821,19.5863,True,0.1433,0.0942,1.5212,0.1133,0.1814,True
8,follow_user_num_range,random,500+,258413,18.4697,17.616,1.0485,18.3205,18.6197,True,0.1412,0.0942,1.4989,0.1275,0.1565,True
9,video_orientation,standard,square,21537,38.9562,46.456,0.8386,38.3070,39.6094,False,0.6640,0.4575,1.4514,0.5640,0.7816,True
10,register_days_range,random,181-365,83818,18.8313,17.616,1.0690,18.5680,19.0974,True,0.1336,0.0942,1.4183,0.1111,0.1607,True
11,video_upload_type,standard,LongPicture,21548,23.1715,46.456,0.4988,22.6130,23.7396,False,0.6033,0.4575,1.3187,0.5083,0.7159,True
12,video_upload_type,random,ShortImport,143707,17.4918,17.616,0.9929,17.2963,17.6891,False,0.1225,0.0942,1.3004,0.1057,0.1419,True
13,user_active_degree,random,high_active,235289,19.0234,17.616,1.0799,18.8653,19.1825,True,0.1224,0.0942,1.2994,0.1091,0.1374,True
14,video_type,standard,AD,15494,48.5543,46.456,1.0452,47.7678,49.3415,True,0.5809,0.4575,1.2697,0.4728,0.7134,True
15,video_upload_type,standard,UNKNOWN,17218,44.9936,46.456,0.9685,44.2517,45.7377,False,0.5692,0.4575,1.2442,0.4673,0.6931,True
16,register_days_range,random,61-90,17968,19.7407,17.616,1.1206,19.1651,20.3291,True,0.1169,0.0942,1.2410,0.0765,0.1786,False
17,user_active_degree,standard,high_active,227174,51.5543,46.456,1.1097,51.3488,51.7598,True,0.5590,0.4575,1.2219,0.5292,0.5906,True
18,register_days_range,standard,366-730,179149,49.6760,46.456,1.0693,49.4444,49.9075,True,0.5532,0.4575,1.2092,0.5199,0.5886,True
19,friend_user_num_range,standard,250+,176553,45.1128,46.456,0.9711,44.8808,45.3450,False,0.5364,0.4575,1.1725,0.5034,0.5715,True
20,user_active_degree,random,middle_active,82845,19.7598,17.616,1.1217,19.4900,20.0323,True,0.1098,0.0942,1.1656,0.0895,0.1348,False
21,friend_user_num_range,random,"[5,30)",334148,17.7795,17.616,1.0093,17.6503,17.9096,True,0.1077,0.0942,1.1433,0.0972,0.1194,True
22,friend_user_num_range,random,250+,148316,18.1484,17.616,1.0302,17.9531,18.3454,True,0.1052,0.0942,1.1168,0.0899,0.1230,False
23,register_days_range,random,366-730,155187,19.3173,17.616,1.0966,19.1217,19.5145,True,0.1044,0.0942,1.1083,0.0895,0.1217,False
24,fans_user_num_range,random,"[10,100)",457791,17.5471,17.616,0.9961,17.4372,17.6575,False,0.1044,0.0942,1.1083,0.0955,0.1142,True
25,user_active_degree,random,2_14_day_new,23214,18.3941,17.616,1.0442,17.9009,18.8977,True,0.1034,0.0942,1.0977,0.0695,0.1538,False
26,friend_user_num_range,standard,"[120,250)",127785,44.5569,46.456,0.9591,44.2845,44.8296,False,0.4969,0.4575,1.0861,0.4598,0.5370,True
27,fans_user_num_range,standard,"[10,100)",533497,47.3140,46.456,1.0185,47.1801,47.4480,True,0.4748,0.4575,1.0378,0.4567,0.4936,False
28,video_orientation,random,vertical,887495,17.9827,17.616,1.0208,17.9030,18.0628,True,0.0971,0.0942,1.0308,0.0909,0.1038,False
29,follow_user_num_range,standard,"(150,250]",188935,46.9632,46.456,1.0109,46.7383,47.1883,True,0.4689,0.4575,1.0249,0.4391,0.5008,False
30,video_upload_type,standard,Web,421648,50.2509,46.456,1.0817,50.1000,50.4018,True,0.4686,0.4575,1.0243,0.4485,0.4897,False
31,friend_user_num_range,standard,"[5,30)",391901,47.1632,46.456,1.0152,47.0069,47.3195,True,0.4682,0.4575,1.0234,0.4473,0.4901,False
32,music_type,standard,9.0,1249793,47.3825,46.456,1.0199,47.2950,47.4700,True,0.4637,0.4575,1.0136,0.4519,0.4757,False
33,video_upload_type,random,LongImport,458185,18.2256,17.616,1.0346,18.1141,18.3377,True,0.0947,0.0942,1.0053,0.0862,0.1041,False
34,music_type,random,9.0,1042841,17.7558,17.616,1.0079,17.6826,17.8293,True,0.0946,0.0942,1.0042,0.0889,0.1007,False
35,fans_user_num_range,random,"[1,10)",225066,18.0680,17.616,1.0257,17.9096,18.2275,True,0.0942,0.0942,1.0000,0.0823,0.1077,False
36,video_upload_type,standard,LongImport,612193,47.6774,46.456,1.0263,47.5523,47.8026,True,0.4552,0.4575,0.9950,0.4387,0.4724,False
37,video_orientation,standard,horizontal,318293,51.2694,46.456,1.1036,51.0958,51.4431,True,0.4549,0.4575,0.9943,0.4321,0.4789,False
38,user_active_degree,standard,2_14_day_new,32521,47.6277,46.456,1.0252,47.0852,48.1708,True,0.4520,0.4575,0.9880,0.3847,0.5310,False
39,friend_user_num_range,standard,"[1,5)",251998,48.3619,46.456,1.0410,48.1668,48.5570,True,0.4302,0.4575,0.9403,0.4054,0.4565,False
40,fans_user_num_range,standard,"[1,10)",242643,49.7562,46.456,1.0710,49.5573,49.9552,True,0.4290,0.4575,0.9377,0.4038,0.4558,False
41,video_upload_type,random,Web,378724,18.0834,17.616,1.0265,17.9611,18.2063,True,0.0834,0.0942,0.8854,0.0747,0.0932,False
42,music_type,standard,NaN,48332,46.9854,46.456,1.0114,46.5407,47.4306,True,0.4014,0.4575,0.8774,0.3488,0.4618,False
43,friend_user_num_range,standard,0,155603,48.1154,46.456,1.0357,47.8672,48.3637,True,0.3637,0.4575,0.7950,0.3350,0.3949,False
44,fans_user_num_range,standard,0,51032,49.2005,46.456,1.0591,48.7668,49.6343,True,0.3488,0.4575,0.7624,0.3013,0.4038,False
45,music_type,random,NaN,30770,20.7637,17.616,1.1787,20.3142,21.2206,True,0.0715,0.0942,0.7590,0.0472,0.1082,False

In [81]:
# Filtering post-click priority segments to credible opportunities

minimum_priority_clicked_impression_count = 3000

post_click_priority_segments = (
    post_click_segment_conversion_within_traffic_source[
        [
            "segment_field",
            "traffic_source",
            "segment_value",
            "clicked_impression_count",
            "click_to_meaningful_watch_rate_percent",
            "click_to_profile_enter_rate_percent",
            "click_to_like_rate_percent",
            "click_to_high_value_engagement_rate_percent",
            "traffic_source_click_to_high_value_engagement_rate_percent",
            "click_to_high_value_engagement_rate_lift_within_traffic_source",
            "click_to_high_value_engagement_rate_lower_bound_percent",
            "click_to_high_value_engagement_rate_upper_bound_percent",
            "click_to_high_value_engagement_confidently_above_traffic_source"
        ]
    ]
    .loc[lambda frame: frame["clicked_impression_count"] >= minimum_priority_clicked_impression_count]
    .loc[lambda frame: frame["click_to_high_value_engagement_confidently_above_traffic_source"]]
    .sort_values(
        [
            "click_to_high_value_engagement_rate_lift_within_traffic_source",
            "clicked_impression_count"
        ],
        ascending = [False, False]
    )
    .reset_index(drop = True)
)

post_click_priority_segments

,segment_field,traffic_source,segment_value,clicked_impression_count,click_to_meaningful_watch_rate_percent,click_to_profile_enter_rate_percent,click_to_like_rate_percent,click_to_high_value_engagement_rate_percent,traffic_source_click_to_high_value_engagement_rate_percent,click_to_high_value_engagement_rate_lift_within_traffic_source,click_to_high_value_engagement_rate_lower_bound_percent,click_to_high_value_engagement_rate_upper_bound_percent,click_to_high_value_engagement_confidently_above_traffic_source
0,video_upload_type,standard,LongPicture,4993,32.0449,5.4076,11.2157,2.2632,0.9200,2.4600,1.8859,2.7139,True
1,video_orientation,standard,square,8390,61.6091,5.0775,8.8439,1.5375,0.9200,1.6712,1.2956,1.8239,True
2,follow_user_num_range,standard,500+,134373,72.4669,5.1796,5.4460,1.3485,0.9200,1.4658,1.2882,1.4116,True
3,register_days_range,standard,91-180,25944,73.8784,4.3401,4.2977,1.3452,0.9200,1.4622,1.2121,1.4928,True
4,register_days_range,random,91-180,9257,48.1906,2.0309,1.9553,0.6266,0.4351,1.4401,0.4850,0.8090,True
5,register_days_range,standard,31-60,8882,73.8235,4.3909,4.2333,1.3173,0.9200,1.4318,1.1003,1.5763,True
6,register_days_range,random,181-365,15784,47.9726,2.0084,2.1541,0.6209,0.4351,1.4270,0.5098,0.7560,True
7,follow_user_num_range,random,500+,47728,48.9147,2.2293,2.7384,0.6139,0.4351,1.4109,0.5477,0.6881,True
8,register_days_range,standard,181-365,50296,73.2881,4.6505,4.9785,1.2884,0.9200,1.4004,1.1935,1.3907,True
9,register_days_range,standard,61-90,9204,74.2286,4.2156,2.9770,1.2603,0.9200,1.3699,1.0519,1.5094,True
10,user_active_degree,standard,middle_active,45700,73.0853,5.0306,5.1357,1.2276,0.9200,1.3343,1.1306,1.3327,True
11,video_upload_type,standard,UNKNOWN,7747,73.5898,7.1512,3.5369,1.2005,0.9200,1.3049,0.9810,1.4683,True
12,video_upload_type,random,ShortImport,25137,54.7440,2.2914,2.2278,0.5569,0.4351,1.2799,0.4722,0.6568,True
13,video_type,standard,AD,7523,74.4650,7.2577,3.6023,1.1565,0.9200,1.2571,0.9386,1.4242,True
14,music_type,random,4.0,15939,46.8411,2.1394,2.0829,0.5458,0.4351,1.2544,0.4428,0.6727,True
15,friend_user_num_range,standard,250+,79648,70.3169,5.8081,4.9129,1.1049,0.9200,1.2010,1.0346,1.1799,True
16,user_active_degree,random,high_active,44760,48.9879,2.0040,1.9638,0.5206,0.4351,1.1965,0.4580,0.5916,True
17,video_upload_type,standard,ShortImport,82976,70.7180,4.1398,4.7532,1.0533,0.9200,1.1449,0.9861,1.1251,True
18,fans_user_num_range,standard,"[1k,5k)",34286,70.1919,5.9879,4.6200,1.0500,0.9200,1.1413,0.9474,1.1635,True
19,friend_user_num_range,random,"[5,30)",59410,48.2966,2.0502,1.6748,0.4949,0.4351,1.1374,0.4416,0.5546,True
20,friend_user_num_range,standard,"[120,250)",56937,71.2033,5.5149,4.7052,1.0362,0.9200,1.1263,0.9563,1.1228,True
21,fans_user_num_range,random,"[10,100)",80329,48.2839,1.9022,1.5785,0.4880,0.4351,1.1216,0.4421,0.5386,True
22,register_days_range,standard,366-730,88994,72.5869,4.9104,4.0553,1.0282,0.9200,1.1176,0.9640,1.0966,True
23,user_active_degree,standard,high_active,117118,73.4960,4.6594,4.2282,1.0075,0.9200,1.0951,0.9519,1.0664,True
24,follow_user_num_range,standard,"(250,500]",103705,71.8124,5.1984,3.9352,0.9787,0.9200,1.0638,0.9206,1.0405,True

In [82]:
# Combining pre-click and post-click opportunities into one view

priority_segment_opportunities = (
    pre_click_priority_segments[
        [
            "segment_field",
            "traffic_source",
            "segment_value",
            "impression_count",
            "click_rate_percent",
            "click_rate_lift_within_traffic_source",
            "high_value_engagement_rate_percent",
            "high_value_engagement_rate_lift_within_traffic_source",
            "click_rate_confidently_above_traffic_source",
            "high_value_engagement_rate_confidently_above_traffic_source"
        ]
    ]
    .merge(
        post_click_priority_segments[
            [
                "segment_field",
                "traffic_source",
                "segment_value",
                "clicked_impression_count",
                "click_to_high_value_engagement_rate_percent",
                "click_to_high_value_engagement_rate_lift_within_traffic_source"
            ]
        ],
        on = ["segment_field", "traffic_source", "segment_value"],
        how = "left"
    )
    .sort_values(
        [
            "high_value_engagement_rate_lift_within_traffic_source",
            "click_rate_lift_within_traffic_source",
            "impression_count"
        ],
        ascending = [False, False, False]
    )
    .reset_index(drop = True)
)

priority_segment_opportunities

,segment_field,traffic_source,segment_value,impression_count,click_rate_percent,click_rate_lift_within_traffic_source,high_value_engagement_rate_percent,high_value_engagement_rate_lift_within_traffic_source,click_rate_confidently_above_traffic_source,high_value_engagement_rate_confidently_above_traffic_source,clicked_impression_count,click_to_high_value_engagement_rate_percent,click_to_high_value_engagement_rate_lift_within_traffic_source
0,register_days_range,random,31-60,15095,20.2915,1.1519,0.1590,1.6879,True,True,NaN,NaN,NaN
1,register_days_range,standard,31-60,16916,52.5065,1.1302,0.7626,1.6669,True,True,8882.0,1.3173,1.4318
2,register_days_range,standard,91-180,49566,52.3423,1.1267,0.7485,1.6361,True,True,25944.0,1.3452,1.4622
3,follow_user_num_range,standard,500+,279008,48.1610,1.0367,0.7215,1.5770,True,True,134373.0,1.3485,1.4658
4,user_active_degree,standard,middle_active,84057,54.3679,1.1703,0.7209,1.5757,True,True,45700.0,1.2276,1.3343
5,register_days_range,standard,61-90,16879,54.5293,1.1738,0.7109,1.5539,True,True,9204.0,1.2603,1.3699
6,register_days_range,standard,181-365,95789,52.5071,1.1303,0.7036,1.5379,True,True,50296.0,1.2884,1.4004
7,register_days_range,random,91-180,48134,19.2317,1.0917,0.1433,1.5212,True,True,9257.0,0.6266,1.4401
8,follow_user_num_range,random,500+,258413,18.4697,1.0485,0.1412,1.4989,True,True,47728.0,0.6139,1.4109
9,video_orientation,standard,square,21537,38.9562,0.8386,0.6640,1.4514,False,True,8390.0,1.5375,1.6712
10,register_days_range,random,181-365,83818,18.8313,1.0690,0.1336,1.4183,True,True,15784.0,0.6209,1.4270
11,video_upload_type,standard,LongPicture,21548,23.1715,0.4988,0.6033,1.3187,False,True,4993.0,2.2632,2.4600
12,video_upload_type,random,ShortImport,143707,17.4918,0.9929,0.1225,1.3004,False,True,25137.0,0.5569,1.2799
13,user_active_degree,random,high_active,235289,19.0234,1.0799,0.1224,1.2994,True,True,44760.0,0.5206,1.1965
14,video_type,standard,AD,15494,48.5543,1.0452,0.5809,1.2697,True,True,7523.0,1.1565,1.2571
15,video_upload_type,standard,UNKNOWN,17218,44.9936,0.9685,0.5692,1.2442,False,True,7747.0,1.2005,1.3049
16,register_days_range,random,61-90,17968,19.7407,1.1206,0.1169,1.2410,True,False,NaN,NaN,NaN
17,user_active_degree,standard,high_active,227174,51.5543,1.1097,0.5590,1.2219,True,True,117118.0,1.0075,1.0951
18,register_days_range,standard,366-730,179149,49.6760,1.0693,0.5532,1.2092,True,True,88994.0,1.0282,1.1176
19,friend_user_num_range,standard,250+,176553,45.1128,0.9711,0.5364,1.1725,False,True,79648.0,1.1049,1.2010
20,user_active_degree,random,middle_active,82845,19.7598,1.1217,0.1098,1.1656,True,False,NaN,NaN,NaN
21,friend_user_num_range,random,"[5,30)",334148,17.7795,1.0093,0.1077,1.1433,True,True,59410.0,0.4949,1.1374
22,friend_user_num_range,random,250+,148316,18.1484,1.0302,0.1052,1.1168,True,False,NaN,NaN,NaN
23,register_days_range,random,366-730,155187,19.3173,1.0966,0.1044,1.1083,True,False,NaN,NaN,NaN
24,fans_user_num_range,random,"[10,100)",457791,17.5471,0.9961,0.1044,1.1083,False,True,80329.0,0.4880,1.1216
25,user_active_degree,random,2_14_day_new,23214,18.3941,1.0442,0.1034,1.0977,True,False,NaN,NaN,NaN
26,friend_user_num_range,standard,"[120,250)",127785,44.5569,0.9591,0.4969,1.0861,False,True,56937.0,1.0362,1.1263
27,fans_user_num_range,standard,"[10,100)",533497,47.3140,1.0185,0.4748,1.0378,True,False,NaN,NaN,NaN
28,video_orientation,random,vertical,887495,17.9827,1.0208,0.0971,1.0308,True,False,NaN,NaN,NaN
29,follow_user_num_range,standard,"(150,250]",188935,46.9632,1.0109,0.4689,1.0249,True,False,NaN,NaN,NaN
30,video_upload_type,standard,Web,421648,50.2509,1.0817,0.4686,1.0243,True,False,NaN,NaN,NaN
31,friend_user_num_range,standard,"[5,30)",391901,47.1632,1.0152,0.4682,1.0234,True,False,NaN,NaN,NaN
32,music_type,standard,9.0,1249793,47.3825,1.0199,0.4637,1.0136,True,False,NaN,NaN,NaN
33,video_upload_type,random,LongImport,458185,18.2256,1.0346,0.0947,1.0053,True,False,NaN,NaN,NaN
34,music_type,random,9.0,1042841,17.7558,1.0079,0.0946,1.0042,True,False,NaN,NaN,NaN
35,fans_user_num_range,random,"[1,10)",225066,18.0680,1.0257,0.0942,1.0000,True,False,NaN,NaN,NaN
36,video_upload_type,standard,LongImport,612193,47.6774,1.0263,0.4552,0.9950,True,False,NaN,NaN,NaN
37,video_orientation,standard,horizontal,318293,51.2694,1.1036,0.4549,0.9943,True,False,NaN,NaN,NaN
38,user_active_degree,standard,2_14_day_new,32521,47.6277,1.0252,0.4520,0.9880,True,False,NaN,NaN,NaN
39,friend_user_num_range,standard,"[1,5)",251998,48.3619,1.0410,0.4302,0.9403,True,False,NaN,NaN,NaN
40,fans_user_num_range,standard,"[1,10)",242643,49.7562,1.0710,0.4290,0.9377,True,False,NaN,NaN,NaN
41,video_upload_type,random,Web,378724,18.0834,1.0265,0.0834,0.8854,True,False,NaN,NaN,NaN
42,music_type,standard,NaN,48332,46.9854,1.0114,0.4014,0.8774,True,False,NaN,NaN,NaN
43,friend_user_num_range,standard,0,155603,48.1154,1.0357,0.3637,0.7950,True,False,NaN,NaN,NaN
44,fans_user_num_range,standard,0,51032,49.2005,1.0591,0.3488,0.7624,True,False,NaN,NaN,NaN
45,music_type,random,NaN,30770,20.7637,1.1787,0.0715,0.7590,True,False,NaN,NaN,NaN

In [83]:
# Preparing the click modeling dataset and feature scope

click_target_column = "is_click"

click_reference_columns = [
    "user_id", "video_id", "creator_user_id", "event_timestamp_ms", "event_date", "traffic_source"
]

click_predictor_columns = [
    "feed_tab_id",
    "user_active_degree",
    "is_video_author",
    "follow_user_num",
    "follow_user_num_range",
    "fans_user_num",
    "fans_user_num_range",
    "friend_user_num",
    "friend_user_num_range",
    "register_days",
    "register_days_range",
    "video_type",
    "video_upload_date",
    "video_upload_type",
    "video_width",
    "video_height",
    "video_orientation",
    "music_type",
    "video_age_days",
    "event_content_duration_ms"
]

click_model_dataset = (
    impression_analysis_base[
        click_reference_columns + click_predictor_columns + [click_target_column]
    ]
    .sort_values(["event_date", "event_timestamp_ms", "user_id", "video_id"])
    .reset_index(drop = True)
)

pd.DataFrame(
    {
        "metric_name": ["row_count",
                        "column_count",
                        "duplicate_event_key_count",
                        "missing_target_count"
        ],
        "value": [int(len(click_model_dataset)),
                  int(click_model_dataset.shape[1]),
                  int(
                      click_model_dataset.duplicated(
                          subset = ["user_id", "video_id", "event_timestamp_ms"]
                    ).sum()
                ),
                  int(click_model_dataset[click_target_column].isna().sum())
        ]
    }
)

                 metric_name    value
0                  row_count  2597699
1               column_count       27
2  duplicate_event_key_count        0
3       missing_target_count        0

In [84]:
# Documenting model roles for reference, predictors and target

click_model_field_catalog = pd.DataFrame(
    [
        ("user_id", "reference", "Viewer identifier for tracking and later diagnostics"),
        ("video_id", "reference", "Video identifier for tracking and later diagnostics"),
        ("creator_user_id", "reference", "Creator identifier for tracking and later diagnostics"),
        ("event_timestamp_ms", "reference", "Event timestamp for chronological ordering"),
        ("event_date", "reference", "Event date for chronological split and daily diagnostics"),
        ("traffic_source", "predictor", "Delivery source available at impression time"),
        ("feed_tab_id", "predictor", "Feed tab context available at impression time"),
        ("user_active_degree", "predictor", "User activity segment"),
        ("is_video_author", "predictor", "Whether the viewer is also a video author"),
        ("follow_user_num", "predictor", "Viewer follow count"),
        ("follow_user_num_range", "predictor", "Viewer follow count band"),
        ("fans_user_num", "predictor", "Viewer fans count"),
        ("fans_user_num_range", "predictor", "Viewer fans count band"),
        ("friend_user_num", "predictor", "Viewer friend count"),
        ("friend_user_num_range", "predictor", "Viewer friend count band"),
        ("register_days", "predictor", "Viewer registration age in days"),
        ("register_days_range", "predictor", "Viewer registration age band"),
        ("video_type", "predictor", "Video type"),
        ("video_upload_date", "predictor", "Video upload date"),
        ("video_upload_type", "predictor", "Video upload source type"),
        ("video_width", "predictor", "Video width"),
        ("video_height", "predictor", "Video height"),
        ("video_orientation", "predictor", "Video orientation"),
        ("music_type", "predictor", "Music type"),
        ("video_age_days", "predictor", "Video age at impression date"),
        ("event_content_duration_ms", "predictor", "Content duration available on the event"),
        ("is_click", "target", "Primary prediction target")
    ],
    columns = ["field_name", "model_role", "business_definition"]
)

click_model_field_catalog

                   field_name model_role                                business_definition
0                     user_id  reference  Viewer identifier for tracking and later diagn...
1                    video_id  reference  Video identifier for tracking and later diagno...
2             creator_user_id  reference  Creator identifier for tracking and later diag...
3          event_timestamp_ms  reference         Event timestamp for chronological ordering
4                  event_date  reference  Event date for chronological split and daily d...
5              traffic_source  predictor       Delivery source available at impression time
6                 feed_tab_id  predictor      Feed tab context available at impression time
7          user_active_degree  predictor                              User activity segment
8             is_video_author  predictor          Whether the viewer is also a video author
9             follow_user_num  predictor                                Viewer follow count
10      follow_user_num_range  predictor                           Viewer follow count band
11              fans_user_num  predictor                                  Viewer fans count
12        fans_user_num_range  predictor                             Viewer fans count band
13            friend_user_num  predictor                                Viewer friend count
14      friend_user_num_range  predictor                           Viewer friend count band
15              register_days  predictor                    Viewer registration age in days
16        register_days_range  predictor                       Viewer registration age band
17                 video_type  predictor                                         Video type
18          video_upload_date  predictor                                  Video upload date
19          video_upload_type  predictor                           Video upload source type
20                video_width  predictor                                        Video width
21               video_height  predictor                                       Video height
22          video_orientation  predictor                                  Video orientation
23                 music_type  predictor                                         Music type
24             video_age_days  predictor                       Video age at impression date
25  event_content_duration_ms  predictor            Content duration available on the event
26                   is_click     target                          Primary prediction target

In [85]:
# Creating chronological train, validation and test splits

train_end_date = pd.Timestamp("2022-04-28")
validation_end_date = pd.Timestamp("2022-05-03")

click_model_dataset["model_split"] = np.select(
    [
        click_model_dataset["event_date"] <= train_end_date,
        (click_model_dataset["event_date"] > train_end_date) & (click_model_dataset["event_date"] <= validation_end_date),
        click_model_dataset["event_date"] > validation_end_date
    ],
    [
        "train", "validation", "test"
    ],
    default = "unassigned"
)

split_summary = (click_model_dataset
                 .groupby("model_split", as_index = False)
                 .agg(row_count = ("user_id", "size"),
                      distinct_user_count = ("user_id", "nunique"),
                      distinct_video_count = ("video_id", "nunique"),
                      click_count = ("is_click", "sum")
    )
)

split_summary["click_rate_percent"] = (
    split_summary["click_count"] / split_summary["row_count"] * 100
).round(4)

split_summary

  model_split  row_count  distinct_user_count  distinct_video_count  click_count  click_rate_percent
0        test     600478                26362                  7320       128259             21.3595
1       train    1533888                26842                  7583       628565             40.9785
2  validation     463333                26103                  7392       107906             23.2891

In [86]:
# Checking split composition and traffic-source balance
split_traffic_source_summary = (click_model_dataset
                                .groupby(["model_split", "traffic_source"], as_index = False)
                                .agg(row_count = ("user_id", "size"),
                                     click_count = ("is_click", "sum")
    )
)

split_traffic_source_summary["click_rate_percent"] = (
    split_traffic_source_summary["click_count"] / split_traffic_source_summary["row_count"] * 100
).round(4)

split_traffic_source_summary["split_traffic_share_percent"] = (
    split_traffic_source_summary["row_count"] / split_traffic_source_summary.groupby("model_split")["row_count"].transform("sum") * 100
).round(4)

display(split_summary)
display(split_traffic_source_summary.sort_values(["model_split", "traffic_source"]).reset_index(drop = True))

  model_split  row_count  distinct_user_count  distinct_video_count  click_count  click_rate_percent
0        test     600478                26362                  7320       128259             21.3595
1       train    1533888                26842                  7583       628565             40.9785
2  validation     463333                26103                  7392       107906             23.2891

  model_split traffic_source  row_count  click_count  click_rate_percent  split_traffic_share_percent
0        test         random     527865        95922             18.1717                      87.9075
1        test       standard      72613        32337             44.5333                      12.0925
2       train         random     288335        48140             16.6959                      18.7977
3       train       standard    1245553       580425             46.5998                      81.2023
4  validation         random     369849        64872             17.5401                      79.8236
5  validation       standard      93484        43034             46.0335                      20.1764

In [87]:
# Saving the full click modeling dataset for reuse

upload_dataframe_to_parquet_blob(click_model_dataset,
                                 container_names["curated"],
                                 "click_model_dataset.parquet"
)

pd.DataFrame(
    {
        "dataset_name": ["click_model_dataset"],
        "row_count": [len(click_model_dataset)],
        "column_count": [click_model_dataset.shape[1]],
        "split_count": [click_model_dataset["model_split"].nunique()]
    }
)

          dataset_name  row_count  column_count  split_count
0  click_model_dataset    2597699            28            3

In [88]:
# Diagnosing split drift before modeling decisions

click_model_split_diagnostics = (
    split_traffic_source_summary[
        [
            "model_split",
            "traffic_source",
            "row_count",
            "split_traffic_share_percent",
            "click_rate_percent"
        ]
    ]
    .sort_values(["model_split", "traffic_source"])
    .reset_index(drop = True)
)

split_drift_summary = pd.DataFrame(
    {
        "metric_name": ["train_standard_share_percent", "validation_standard_share_percent", "test_standard_share_percent",
                        "train_click_rate_percent", "validation_click_rate_percent", "test_click_rate_percent",
                        "standard_share_range_percent_points", "click_rate_range_percent_points",
        ],
        "value": [
            float(
                click_model_split_diagnostics.loc[
                    (click_model_split_diagnostics["model_split"] == "train") 
                    & (click_model_split_diagnostics["traffic_source"] == "standard"),
                    "split_traffic_share_percent"
                ].iloc[0]
            ),
            float(
                click_model_split_diagnostics.loc[
                    (click_model_split_diagnostics["model_split"] == "validation")
                    & (click_model_split_diagnostics["traffic_source"] == "standard"),
                    "split_traffic_share_percent"
                ].iloc[0]
            ),
            float(
                click_model_split_diagnostics.loc[
                    (click_model_split_diagnostics["model_split"] == "test")
                    & (click_model_split_diagnostics["traffic_source"] == "standard"),
                    "split_traffic_share_percent"
                ].iloc[0]
            ),
            float(
                split_summary.loc[
                    split_summary["model_split"] == "train",
                    "click_rate_percent"
                ].iloc[0]
            ),
            float(
                split_summary.loc[
                    split_summary["model_split"] == "validation",
                    "click_rate_percent"
                ].iloc[0]
            ),
            float(
                split_summary.loc[
                    split_summary["model_split"] == "test",
                    "click_rate_percent"
                ].iloc[0]
            ),
            round(
                split_traffic_source_summary.loc[
                    split_traffic_source_summary["traffic_source"] == "standard",
                    "split_traffic_share_percent"
                ].max()
                - split_traffic_source_summary.loc[
                    split_traffic_source_summary["traffic_source"] == "standard",
                    "split_traffic_share_percent"
                ].min(),
                4
            ),
            round(
                split_summary["click_rate_percent"].max()
                - split_summary["click_rate_percent"].min(),
                4
            )
        ]
    }
)

display(click_model_split_diagnostics)
display(split_drift_summary)

  model_split traffic_source  row_count  split_traffic_share_percent  click_rate_percent
0        test         random     527865                      87.9075             18.1717
1        test       standard      72613                      12.0925             44.5333
2       train         random     288335                      18.7977             16.6959
3       train       standard    1245553                      81.2023             46.5998
4  validation         random     369849                      79.8236             17.5401
5  validation       standard      93484                      20.1764             46.0335

                           metric_name    value
0         train_standard_share_percent  81.2023
1    validation_standard_share_percent  20.1764
2          test_standard_share_percent  12.0925
3             train_click_rate_percent  40.9785
4        validation_click_rate_percent  23.2891
5              test_click_rate_percent  21.3595
6  standard_share_range_percent_points  69.1098
7      click_rate_range_percent_points  19.6190

In [89]:
# Isolating standard traffic for the main click model path

click_model_dataset_standard_traffic = (click_model_dataset.loc[click_model_dataset["traffic_source"] == "standard"]
                                        .copy()
                                        .sort_values(["event_date", "event_timestamp_ms", "user_id", "video_id"])
                                        .reset_index(drop = True)
)

standard_traffic_split_summary = (click_model_dataset_standard_traffic
                                  .groupby("model_split", as_index = False)
                                  .agg(row_count = ("user_id", "size"),
                                       distinct_user_count = ("user_id", "nunique"),
                                       distinct_video_count = ("video_id", "nunique"),
                                       click_count = ("is_click", "sum")
    )
)

standard_traffic_split_summary["click_rate_percent"] = (
    standard_traffic_split_summary["click_count"] / standard_traffic_split_summary["row_count"] * 100
).round(4)

standard_traffic_split_summary

  model_split  row_count  distinct_user_count  distinct_video_count  click_count  click_rate_percent
0        test      72613                19357                  5217        32337             44.5333
1       train    1245553                26631                  7545       580425             46.5998
2  validation      93484                20550                  5277        43034             46.0335

In [90]:
# Confirming that the standard-traffic split is stable enough

standard_traffic_split_diagnostics = pd.DataFrame(
    {
        "metric_name": ["train_row_count", "validation_row_count", "test_row_count",
                        "train_click_rate_percent", "validation_click_rate_percent", "test_click_rate_percent",
                        "click_rate_range_percent_points", "duplicate_event_key_count", "missing_target_count"
        ],
        "value": [
            int(
                standard_traffic_split_summary.loc[
                    standard_traffic_split_summary["model_split"] == "train",
                    "row_count"
                ].iloc[0]
            ),
            int(
                standard_traffic_split_summary.loc[
                    standard_traffic_split_summary["model_split"] == "validation",
                    "row_count"
                ].iloc[0]
            ),
            int(
                standard_traffic_split_summary.loc[
                    standard_traffic_split_summary["model_split"] == "test",
                    "row_count"
                ].iloc[0]
            ),
            float(
                standard_traffic_split_summary.loc[
                    standard_traffic_split_summary["model_split"] == "train",
                    "click_rate_percent"
                ].iloc[0]
            ),
            float(
                standard_traffic_split_summary.loc[
                    standard_traffic_split_summary["model_split"] == "validation",
                    "click_rate_percent"
                ].iloc[0]
            ),
            float(
                standard_traffic_split_summary.loc[
                    standard_traffic_split_summary["model_split"] == "test",
                    "click_rate_percent"
                ].iloc[0]
            ),
            round(
                standard_traffic_split_summary["click_rate_percent"].max()
                - standard_traffic_split_summary["click_rate_percent"].min(),
                4
            ),
            int(
                click_model_dataset_standard_traffic.duplicated(
                    subset = ["user_id", "video_id", "event_timestamp_ms"]
                ).sum()
            ),
            int(click_model_dataset_standard_traffic["is_click"].isna().sum())
        ]
    }
)

standard_traffic_split_diagnostics

                       metric_name         value
0                  train_row_count  1.245553e+06
1             validation_row_count  9.348400e+04
2                   test_row_count  7.261300e+04
3         train_click_rate_percent  4.659980e+01
4    validation_click_rate_percent  4.603350e+01
5          test_click_rate_percent  4.453330e+01
6  click_rate_range_percent_points  2.066500e+00
7        duplicate_event_key_count  0.000000e+00
8             missing_target_count  0.000000e+00

In [91]:
# Saving the standard-traffic modeling dataset for production use
upload_dataframe_to_parquet_blob(click_model_dataset_standard_traffic,
                                 container_names["curated"],
                                 "click_model_dataset_standard_traffic.parquet"
)

pd.DataFrame(
    {
        "dataset_name": ["click_model_dataset_standard_traffic"],
        "row_count": [len(click_model_dataset_standard_traffic)],
        "column_count": [click_model_dataset_standard_traffic.shape[1]],
        "split_count": [click_model_dataset_standard_traffic["model_split"].nunique()]
    }
)

                           dataset_name  row_count  column_count  split_count
0  click_model_dataset_standard_traffic    1411650            28            3

In [92]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (average_precision_score,
                             brier_score_loss,
                             log_loss,
                             roc_auc_score
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.dummy import DummyClassifier

In [93]:
# Separating modeling inputs, target, and chronological splits

modeling_base = click_model_dataset_standard_traffic.copy()

target_column = "is_click"
split_column = "model_split"

reference_columns = ["user_id", "video_id", "creator_user_id", "event_timestamp_ms", "event_date",
                     "video_upload_date", split_column
]

feature_columns = ["traffic_source", "feed_tab_id", "user_active_degree", "is_video_author", "follow_user_num",
                   "follow_user_num_range", "fans_user_num", "fans_user_num_range", "friend_user_num", "friend_user_num_range",
                   "register_days", "register_days_range", "video_type", "video_upload_type", "video_width", "video_height",
                   "video_orientation", "music_type", "video_age_days", "event_content_duration_ms"
]

missing_model_columns = [column_name
                         for column_name in feature_columns + [target_column, split_column]
                         if column_name not in modeling_base.columns
]

if missing_model_columns:
    raise KeyError(f"Missing required modeling columns : {missing_model_columns}")


train_mask = modeling_base[split_column].eq("train")
validation_mask = modeling_base[split_column].eq("validation")
test_mask = modeling_base[split_column].eq("test")

X_train = modeling_base.loc[train_mask, feature_columns].copy()
y_train = modeling_base.loc[train_mask, target_column].copy()

X_validation = modeling_base.loc[validation_mask, feature_columns].copy()
y_validation = modeling_base.loc[validation_mask, target_column].copy()

X_test = modeling_base.loc[test_mask, feature_columns].copy()
y_test = modeling_base.loc[test_mask, target_column].copy()


pd.DataFrame(
    {
        "split_name": ["train", "validation", "test"],
        "row_count": [len(X_train), len(X_validation), len(X_test)],
        "click_rate_percent": [round(y_train.mean() * 100, 4),
                               round(y_validation.mean() * 100, 4),
                               round(y_test.mean() * 100, 4)
        ]
    }
)

   split_name  row_count  click_rate_percent
0       train    1245553             46.5998
1  validation      93484             46.0335
2        test      72613             44.5333

In [94]:
# Defining the preprocessing plan for mixed feature types
categorical_features = ["traffic_source",
                        "feed_tab_id",
                        "user_active_degree",
                        "follow_user_num_range",
                        "fans_user_num_range",
                        "friend_user_num_range",
                        "register_days_range",
                        "video_type",
                        "video_upload_type",
                        "video_orientation",
                        "music_type"
]

numeric_features = ["is_video_author",
                    "follow_user_num",
                    "fans_user_num",
                    "friend_user_num",
                    "register_days",
                    "video_width",
                    "video_height",
                    "video_age_days",
                    "event_content_duration_ms"
]

preprocessor = ColumnTransformer(
    transformers = [
        (
            "categorical",
            Pipeline(
                steps = [
                    ("imputer", SimpleImputer(strategy = "most_frequent")),
                    ("encoder", OneHotEncoder(handle_unknown = "ignore"))
                ]
            ),
            categorical_features
        ),
        (
            "numeric",
            Pipeline(
                steps = [
                    ("imputer", SimpleImputer(strategy = "median")),
                    ("scaler", StandardScaler())
                ]
            ),
            numeric_features
        )
    ],
    remainder = "drop"
)

In [95]:
# Training baseline and logistic click models for comparison

dummy_model = Pipeline(
    steps = [
        ("preprocessor", preprocessor),
        ("classifier", DummyClassifier(strategy = "prior"))
    ]
)

logistic_click_model = Pipeline(
    steps = [
        ("preprocessor", preprocessor),
        (
            "classifier",
            LogisticRegression(max_iter = 1000,
                               class_weight = "balanced",
                               random_state = 42
            )
        )
    ]
)

dummy_model.fit(X_train, y_train)
logistic_click_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['traffic_source',
                                                   'feed_tab_id',
                                                   'user_active_degree',
                                                   'follow_user_num_range',
                                                   'fans_user_num_range',
                                                   'friend_user_num_range',
                                                   'register_days_range',
                                                   'vide...
                                                 ('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['is_video_author',
                                                   'follow_user_num',
                                                   'fans_user_num',
                                                   'friend_user_num',
                                                   'register_days',
                                                   'video_width',
                                                   'video_height',
                                                   'video_age_days',
                                                   'event_content_duration_ms'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [96]:
# Evaluating model quality with ranking and calibration metrics

def evaluate_binary_classifier(model, X_frame, y_true, split_name):
    predicted_probability = model.predict_proba(X_frame)[ : , 1]

    return {"split_name": split_name,
            "row_count": int(len(y_true)),
            "positive_rate_percent": round(y_true.mean() * 100, 4),
            "roc_auc": round(roc_auc_score(y_true, predicted_probability), 6),
            "average_precision": round(average_precision_score(y_true, predicted_probability), 6),
            "log_loss": round(log_loss(y_true, predicted_probability), 6),
            "brier_score": round(brier_score_loss(y_true, predicted_probability), 6)
    }

model_evaluation_summary = pd.DataFrame(
    [
        {"model_name": "dummy_click_model", **evaluate_binary_classifier(dummy_model, X_validation, y_validation, "validation")},
        {"model_name": "dummy_click_model", **evaluate_binary_classifier(dummy_model, X_test, y_test, "test")},
        {"model_name": "logistic_click_model", **evaluate_binary_classifier(logistic_click_model, X_validation, y_validation, "validation")},
        {"model_name": "logistic_click_model", **evaluate_binary_classifier(logistic_click_model, X_test, y_test, "test")}
    ]
)

model_evaluation_summary

             model_name  split_name  row_count  positive_rate_percent   roc_auc  average_precision  log_loss  brier_score
0     dummy_click_model  validation      93484                46.0335  0.500000           0.460335  0.690062     0.248459
1     dummy_click_model        test      72613                44.5333  0.500000           0.445333  0.688018     0.247439
2  logistic_click_model  validation      93484                46.0335  0.656781           0.583613  0.637296     0.225342
3  logistic_click_model        test      72613                44.5333  0.646363           0.563044  0.641065     0.227126

In [97]:
# Scoring test impressions and checking score separation by decile

test_scored_impressions = modeling_base.loc[test_mask, reference_columns + feature_columns + [target_column]].copy()
test_scored_impressions["predicted_click_probability"] = logistic_click_model.predict_proba(X_test)[ : , 1]

test_scored_impressions["score_decile"] = pd.qcut(
    test_scored_impressions["predicted_click_probability"],
    q = 10,
    labels = False,
    duplicates = "drop"
)

test_score_decile_summary = (test_scored_impressions
                             .groupby("score_decile", as_index = False)
                             .agg(impression_count = ("user_id", "size"),
                                  actual_click_count = ("is_click", "sum"),
                                  average_predicted_click_probability = ("predicted_click_probability", "mean")
    )
    .sort_values("score_decile", ascending = False)
    .reset_index(drop = True)
)

test_score_decile_summary["actual_click_rate_percent"] = (
    test_score_decile_summary["actual_click_count"] / test_score_decile_summary["impression_count"] * 100
).round(4)

test_score_decile_summary["average_predicted_click_probability_percent"] = (
    test_score_decile_summary["average_predicted_click_probability"] * 100
).round(4)

test_score_decile_summary

   score_decile  impression_count  actual_click_count  average_predicted_click_probability  actual_click_rate_percent  average_predicted_click_probability_percent
0             9              7262                4491                             0.640171                    61.8425                                      64.0171
1             8              7261                4101                             0.590873                    56.4798                                      59.0873
2             7              7261                3913                             0.563557                    53.8906                                      56.3557
3             6              7261                3581                             0.541127                    49.3183                                      54.1127
4             5              7261                3434                             0.522790                    47.2938                                      52.2790
5             4              7262                3413                             0.507010                    46.9981                                      50.7010
6             3              7261                3301                             0.489726                    45.4621                                      48.9726
7             2              7261                3097                             0.462436                    42.6525                                      46.2436
8             1              7261                2386                             0.355366                    32.8605                                      35.5366
9             0              7262                 620                             0.088517                     8.5376                                       8.8517

In [98]:
# Extracting directional model signals for business interpretation
encoded_feature_names = logistic_click_model.named_steps["preprocessor"].get_feature_names_out()
logistic_coefficients = logistic_click_model.named_steps["classifier"].coef_[0]

logistic_feature_importance = pd.DataFrame(
    {
        "feature_name": encoded_feature_names,
        "coefficient": logistic_coefficients,
        "absolute_coefficient": np.abs(logistic_coefficients)
    }
).sort_values("absolute_coefficient", ascending = False).reset_index(drop = True)

top_positive_click_drivers = logistic_feature_importance.sort_values("coefficient", ascending = False).head(20).reset_index(drop = True)
top_negative_click_drivers = logistic_feature_importance.sort_values("coefficient", ascending = True).head(20).reset_index(drop = True)

display(top_positive_click_drivers)
display(top_negative_click_drivers)

                                        feature_name  coefficient  absolute_coefficient
0                         categorical__feed_tab_id_9     3.435293              3.435293
1                        categorical__feed_tab_id_10     1.611975              1.611975
2                         categorical__feed_tab_id_4     1.478394              1.478394
3                         categorical__feed_tab_id_1     1.132836              1.132836
4                         categorical__feed_tab_id_2     0.884750              0.884750
5                         categorical__video_type_AD     0.686651              0.686651
6                         categorical__feed_tab_id_7     0.654618              0.654618
7                 categorical__video_upload_type_Web     0.592489              0.592489
8              categorical__video_upload_type_Kmovie     0.555294              0.555294
9          categorical__video_upload_type_LongImport     0.550769              0.550769
10  categorical__video_upload_type_ShareFromOtherApp     0.394640              0.394640
11                      categorical__music_type_11.0     0.363129              0.363129
12        categorical__user_active_degree_low_active     0.333631              0.333631
13                       categorical__feed_tab_id_13     0.333274              0.333274
14           categorical__user_active_degree_day_new     0.294455              0.294455
15         categorical__video_upload_type_LongCamera     0.286073              0.286073
16        categorical__video_upload_type_ShortImport     0.265407              0.265407
17     categorical__user_active_degree_middle_active     0.228679              0.228679
18                       categorical__music_type_9.0     0.147100              0.147100
19         categorical__video_orientation_horizontal     0.140980              0.140980

                                  feature_name  coefficient  absolute_coefficient
0                   categorical__feed_tab_id_3    -2.865176              2.865176
1                   categorical__feed_tab_id_8    -2.333047              2.333047
2                  categorical__feed_tab_id_11    -1.914471              1.914471
3                   categorical__feed_tab_id_0    -1.240870              1.240870
4      categorical__user_active_degree_UNKNOWN    -1.065955              1.065955
5                  categorical__feed_tab_id_12    -0.796327              0.796327
6    categorical__video_upload_type_PictureSet    -0.692668              0.692668
7       categorical__video_upload_type_UNKNOWN    -0.619232              0.619232
8   categorical__video_upload_type_FollowShoot    -0.570328              0.570328
9                  categorical__music_type_8.0    -0.560285              0.560285
10              categorical__video_type_NORMAL    -0.549955              0.549955
11  categorical__video_upload_type_ShortCamera    -0.522499              0.522499
12  categorical__video_upload_type_LongPicture    -0.502695              0.502695
13             categorical__video_type_UNKNOWN    -0.407429              0.407429
14                  categorical__feed_tab_id_6    -0.387142              0.387142
15        categorical__traffic_source_standard    -0.270733              0.270733
16       categorical__video_orientation_square    -0.220925              0.220925
17       categorical__register_days_range_730+    -0.199124              0.199124
18     categorical__video_orientation_vertical    -0.190788              0.190788
19                  categorical__feed_tab_id_5    -0.182059              0.182059

In [99]:
# Rebuilding the standard-traffic modeling frame for the final path

standard_modeling_base = click_model_dataset_standard_traffic.copy()

standard_target_column = "is_click"
standard_split_column = "model_split"

standard_reference_columns = ["user_id", "video_id", "creator_user_id",
                              "event_timestamp_ms", "event_date",
                              "video_upload_date", standard_split_column
]

standard_feature_columns = ["feed_tab_id", "user_active_degree", "is_video_author", 
                            "follow_user_num", "follow_user_num_range",
                            "fans_user_num", "fans_user_num_range", 
                            "friend_user_num", "friend_user_num_range", "register_days",
                            "register_days_range", 
                            "video_type", "video_upload_type", "video_width", "video_height", "video_orientation", 
                            "music_type", "video_age_days", "event_content_duration_ms"
]

missing_standard_model_columns = [
    column_name
    for column_name in standard_feature_columns + [standard_target_column, standard_split_column]
    if column_name not in standard_modeling_base.columns
]

if missing_standard_model_columns:
    raise KeyError(f"Missing required modeling columns : {missing_standard_model_columns}")


standard_train_mask = standard_modeling_base[standard_split_column].eq("train")
standard_validation_mask = standard_modeling_base[standard_split_column].eq("validation")
standard_test_mask = standard_modeling_base[standard_split_column].eq("test")

X_train_standard = standard_modeling_base.loc[standard_train_mask, standard_feature_columns].copy()
y_train_standard = standard_modeling_base.loc[standard_train_mask, standard_target_column].copy()

X_validation_standard = standard_modeling_base.loc[standard_validation_mask, standard_feature_columns].copy()
y_validation_standard = standard_modeling_base.loc[standard_validation_mask, standard_target_column].copy()

X_test_standard = standard_modeling_base.loc[standard_test_mask, standard_feature_columns].copy()
y_test_standard = standard_modeling_base.loc[standard_test_mask, standard_target_column].copy()


pd.DataFrame(
    {
        "split_name": ["train", "validation", "test"],
        "row_count": [len(X_train_standard), len(X_validation_standard), len(X_test_standard)],
        "click_rate_percent": [round(y_train_standard.mean() * 100, 4),
                               round(y_validation_standard.mean() * 100, 4),
                               round(y_test_standard.mean() * 100, 4)
        ]
    }
)

   split_name  row_count  click_rate_percent
0       train    1245553             46.5998
1  validation      93484             46.0335
2        test      72613             44.5333

In [100]:
# Defining and fitting the final standard-traffic model pipeline

standard_categorical_features = ["feed_tab_id", "user_active_degree", "follow_user_num_range", "fans_user_num_range",
                                 "friend_user_num_range", "register_days_range", "video_type",
                                 "video_upload_type", "video_orientation", "music_type"
]

standard_numeric_features = ["is_video_author", "follow_user_num", "fans_user_num", "friend_user_num", "register_days",
                             "video_width", "video_height", "video_age_days", "event_content_duration_ms"
]

standard_preprocessor = ColumnTransformer(
    transformers = [
        (
            "categorical",
            Pipeline(
                steps = [
                    ("imputer", SimpleImputer(strategy = "most_frequent")),
                    ("encoder", OneHotEncoder(handle_unknown = "ignore"))
                ]
            ),
            standard_categorical_features
        ),
        (
            "numeric",
            Pipeline(
                steps = [
                    ("imputer", SimpleImputer(strategy = "median")),
                    ("scaler", StandardScaler())
                ]
            ),
            standard_numeric_features
        )
    ],
    remainder = "drop"
)

standard_dummy_model = Pipeline(
    steps = [
        ("preprocessor", standard_preprocessor),
        ("classifier", DummyClassifier(strategy = "prior"))
    ]
)

standard_logistic_click_model = Pipeline(
    steps = [
        ("preprocessor", standard_preprocessor),
        (
            "classifier",
            LogisticRegression(max_iter = 1000,
                               class_weight = "balanced",
                               random_state = 42
            )
        )
    ]
)

standard_dummy_model.fit(X_train_standard, y_train_standard)
standard_logistic_click_model.fit(X_train_standard, y_train_standard)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['feed_tab_id',
                                                   'user_active_degree',
                                                   'follow_user_num_range',
                                                   'fans_user_num_range',
                                                   'friend_user_num_range',
                                                   'register_days_range',
                                                   'video_type',
                                                   'video_up...
                                                 ('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['is_video_author',
                                                   'follow_user_num',
                                                   'fans_user_num',
                                                   'friend_user_num',
                                                   'register_days',
                                                   'video_width',
                                                   'video_height',
                                                   'video_age_days',
                                                   'event_content_duration_ms'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [101]:
# Summarizing final model performance on validation and test splits
standard_model_evaluation_summary = pd.DataFrame(
    [
        {
            "model_name": "standard_dummy_click_model",
            **evaluate_binary_classifier(standard_dummy_model,
                                         X_validation_standard,
                                         y_validation_standard,
                                         "validation"
            )
        },
        {
            "model_name": "standard_dummy_click_model",
            **evaluate_binary_classifier(standard_dummy_model,
                                         X_test_standard,
                                         y_test_standard,
                                         "test"
            )
        },
        {
            "model_name": "standard_logistic_click_model",
            **evaluate_binary_classifier(standard_logistic_click_model,
                                         X_validation_standard,
                                         y_validation_standard,
                                         "validation"
            )
        },
        {
            "model_name": "standard_logistic_click_model",
            **evaluate_binary_classifier(standard_logistic_click_model,
                                         X_test_standard,
                                         y_test_standard,
                                         "test"
            )
        }
    ]
)

standard_model_evaluation_summary

                      model_name  split_name  row_count  positive_rate_percent   roc_auc  average_precision  log_loss  brier_score
0     standard_dummy_click_model  validation      93484                46.0335  0.500000           0.460335  0.690062     0.248459
1     standard_dummy_click_model        test      72613                44.5333  0.500000           0.445333  0.688018     0.247439
2  standard_logistic_click_model  validation      93484                46.0335  0.656571           0.583219  0.637392     0.225380
3  standard_logistic_click_model        test      72613                44.5333  0.646208           0.562669  0.641121     0.227147

In [102]:
# Scoring the final test set and validating probability ranking

standard_test_scored_impressions = (
    standard_modeling_base.loc[
        standard_test_mask,
        standard_reference_columns + standard_feature_columns + [standard_target_column]
    ]
    .copy()
)

standard_test_scored_impressions["predicted_click_probability"] = (
    standard_logistic_click_model.predict_proba(X_test_standard)[ : , 1]
)

standard_test_scored_impressions["score_decile"] = pd.qcut(
    standard_test_scored_impressions["predicted_click_probability"],
    q = 10,
    labels = False,
    duplicates = "drop"
)

standard_test_score_decile_summary = (
    standard_test_scored_impressions
    .groupby("score_decile", as_index = False)
    .agg(impression_count = ("user_id", "size"),
         actual_click_count = ("is_click", "sum"),
         average_predicted_click_probability = ("predicted_click_probability", "mean")
    )
    .sort_values("score_decile", ascending = False)
    .reset_index(drop = True)
)

standard_test_score_decile_summary["actual_click_rate_percent"] = (
    standard_test_score_decile_summary["actual_click_count"] / standard_test_score_decile_summary["impression_count"] * 100
).round(4)

standard_test_score_decile_summary["average_predicted_click_probability_percent"] = (
    standard_test_score_decile_summary["average_predicted_click_probability"] * 100
).round(4)

standard_test_score_decile_summary

   score_decile  impression_count  actual_click_count  average_predicted_click_probability  actual_click_rate_percent  average_predicted_click_probability_percent
0             9              7262                4485                             0.640438                    61.7598                                      64.0438
1             8              7261                4099                             0.590985                    56.4523                                      59.0985
2             7              7261                3903                             0.563592                    53.7529                                      56.3592
3             6              7261                3599                             0.540991                    49.5662                                      54.0991
4             5              7261                3440                             0.522807                    47.3764                                      52.2807
5             4              7262                3398                             0.507114                    46.7915                                      50.7114
6             3              7261                3315                             0.489823                    45.6549                                      48.9823
7             2              7261                3093                             0.462371                    42.5974                                      46.2371
8             1              7261                2385                             0.354834                    32.8467                                      35.4834
9             0              7262                 620                             0.088690                     8.5376                                       8.8690

In [103]:
# Extracting final model drivers for reporting use

standard_encoded_feature_names = (
    standard_logistic_click_model.named_steps["preprocessor"].get_feature_names_out()
)

standard_logistic_coefficients = (
    standard_logistic_click_model.named_steps["classifier"].coef_[0]
)

standard_logistic_feature_importance = (
    pd.DataFrame(
        {
            "feature_name": standard_encoded_feature_names,
            "coefficient": standard_logistic_coefficients,
            "absolute_coefficient": np.abs(standard_logistic_coefficients),
        }
    )
    .sort_values("absolute_coefficient", ascending = False)
    .reset_index(drop = True)
)

standard_top_positive_click_drivers = (standard_logistic_feature_importance
                                       .sort_values("coefficient", ascending = False)
                                       .head(20)
                                       .reset_index(drop = True)
)

standard_top_negative_click_drivers = (standard_logistic_feature_importance
                                       .sort_values("coefficient", ascending = True)
                                       .head(20)
                                       .reset_index(drop = True)
)

display(standard_top_positive_click_drivers)
display(standard_top_negative_click_drivers)

                                        feature_name  coefficient  absolute_coefficient
0                         categorical__feed_tab_id_9     3.324646              3.324646
1                        categorical__feed_tab_id_10     1.497227              1.497227
2                         categorical__feed_tab_id_4     1.474444              1.474444
3                         categorical__feed_tab_id_1     1.133910              1.133910
4                         categorical__feed_tab_id_2     0.881882              0.881882
5                         categorical__feed_tab_id_7     0.655028              0.655028
6                         categorical__video_type_AD     0.647854              0.647854
7                 categorical__video_upload_type_Web     0.575487              0.575487
8              categorical__video_upload_type_Kmovie     0.540185              0.540185
9          categorical__video_upload_type_LongImport     0.533568              0.533568
10  categorical__video_upload_type_ShareFromOtherApp     0.394777              0.394777
11                      categorical__music_type_11.0     0.340601              0.340601
12        categorical__user_active_degree_low_active     0.336698              0.336698
13                       categorical__feed_tab_id_13     0.319276              0.319276
14         categorical__video_upload_type_LongCamera     0.279221              0.279221
15           categorical__user_active_degree_day_new     0.266890              0.266890
16        categorical__video_upload_type_ShortImport     0.248335              0.248335
17     categorical__user_active_degree_middle_active     0.214141              0.214141
18                       categorical__music_type_9.0     0.137219              0.137219
19          categorical__fans_user_num_range_[5k,1w)     0.077025              0.077025

                                   feature_name  coefficient  absolute_coefficient
0                    categorical__feed_tab_id_3    -2.858486              2.858486
1                    categorical__feed_tab_id_8    -2.360317              2.360317
2                   categorical__feed_tab_id_11    -1.825047              1.825047
3                    categorical__feed_tab_id_0    -1.238606              1.238606
4       categorical__user_active_degree_UNKNOWN    -1.033879              1.033879
5                   categorical__feed_tab_id_12    -0.803857              0.803857
6     categorical__video_upload_type_PictureSet    -0.688190              0.688190
7        categorical__video_upload_type_UNKNOWN    -0.633513              0.633513
8                categorical__video_type_NORMAL    -0.590379              0.590379
9                   categorical__music_type_8.0    -0.588924              0.588924
10   categorical__video_upload_type_LongPicture    -0.561416              0.561416
11   categorical__video_upload_type_FollowShoot    -0.538658              0.538658
12   categorical__video_upload_type_ShortCamera    -0.507725              0.507725
13              categorical__video_type_UNKNOWN    -0.424099              0.424099
14                   categorical__feed_tab_id_6    -0.390342              0.390342
15        categorical__video_orientation_square    -0.240334              0.240334
16        categorical__register_days_range_730+    -0.217451              0.217451
17      categorical__video_orientation_vertical    -0.202904              0.202904
18    categorical__follow_user_num_range_(0,10]    -0.189240              0.189240
19  categorical__fans_user_num_range_[10w,100w)    -0.172783              0.172783

In [104]:
# Saving scored test impressions for downstream consumption
upload_dataframe_to_parquet_blob(standard_test_scored_impressions,
                                 container_names["model_output"],
                                 "click_model_scored_standard_traffic_test.parquet"
)

pd.DataFrame(
    {
        "dataset_name": ["click_model_scored_standard_traffic_test"],
        "row_count": [len(standard_test_scored_impressions)],
        "column_count": [standard_test_scored_impressions.shape[1]]
    }
)

                               dataset_name  row_count  column_count
0  click_model_scored_standard_traffic_test      72613            29

In [105]:
# Ranking creators by standard-traffic engagement quality

creator_performance_summary = (
    impression_analysis_base.loc[impression_analysis_base["traffic_source"] == "standard"]
    .groupby("creator_user_id", as_index = False)
    .agg(impression_count = ("user_id", "size"),
         distinct_video_count = ("video_id", "nunique"),
         click_count = ("is_click", "sum"),
         meaningful_watch_count = ("is_meaningful_watch", "sum"),
         high_value_engagement_count = ("is_high_value_engagement", "sum")
    )
)

creator_performance_summary["click_rate_percent"] = (
    creator_performance_summary["click_count"] / creator_performance_summary["impression_count"] * 100
).round(4)

creator_performance_summary["meaningful_watch_rate_percent"] = (
    creator_performance_summary["meaningful_watch_count"] / creator_performance_summary["impression_count"] * 100
).round(4)

creator_performance_summary["high_value_engagement_rate_percent"] = (
    creator_performance_summary["high_value_engagement_count"] / creator_performance_summary["impression_count"] * 100
).round(4)

creator_hve_interval = creator_performance_summary.apply(
    lambda row: wilson_interval(
        row["high_value_engagement_count"],
        row["impression_count"]
    ),
    axis = 1
)

creator_performance_summary["high_value_engagement_rate_center"] = [
    interval[0] for interval in creator_hve_interval
]

creator_performance_summary["high_value_engagement_rate_margin"] = [
    interval[1] for interval in creator_hve_interval
]

creator_performance_summary["high_value_engagement_rate_lower_bound_percent"] = (
    (
        creator_performance_summary["high_value_engagement_rate_center"] - creator_performance_summary["high_value_engagement_rate_margin"]
    ) * 100
).round(4)

creator_priority_summary = (
    creator_performance_summary.loc[creator_performance_summary["impression_count"] >= 1000]
    .sort_values(
        [
            "high_value_engagement_rate_lower_bound_percent",
            "click_rate_percent",
            "impression_count",
        ],
        ascending = [False, False, False]
    )
    .reset_index(drop = True)
)

creator_priority_summary.head(30)

,creator_user_id,impression_count,distinct_video_count,click_count,meaningful_watch_count,high_value_engagement_count,click_rate_percent,meaningful_watch_rate_percent,high_value_engagement_rate_percent,high_value_engagement_rate_center,high_value_engagement_rate_margin,high_value_engagement_rate_lower_bound_percent
0,8346076,4887,1,2991,2472,120,61.2032,50.5832,2.4555,0.024928,0.004354,2.0575
1,663099,2008,1,1303,1021,45,64.8904,50.8466,2.2410,0.023322,0.006532,1.6790
2,7813686,1284,1,723,393,27,56.3084,30.6075,2.1028,0.022457,0.007965,1.4491
3,5468688,1647,1,875,628,29,53.1269,38.1299,1.7608,0.018730,0.006443,1.2287
4,2517717,2218,2,955,662,35,43.0568,29.8467,1.5780,0.016617,0.005249,1.1368
5,23123,1544,2,1081,797,23,70.0130,51.6192,1.4896,0.016100,0.006154,0.9946
6,5570290,1185,1,698,585,18,58.9030,49.3671,1.5190,0.016756,0.007127,0.9630
7,7941871,2509,2,1529,1175,33,60.9406,46.8314,1.3153,0.013897,0.004516,0.9381
8,2562264,1823,1,565,358,23,30.9929,19.6380,1.2617,0.013641,0.005220,0.8422
9,803086,2121,1,1447,1259,26,68.2225,59.3588,1.2258,0.013140,0.004761,0.8379
10,3448364,2415,1,1601,1136,29,66.2940,47.0393,1.2008,0.012783,0.004409,0.8374
11,55307,1475,1,543,227,19,36.8136,15.3898,1.2881,0.014147,0.005885,0.8262
12,4838224,2834,1,1634,585,32,57.6570,20.6422,1.1291,0.011953,0.003943,0.8010
13,3692717,1102,1,560,383,14,50.8167,34.7550,1.2704,0.014397,0.006815,0.7582
14,7959597,2179,1,1534,1459,24,70.3993,66.9573,1.1014,0.011875,0.004462,0.7413
15,7328539,1052,1,552,383,13,52.4715,36.4068,1.2357,0.014132,0.006896,0.7236
16,1127691,1069,1,794,699,12,74.2750,65.3882,1.1225,0.012976,0.006543,0.6433
17,5609437,2791,1,1108,660,26,39.6990,23.6474,0.9316,0.009990,0.003625,0.6365
18,1665717,1246,4,801,568,13,64.2857,45.5859,1.0433,0.011938,0.005831,0.6107
19,80854,1788,2,821,576,17,45.9172,32.2148,0.9508,0.010559,0.004615,0.5945
20,5446992,1334,1,872,496,13,65.3673,37.1814,0.9745,0.011153,0.005449,0.5704
21,6810556,1904,1,1264,907,17,66.3866,47.6366,0.8929,0.009917,0.004335,0.5582
22,5345439,9799,1,5992,4945,69,61.1491,50.4643,0.7042,0.007235,0.001667,0.5568
23,7221011,1375,1,913,753,13,66.4000,54.7636,0.9455,0.010821,0.005288,0.5534
24,764815,2675,2,1569,1259,22,58.6542,47.0654,0.8224,0.008930,0.003492,0.5437
25,4018269,1293,1,735,515,12,56.8445,39.8299,0.9281,0.010734,0.005418,0.5317
26,7920306,3658,1,739,141,28,20.2023,3.8546,0.7654,0.008171,0.002870,0.5301
27,5802877,6674,2,3115,2052,47,46.6737,30.7462,0.7042,0.007326,0.002026,0.5300
28,7898710,1721,1,1074,785,15,62.4056,45.6130,0.8716,0.009810,0.004521,0.5289
29,3843914,4836,1,2662,2103,35,55.0455,43.4864,0.7237,0.007629,0.002420,0.5209

In [106]:
# Exporting presentation-ready tables for Power BI use

presentation_tables = {"overall_funnel_summary": overall_funnel_summary,
                       "traffic_source_funnel_summary": traffic_source_funnel_summary,
                       "feed_tab_funnel_summary": feed_tab_funnel_summary,
                       "daily_rate_decomposition": daily_rate_decomposition,
                       "priority_segment_opportunities": priority_segment_opportunities,
                       "post_click_priority_segments": post_click_priority_segments,
                       "post_click_conversion_by_traffic_source": post_click_conversion_by_traffic_source,
                       "video_tag_performance": video_tag_performance,
                       "creator_priority_summary": creator_priority_summary,
                       "standard_model_evaluation_summary": standard_model_evaluation_summary,
                       "standard_test_score_decile_summary": standard_test_score_decile_summary,
                       "standard_top_positive_click_drivers": standard_top_positive_click_drivers,
                       "standard_top_negative_click_drivers": standard_top_negative_click_drivers
}

def make_parquet_safe(dataframe):
    parquet_safe_frame = dataframe.copy()

    for column_name in parquet_safe_frame.columns:
        if parquet_safe_frame[column_name].dtype == "object":
            parquet_safe_frame[column_name] = parquet_safe_frame[column_name].astype("string")

    return parquet_safe_frame

presentation_export_summary = []


# Converting export tables into parquet-safe formats before saving
for table_name, table_frame in presentation_tables.items():
    parquet_safe_table = make_parquet_safe(table_frame)

    upload_dataframe_to_parquet_blob(
        parquet_safe_table,
        container_names["presentation"],
        f"{table_name}.parquet"
    )

    presentation_export_summary.append(
        {
            "table_name": table_name,
            "row_count": len(parquet_safe_table),
            "column_count": parquet_safe_table.shape[1]
        }
    )

pd.DataFrame(presentation_export_summary)

                                 table_name  row_count  column_count
0                    overall_funnel_summary          9             3
1             traffic_source_funnel_summary          2            18
2                   feed_tab_funnel_summary         15            18
3                  daily_rate_decomposition         30            20
4            priority_segment_opportunities         46            13
5              post_click_priority_segments         25            13
6   post_click_conversion_by_traffic_source          2            16
7                     video_tag_performance         46             7
8                  creator_priority_summary        260            12
9         standard_model_evaluation_summary          4             8
10       standard_test_score_decile_summary         10             6
11      standard_top_positive_click_drivers         20             3
12      standard_top_negative_click_drivers         20             3